### ISSUE TITLE
Image rendering is distorted

### ISSUE THREAD

**Issue by bausmeier** [software-mansion/react-native-svg#1013]
I'm trying to render an image within an SVG but when I do the image becomes distorted.

A simplified version of my code looks something like this:

```js
<Svg width={84} height={88} viewPort="0 0 84 88">
  <Image width={84} height={88} href={require('./badge.png')} />
</Svg>
```

(Not sure if the dimensions need to be specified in all of those places? I've tried a few variations with no visible difference)

And the result is:

![2019-05-17-152855_grim](https://user-images.githubusercontent.com/116090/57931305-742e0780-78b8-11e9-99e7-d492c189a25d.png)

If I replace the SVG with the React Native Image equivalent then the image looks clear:

```js
<Image style={{width: 84, height: 88}} source={require('./badge.png')} />
```

And the result is:

![2019-05-17-152912_grim](https://user-images.githubusercontent.com/116090/57931321-7d1ed900-78b8-11e9-80af-961d6663c570.png)

If I attach my debugger on [this line](https://github.com/react-native-community/react-native-svg/blob/235ded3d09e1b0a05957d3ba8a42424916d34f38/android/src/main/java/com/horcrux/svg/ImageView.java#L193) then the value of `vbRect` is `(0.0, 0.0, 84.0, 88.0)` and `renderRect` is `(0.0, 0.0, 220.5, 231)` so it looks like the image dimensions are being scaled up according to my device (2.65 scale) but the view box is not.

The same issue occurs if I include `@2x` and `@3x` versions of my image as well.

Is there a way that I can keep the dimensions of my image correct independent of device scale?

**Comment by msand** [comment]
Interesting, looks like the image would've been downscaled and upscaled back again. Is this iOS, Android or both?

**Comment by msand** [comment]
I just notice you have viewPort rather than viewBox, try setting the width and height attributes of the Image element to the native resolution of the image, and set viewBox to that size, and try again.

**Comment by bausmeier** [comment]
Yes that's what it looks like to me. I've only been able to test on Android so far but will hopefully have an iOS build to test on on Monday.

I managed to temporarily get the image to render nicely by hacking at the code a bit but I haven't been able to come up with a fix that works for all cases.

**Comment by bausmeier** [comment]
Ah sorry viewPort is just a typo on this issue. It's viewBox in the code.

**Comment by bausmeier** [comment]
I just tested all of these variations and the appearance is the same for all of them:

```js
<Svg viewBox="0 0 84 88" width={84} height={88}>
  <Image href={require('./badge.png')} />
</Svg>
```

```js
<Svg viewBox="0 0 84 88" width={84} height={88}>
  <Image width={84} height={88} href={require('./badge.png')} />
</Svg>
```

```js
<Svg width={84} height={88}>
  <Image width={84} height={88} href={require('./badge.png')} />
</Svg>
```

```js
<Svg width={84} height={88}>
  <Image href={require('./badge.png')} />
</Svg>
```

**Comment by bausmeier** [comment]
As far as I know this is still an problem.

**Comment by SaayanBiswas98** [comment]
import { Text, SafeAreaView, StyleSheet,Image } from 'react-native';

// You can import supported modules from npm
import { Card } from 'react-native-paper';

// or any files within the Snack
import AssetExample from './components/AssetExample';

export default function App() {
  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.paragraph}>
        Change code in the editor and watch it change on your phone! Save to get a shareable url.
      </Text>
      <Svg width={84} height={88} viewPort="0 0 84 88">
  <Image width={84} height={88} href={require('./assets/snack-icon.png')} />
</Svg>
      <Card>
        <AssetExample />
      </Card>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
  paragraph: {
    margin: 24,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
  },
});
const Svg=()=>{
  
}
My code worked fine

**Comment by SaayanBiswas98** [comment]
![code](https://github.com/software-mansion/react-native-svg/assets/76898125/0883e186-637a-41bf-9f08-9b19dea4a0a0)
