### ISSUE TITLE
Android: Different colour displays on my SVG in v11 V v10

### ISSUE THREAD

**Issue by RuairiOliver** [software-mansion/react-native-svg#1263]
Hi,

Moving from v10.1.0 to v11.0.1 causes different colours to display on my svg. Where previously it displayed black at the top of my svg it now displays grey. Works fine on iOS. Same issue whether I use SvgCSS or the imports from react-native-svg.

Screenshot attached of how it should look.

![Screenshot 2020-01-24 at 17 37 54](https://user-images.githubusercontent.com/2650468/73090400-3619c680-3ed0-11ea-92a5-f8abd29bd80a.png)

```
import { SvgCss } from "react-native-svg";

const xml = `
<svg viewBox="0 0 375 812" style="enable-background:new 0 0 375 812;" xml:space="preserve"> <!-- Change me for size -->
<style>
.st0{opacity:0.6;}
.st1{fill:url(#SVGID_1_);}
.st2{opacity:0.05;fill:#00AFA9;} <!-- Secondary -->
.st3{opacity:0.2;}
.st4{opacity:0.1;fill:#00AFA9;} <!-- Secondary -->
</style>
<g id="Layer_1">
<rect width="375" height="812"/>
<g class="st0">
  <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="-109.25" y1="702.75" x2="484.25" y2="109.25">
    <stop  offset="0" style="stop-color:#00AFA9"/>
    <stop  offset="0.6095" style="stop-color:#000000"/> <!-- Primary -->
    <stop  offset="1" style="stop-color:#000000"/> <!-- Primary -->
  </linearGradient>
  <rect class="st1" width="375" height="812"/>
</g>
<polygon class="st2" points="375,812 0,812 375,437 	"/>
<polygon class="st2" points="375,650 375,812 0,812 0,275 	"/>
<polygon class="st3" points="0,0 375,0 0,375 	"/>
<polygon class="st4" points="0,162 0,0 375,0 375,537 	"/>
</g>
<g id="Layer_2">
</g>
</svg>

`;

<SvgCss xml={xml} width="100%" height="100%" />
```

**Comment by msand** [comment]
Can you try this? (added background color)

```jsx
import React from 'react';
import {SvgCss} from 'react-native-svg';

const xml = `
<svg viewBox="0 0 375 812" style="enable-background:new 0 0 375 812;background-color: black" xml:space="preserve"> <!-- Change me for size -->
<style>
.st0{opacity:0.6;}
.st1{fill:url(#SVGID_1_);}
.st2{opacity:0.05;fill:#00AFA9;} <!-- Secondary -->
.st3{opacity:0.2;}
.st4{opacity:0.1;fill:#00AFA9;} <!-- Secondary -->
</style>
<g id="Layer_1">
<rect width="375" height="812"/>
<g class="st0">
  <linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="-109.25" y1="702.75" x2="484.25" y2="109.25">
    <stop  offset="0" style="stop-color:#00AFA9"/>
    <stop  offset="0.6095" style="stop-color:#000000"/> <!-- Primary -->
    <stop  offset="1" style="stop-color:#000000"/> <!-- Primary -->
  </linearGradient>
  <rect class="st1" width="375" height="812"/>
</g>
<polygon class="st2" points="375,812 0,812 375,437 	"/>
<polygon class="st2" points="375,650 375,812 0,812 0,275 	"/>
<polygon class="st3" points="0,0 375,0 0,375 	"/>
<polygon class="st4" points="0,162 0,0 375,0 375,537 	"/>
</g>
<g id="Layer_2">
</g>
</svg>

`;

export default () => <SvgCss xml={xml} width="100%" height="100%" />;

```

**Comment by dschep** [comment]
I also experienced a similar issue. Many of my SVG files are no longer rendering correctly. They render fine on iOS, older versions (v9), and on every other SVG renderer I've tried.

Here's what it should look like (you can use this svg for testing, it's the exact one I'm using.):
https://gist.github.com/dschep/3b640364df9e2b0aecd593902afbe630

Here's what it looks like on Android:
![Screenshot_20200410-091905_Expo](https://user-images.githubusercontent.com/667763/78993913-e204a280-7b0c-11ea-915e-12fdb2b1f2ce.jpg)

**Comment by dl-husky73** [comment]
Thanks dschep, but isn't this solution live now?   I thought I saw the background color issue was pushed live and I am using latest.  So shouldn't above fix already be implemented?

**Comment by dschep** [comment]
oh. dunno tbh. upgrading is tricky for me, i can't jsut grab a version and buidl it bc I'm using expo.

**Comment by dl-husky73** [comment]
> I also experienced a similar issue. Many of my SVG files are no longer rendering correctly. They render fine on iOS, older versions (v9), and on every other SVG renderer I've tried.
> 
> Here's what it should look like (you can use this svg for testing, it's the exact one I'm using.):
> https://gist.github.com/dschep/3b640364df9e2b0aecd593902afbe630
> 
> Here's what it looks like on Android:
> ![Screenshot_20200410-091905_Expo](https://user-images.githubusercontent.com/667763/78993913-e204a280-7b0c-11ea-915e-12fdb2b1f2ce.jpg)

What exact version did you move to that fixed this problem?

**Comment by dschep** [comment]
Expo SDK 36 which I'm using uses 9.13.3 of this library.

**Comment by dschep** [comment]
This issue is not yet resolved. Please don't close. In fact the issue now seems to affect iOS as well. Here is a snack reproducing the bug with v12.1.0 https://snack.expo.io/@ourstreets/ae8eb9

Here's a screenshot: 
![Screenshot_20200713-094333](https://user-images.githubusercontent.com/667763/87313849-7d345c00-c4f0-11ea-9515-266a5d0a35d8.png)


For reference, here's how every other tool(chrome, firefox, gimp, inkscape, etc etc etc, version 10 of this library!) renders the same svg:
![BREAD-GRAINS](https://user-images.githubusercontent.com/667763/87316657-0ef19880-c4f4-11ea-9c74-5d61fbdd7274.png)

**Comment by WoLewicki** [comment]
This issue looks like a duplicate of https://github.com/software-mansion/react-native-svg/issues/1543. I tested the code you sent with the fix provided in that issue and it seems to resolve the problem. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
