### ISSUE TITLE
SvgCss not available on version 9.9.2

### ISSUE THREAD

**Issue by DLesage25** [software-mansion/react-native-svg#1307]
I'm trying to add custom CSS to an SVG. The documentation states I should use SvgCss and pass an xml string on to it, but SvgCss is not available in version 9.9.2 as an export from the `react-native-svg` library.

**Comment by msand** [comment]
Can you try the latest version?

**Comment by WoLewicki** [comment]
This issue is no longer present so I will close it. Feel free to comment here if something is wrong and we can always reopen it then.
