### ISSUE TITLE
Invariant Violation: View config not found for name (svg content)

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [software-mansion/react-native-svg#1312]
My app can't render svg file because this error code.

this is error code.

error
```
Exception: Invariant Violation: View config not found for name <?xml version="1.0" encoding="UTF-8" standalone="no" ?><svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 235.032 75.093" width="235.032" height="75.093"><path d="M8.828 
```

I'm struggling with this issue for about a day.But I couldn't reach solution...

could you help me??
Do you have any idea of the cause and resolution.

metro.config.js
```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false
        }
      }),
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
```

babel.config.js
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'babel-plugin-module-resolver',
      {
        root: ['./src'],
        extensions: [
          '.ios.ts',
          '.android.ts',
          '.ts',
          '.ios.tsx',
          '.android.tsx',
          '.tsx',
          '.jsx',
          '.js',
          '.json',
          '.svg'
        ],
        alias: {
          '@navigations': './src/navigations',
          '@models': './src/models',
          '@reducks': './src/store/reducks',
          '@screens': './src/screens',
          '@apis': './src/apis',
          '@utils': './src/utils',
          '@plugins': './src/plugins',
          '@assets': './src/assets',
        },
      },
    ],
    [
      "babel-plugin-inline-import",
      {
        "extensions": [".svg"]
      }
    ]
  ],
};
```
the code
```
import Logo from '../assets/images/logo.svg';

<Logo width={50} height={50} />
```

I tried this code, the error not occured,but image was not rendered.
```
import {SvgXml} from 'react-native-svg';
<SvgXml xml={SvgXml} width={50} height={50} />
```

basic information
```
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-svg": "^12.0.3",
    "react-native-svg-transformer": "^0.14.3",
```

**Comment by msand** [comment]
Hard to say, could you make a git repo?

**Comment by Yoshihide-Nishimoto** [comment]
@msand

> Hard to say, could you make a git repo?

It's hard for NDA.
So I'll try to make minimux repo.
thx

**Comment by tracyhyq** [comment]
@Yoshihide-Nishimoto the same to me? Have you solved the problem?

**Comment by nguyenvm** [comment]
The same error with me. I try to upload svg file and use SvgCssUri instead, it's working
<img width="939" alt="Screen Shot 2020-05-20 at 23 32 27" src="https://user-images.githubusercontent.com/48425675/82472329-33338900-9af2-11ea-9808-8a3cc947d011.png">

**Comment by vanminhnguyenbmt** [comment]
The same error with me. I try to upload svg file and use SvgCssUri instead, it's working
<img width="939" alt="Screen Shot 2020-05-20 at 23 32 27" src="https://user-images.githubusercontent.com/48425675/82472329-33338900-9af2-11ea-9808-8a3cc947d011.png">

**Comment by nguyenvm** [comment]
I have tried another way. Covert content of svg file to React Native Component via `https://react-svgr.com/playground/?native=true&typescript=true` and it's working as well.

**Comment by vanminhnguyenbmt** [comment]
I have tried another way. Covert content of svg file to React Native Component via `https://react-svgr.com/playground/?native=true&typescript=true` and it's working as well.

**Comment by brokrete-oleksii** [comment]
@Yoshihide-Nishimoto 
```
 [
      "babel-plugin-inline-import",
      {
        "extensions": [".svg"]
      }
    ]
```
This block is the reason for the problem. Remove it from babel and will be good. I had the same error and removing helped.

**Comment by WoLewicki** [comment]
This issue seems to be a problem in configuration rather than a bug in the library. I will close it then. Feel free to comment here if something is wrong and we can always reopen it then.
