### ISSUE TITLE
Problem in drawing horizontal BarChart in ios

### ISSUE THREAD

**Issue by aligol20** [software-mansion/react-native-svg#1316]
I drawing horizontal bar chart with bellow code,It works fine in android
but nothing show in ios
<img width="223" alt="Screen Shot 2020-03-19 at 9 49 46 AM" src="https://user-images.githubusercontent.com/8493249/77037616-f8fd1c80-69c6-11ea-89c3-a3a167c9559f.png">
![WhatsApp Image 2020-03-19 at 09 51 25](https://user-images.githubusercontent.com/8493249/77037778-5729ff80-69c7-11ea-96be-31d05ce542bd.jpeg)

 in ios
# Bug

/**
 * Component that renders HorizontalBarChart
 */
import React from 'react';
import { Dimensions, View } from 'react-native';
import { Text } from 'react-native-animatable';
import { Rect, Svg } from 'react-native-svg';
import { horizontal_bar_chart_style } from './Styles';

const width = Dimensions.get('screen').width;
const height = Dimensions.get('screen').height;

const TEXT_LENGTH = 50;
const TEXT_HEIGHT = 29;
const OFFSET = TEXT_LENGTH / 2 - TEXT_HEIGHT / 2;

interface Props {
  data: {label: string; value: number}[];
  round: any;
}
/**
 *
 * @param data - raw data comes with props and then we render them
 * more details about how we draw charts is available at @link https://github.com/react-native-community/react-native-svg
 */
const HorizontalBarChart: React.FC<Props> = ({data, round}) => {
  const SVGHeight = 170;
  const SVGWidth = 0.5 * width;

  return (
    <View style={horizontal_bar_chart_style.container}>
      <Svg width={SVGWidth} height={0.3 * height}>
        <View
          style={{
            flexDirection: 'column',
            justifyContent: 'space-between',
          }}>
          {data.map((item, index) => (
            <View style={{flexDirection: 'row'}}>
              <Rect
                key={'bar' + index}
                x={0.5 * width - item.value}
                y={index * 0.05 * width}
                rx={7}
                height={11}
                width={item.value}
                fill="#7732AD"
              />
            </View>
          ))}
        </View>
      </Svg>
    </View>
  );
};
export default HorizontalBarChart;

**Comment by WoLewicki** [comment]
Could you post a repository where this bug can be reproduced easily? It would help with fixing the issue.

**Comment by bohdanprog** [comment]
Hello @aligol20,
We tried to reproduce that problem by drawing BarChart, and in our case, everything worked well. 
If you still have the same problem feel free to reopen the issue, Thank you.
