### ISSUE TITLE
It doesn't work on androidX. Which version should I choose？

### ISSUE THREAD

**Issue by G1King** [software-mansion/react-native-svg#1327]
Since our other libraries do not use androidx, I want to make it compatible, so which version should I choose，thanks

**Comment by soroushm** [comment]
@G1King use jetifier
`yarn add jetifier`
`npx jetifier`

**Comment by XingtianXin** [comment]
My Android projects donot support AndroidX, if we don't want to add AndroidX,
which react-native-svg version should we use ?

**Comment by neonardos** [comment]
My Android Project don't support AndroidX, and I tried with react-native-svg@9.3.7 and it works. @G1King @XingtianXin

**Comment by WoLewicki** [comment]
I believe it is not an issue anymore so I will close this issue. Feel free to comment here if something is wrong and we can always reopen it then.
