### ISSUE TITLE
Does <SvgUri /> component support cache?

### ISSUE THREAD

**Issue by hakkikonu** [software-mansion/react-native-svg#1328]
Does `<SvgUri />` component support **cache** like react native's `<Image />` component?

For example I'm using cache for my remote png files like 

```
<Image
     source={{
     uri: "https://example.com/image.png",
     cache: 'force-cache',
     }}
/>

```

**Comment by msand** [comment]
It uses fetch provided by react-native, so it respects the http protocol and the http cache related headers as is. If you want something more than that, I'd recommend copying the code from SvgUri and modify it to your needs.

**Comment by creat-or** [comment]
I also needed caching and solved it like this:

```javascript
// CachedSVGUri.js
import React, {Component} from 'react';
import {SvgFromXml} from 'react-native-svg';
import SVGCacheService from '../services/storage/SVGCacheService';

export async function fetchCached(uri) {
    const cached = await SVGCacheService.getSvg(uri);
    if (cached) {
        return cached;
    } else {
        const response = await fetch(uri);
        const svg = await response.text();
        SVGCacheService.setSvg(uri, svg);
        return svg;
    }
}

export default class CachedSvgUri extends Component {
    state = {xml: null};
    componentDidMount() {
        this.fetch(this.props.uri);
    }
    componentDidUpdate(prevProps) {
        const {uri} = this.props;
        if (uri !== prevProps.uri) {
            this.fetch(uri);
        }
    }
    async fetch(uri) {
        try {
            this.setState({xml: uri ? await fetchCached(uri) : null});
        } catch (e) {
            console.error(e);
        }
    }
    render() {
        const {
            props,
            state: {xml},
        } = this;
        return <SvgFromXml xml={xml} override={props} />;
    }
}
```

```javascript
// SVGCacheService.js
import AsyncStorage from '@react-native-community/async-storage';

const ASYNC_STORAGE_KEY = 'svg-cache';

let data = null;

const loadData = async () => {
    const defaultData = {
        svgs: {},
    };

    const result = await AsyncStorage.getItem(ASYNC_STORAGE_KEY);
    data = result ? await JSON.parse(result) : defaultData;
    data = {...defaultData, ...data};
};

export default class SVGCacheService {
    static async setSvg(uri, svg) {
        const oldData = data || {};

        const newData = {
            ...oldData,
            svgs: {
                ...oldData.svgs,
                [uri]: svg,
            },
        };

        data = newData;

        await AsyncStorage.setItem(ASYNC_STORAGE_KEY, JSON.stringify(newData));
    }

    static async getSvg(uri) {
        if (data === null) await loadData();
        return data.svgs[uri];
    }
}

```

**Comment by danyasnov** [comment]
@creat-or nice solution
but storing svg strings in an object can create a memory leak

**Comment by creat-or** [comment]
@danyasnov hey there!
thank you for your answer and the hint with the memory leak. do you know why this is the case and how you could test for that?
thank you!

**Comment by WoLewicki** [comment]
Since the solution provided by @27leaves seems like a good option, I believe we can close this issue. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by sovetski** [comment]
Same problem here, maybe @27leaves's solution works, but as @danyasnov said, it is not an optimal solution.
This kind of functionality should be implemented in the library itself, which application will fetch X time the same SVG? Generally you do the fetch the first time and that's all...

@WoLewicki as you closed the issue, if for you the @27leaves's solution is fine, maybe you can implement him code in the library?

Thanks

**Comment by kravchenko-anton** [comment]
const [svgContent, setSvgContent] = useState<string | null>(null)
	useEffect(() => {
		const getFromAsyncStorageSvgGenre = async () => {
			const svg = await AsyncStorage.getItem('svgGenre' + svgUri)
			if (svg) {
				console.log('svg from async storage ' + svgUri)
				setSvgContent(svg)
				return
			} else {
				const svg = await fetch(getFileUrl(svgUri)).then(response =>
					response.text()
				)
				await AsyncStorage.setItem('svgGenre' + svgUri, svg)
				console.log('svg from fetch ' + svgUri)
				return svg
			}
		}
		getFromAsyncStorageSvgGenre()
	}, [svgUri])

**Comment by rvasseur31** [comment]
A solution with React Query :
```
import {SvgXml, UriProps} from "react-native-svg"
import {useQuery} from "@tanstack/react-query"

async function fetchText(uri: string) {
  const response = await fetch(uri)
  if (response.ok || (response.status === 0 && uri.startsWith("file://"))) {
    return await response.text()
  }
  throw new Error(`Fetching ${uri} failed with status ${response.status}`)
}

export function SvgUri(props: UriProps) {
  const {uri, fallback} = props

  const {data, error} = useQuery({
    queryKey: [uri],
    queryFn: () => fetchText(uri ?? ""),
    enabled: !!uri,
  })

  if (error || !data) {
    return fallback ?? null
  }

  return <SvgXml xml={data} override={props} fallback={fallback} />
}
```
