### ISSUE TITLE
Svg from local not working

### ISSUE THREAD

**Issue by sinhpn92** [software-mansion/react-native-svg#1329]
I tried to load svg from local, but It's still not working (do not have anything to showing).
I used react-native version 0.62.
I did add to metro.config.js like that: 
const { getDefaultConfig } = require('metro-config');
```
module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts },
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```
And Use by that:
```
...
import IconBack from '../../../../resources/icon/ic_arrow_left_2.svg';
...
<IconBack width={24} height={24} />
...
```

Have any suggest to solve this? :((
Thanks for your time!

**Comment by ssghajar** [comment]
have you installed `react-native-svg-transformer` package before `metro-config.js` setups?

**Comment by Malikkhoja** [comment]
facing same issue. Yes we have installed react-native-svg-transformer package as well. On RN 0.62.2 we are facing this issue

**Comment by asherccohen** [comment]
Any help?

**Comment by WoLewicki** [comment]
Is this still an issue? If so could you provide a simple repo with a reproduction of the issue?

**Comment by bohdanprog** [comment]
Hello @asherccohen, @Malikkhoja-zz, @sinhpn92
Do you still have that error?
