### ISSUE TITLE
stroke/strokeWidth doesn't work for SvgUri or SvgXml on iOS?

### ISSUE THREAD

**Issue by blackmad** [software-mansion/react-native-svg#1335]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug

I'm trying to style an svg with no in-line styles and I can't get it to render on iOS using the latest version of react-native-svg. Manually adding styles to the xml works fine. It is broken for both SvgXml and SvgUri. I have included links to expo snacks that show the bug.

#### Unexpected behavior

broken version in snack (SvgXml seems to ignore stroke and strokeWidth): https://snack.expo.io/W7ygrQOne --> broken in iOS, works in android

working version in snack (putting stroke and stroke-width inline : https://snack.expo.io/qptVLgipr --> running this in the iOS env

**Comment by msand** [comment]
Interesting, seems to work in plain react-native with the latest version at least.

**Comment by msand** [comment]
If you need it to work in expo, one workaround might be to use https://react-svgr.com/playground/ and move the spreading of props to a G element instead of the Svg root like this:

```jsx
import * as React from 'react';
import Svg, { G, Path } from 'react-native-svg';

function SvgComponent(props) {
  return (
    <Svg viewBox="0 0 511 511">
      <G {...props}>
        <Path d="M131.5 96c-11.537 0-21.955 8.129-29.336 22.891C95.61 132 92 149.263 92 167.5s3.61 35.5 10.164 48.609C109.545 230.871 119.964 239 131.5 239s21.955-8.129 29.336-22.891C167.39 203 171 185.737 171 167.5s-3.61-35.5-10.164-48.609C153.455 104.129 143.037 96 131.5 96zm15.92 113.401C142.78 218.679 136.978 224 131.5 224s-11.28-5.321-15.919-14.599C110.048 198.334 107 183.453 107 167.5s3.047-30.834 8.581-41.901C120.22 116.321 126.022 111 131.5 111s11.28 5.321 15.919 14.599C152.953 136.666 156 151.547 156 167.5s-3.047 30.834-8.58 41.901z" />
        <Path d="M474.852 158.011c-1.263-40.427-10.58-78.216-26.555-107.262C430.298 18.023 405.865 0 379.5 0h-248c-26.365 0-50.798 18.023-68.797 50.749C45.484 82.057 36 123.52 36 167.5s9.483 85.443 26.703 116.751C80.702 316.977 105.135 335 131.5 335a57.57 57.57 0 005.867-.312 7.51 7.51 0 002.133.312h48a7.5 7.5 0 000-15h-16c10.686-8.524 20.436-20.547 28.797-35.749 4.423-8.041 8.331-16.756 11.703-26.007V503.5a7.501 7.501 0 0011.569 6.3l20.704-13.373 20.716 13.374a7.498 7.498 0 008.134 0l20.729-13.376 20.729 13.376a7.49 7.49 0 004.066 1.198c1.416 0 2.832-.4 4.07-1.2l20.699-13.372 20.726 13.374a7.5 7.5 0 008.133 0l20.732-13.377 20.738 13.377a7.5 7.5 0 008.126.003l20.783-13.385 20.783 13.385a7.5 7.5 0 0011.561-6.305v-344a7.377 7.377 0 00-.146-1.488zM187.154 277.023C171.911 304.737 152.146 320 131.5 320s-40.411-15.263-55.654-42.977C59.824 247.891 51 208.995 51 167.5s8.824-80.391 24.846-109.523C91.09 30.263 110.854 15 131.5 15s40.411 15.263 55.654 42.977C203.176 87.109 212 126.005 212 167.5s-8.824 80.391-24.846 109.523zm259.563 204.171a7.5 7.5 0 00-8.122 0l-20.78 13.383-20.742-13.38a7.5 7.5 0 00-8.131 0l-20.732 13.376-20.729-13.376a7.497 7.497 0 00-8.136.002l-20.699 13.373-20.727-13.375a7.498 7.498 0 00-8.133 0l-20.728 13.375-20.718-13.375a7.499 7.499 0 00-8.137.001L227 489.728V271h8.5a7.5 7.5 0 000-15H227v-96.5c0-.521-.054-1.03-.155-1.521-1.267-40.416-10.577-78.192-26.548-107.231C191.936 35.547 182.186 23.524 171.5 15h208c20.646 0 40.411 15.263 55.654 42.977C451.176 87.109 460 126.005 460 167.5V256h-.5a7.5 7.5 0 000 15h.5v218.749l-13.283-8.555z" />
        <Path d="M283.5 256h-16a7.5 7.5 0 000 15h16a7.5 7.5 0 000-15zM331.5 256h-16a7.5 7.5 0 000 15h16a7.5 7.5 0 000-15zM379.5 256h-16a7.5 7.5 0 000 15h16a7.5 7.5 0 000-15zM427.5 256h-16a7.5 7.5 0 000 15h16a7.5 7.5 0 000-15z" />
      </G>
    </Svg>
  );
}

export default function App() {
  return (
    <SvgComponent width="100%" height="100%" strokeWidth={5} stroke="black" />
  );
}

```

**Comment by blackmad** [comment]
re: wei

> Interesting, seems to work in plain react-native with the latest version at least.

**Comment by blackmad** [comment]
Thanks for the reply @msand 

re: translating to spreading props, I was hoping to store svgs in the cloud / in blobs, so I'm still hoping there's a way I can make it work from svg strings.

re: not working in expo - is that something to debug in react-native-svg or something I should file a bug against expo for?

**Comment by blackmad** [comment]
I guess expo knows it's incompatible with v12 :-/

Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-screens - expected version range: ~2.2.0 - actual version installed: ^2.4.0
 - react-native-svg - expected version range: 11.0.1 - actual version installed: ^12.0.3
 - @react-native-community/masked-view - expected version range: 0.1.6 - actual version installed: ^0.1.7
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]

**Comment by WoLewicki** [comment]
This issue looks like a duplicate of https://github.com/software-mansion/react-native-svg/issues/1543. I tested the code you sent with the fix provided in that issue and it seems to resolve the problem. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by TalhaAbid1** [comment]
Issue For Me Is I Use Figma And When I Download SVG
its  stroke Width is Like this  `stroke-width={5}`

## Solution
Simply Change it To  `strokeWidth={5}`

It Worked For me
