### ISSUE TITLE
On the Android platform, when using currentColor as the fill value, the opacity property is ignored.

### ISSUE THREAD

**Issue by gaodeng** [software-mansion/react-native-svg#1345]
#### Unexpected behavior

On the Android platform, when using currentColor as the fill value, the opacity property is ignored. The iOS platform has no such problems

![Simulator Screen Shot - iPhone 11 - 2020-04-14 at 14 02 29](https://user-images.githubusercontent.com/1118249/79192858-15706580-7e5c-11ea-9f34-577908258b12.png)
![Screenshot_1586844684](https://user-images.githubusercontent.com/1118249/79192862-17d2bf80-7e5c-11ea-8c46-1920c41e7490.png)

## Environment info

```bash
 "react-native-svg": "^12.1.0",
```

## Steps To Reproduce
```javascript

 let xml = `<?xml version="1.0" encoding="utf-8"?>
  <svg version="1.1" id="e98f3141-fbb2-4194-a12f-8ac40d4ee285"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200"
     style="enable-background:new 0 0 200 200;" xml:space="preserve">
  <title>listen_now_inactive</title>
  <path fill="currentColor" d="M85.3,24.3h-59c-6.2,0-11.3,5-11.3,11.1c0,0.1,0,0.1,0,0.2v8.7h92.8l-8.3-12.5C96.2,27.2,90.9,24.4,85.3,24.3z"
    />
  <g>
    <path fill="currentColor" opacity="0.1" d="M173.7,44.3H15v119c0,0.1,0,0.1,0,0.2c0,6.2,5.1,11.2,11.3,11.1h147.4c0.1,0,0.1,0,0.2,0
      c6.2,0,11.2-5.1,11.1-11.3V55.6c0-0.1,0-0.1,0-0.2C185,49.3,179.9,44.3,173.7,44.3z M127.6,114.1l-47.3,20.8
      c-0.6,0.3-1.3,0.4-2,0.4c-2.8,0-5.1-2.3-5.1-5.1V88.7c0-0.7,0.1-1.4,0.4-2c1.1-2.6,4.1-3.7,6.7-2.6l47.3,20.8
      c1.3,0.5,2.2,1.5,2.8,2.7C131.5,110.1,130.2,113,127.6,114.1z"/>
    <path fill="currentColor" d="M127.6,104.8L80.3,84c-2.6-1.1-5.5,0-6.7,2.6c-0.3,0.6-0.4,1.3-0.4,2v41.5c0,2.8,2.3,5.1,5.1,5.1
      c0.7,0,1.4-0.1,2-0.4l47.3-20.8c2.6-1.1,3.8-4,2.8-6.6C129.9,106.2,128.9,105.3,127.6,104.8z"/>
  </g>
  </svg>`;

 <SvgCss xml={xml} width="100" height="100" color="red" />

```

Describe what you expected to happen:
 The renderings of iOS and Android platforms should look the same

**Comment by gaodeng** [comment]
?

**Comment by deansimcox** [comment]
I'm also seeing this issue in version 11.0.1.
Both the opacity and fill-opacity attributes are ignored when currentColor is used.

**Comment by NuckChorris** [comment]
I am also seeing this issue, it's a real nuisance :(

**Comment by rafaelsevla** [comment]
i have same problem in 12.1.0

**Comment by vishwasHK7** [comment]
I am also facing this issue. Any workaround  please. Thanks in adcance.

**Comment by vishwasHK7** [comment]
> I am also facing this issue. Any workaround please. Thanks in advance.
> 
> `"react-native-svg": "12.1.0",`

Hi All,

I wrote on workaround. to make i work in iOS And Android by wrapping with wrapper component:

**Usage:**
`<SVGWrapper width={128} height={128} color={theme.primaryColor} xml={congratulations} />`

**SVGWrapper.js**
```
import React from 'react';
import { SvgFromXml } from 'react-native-svg';
import COLORS from '../../utils/COLORS';

const SVGWrapper = props => {
  const { color = COLORS.PREMIER, xml = '' } = props;
  const icon = xml.replace('currentColor', color);
  return <SvgFromXml {...props} xml={icon} />;
};

export default SVGWrapper;
```

**Comment by psnfrench** [comment]
I faced the same issue too, but a workaround that worked for me was to change the opacity to the style prop ie.
change:
`opacity="0.4"`
to:
`style="opacity:0.4"`

**Comment by ecklf** [comment]
Facing the same issue on Android with `stroke="currentColor"`. I work around by setting the color via prop for now.

**Comment by niklavsBariss** [comment]
@vishwasHK7 , how do you import the xml as string to use `replace`?

**Comment by thgh** [comment]
Here is a workaround:



```ts
const ExampleIcon = () =>
  opacityWorkaround(
    <Svg>
      <Path opacity={0.3} d="M5 5h14v2H5V5z" fill="currentColor" />
    </Svg>,
    'blue'
  )

function opacityWorkaround(path: ReactElement, color: Color) {
  if (Array.isArray(path.props.children)) {
    path = deepSet(
      path,
      'props.children',
      path.props.children.map(child => opacityWorkaround(child, color))
    )
  }
  if (path.props.stroke === 'currentColor') {
    path = deepSet(path, 'props.stroke', color)
  }
  if (path.props.fill === 'currentColor') {
    path = deepSet(path, 'props.fill', color)
  }
  return path
}
```

**Comment by robrechtme** [comment]
Reproducible demo: https://snack.expo.dev/@robrechtme/bug-react-native-svg-currentcolor

**Comment by stvmachine** [comment]
> Here is a workaround:
> 
> ```ts
> const ExampleIcon = () =>
>   opacityWorkaround(
>     <Svg>
>       <Path opacity={0.3} d="M5 5h14v2H5V5z" fill="currentColor" />
>     </Svg>,
>     'blue'
>   )
> 
> function opacityWorkaround(path: ReactElement, color: Color) {
>   if (Array.isArray(path.props.children)) {
>     path = deepSet(
>       path,
>       'props.children',
>       path.props.children.map(child => opacityWorkaround(child, color))
>     )
>   }
>   if (path.props.stroke === 'currentColor') {
>     path = deepSet(path, 'props.stroke', color)
>   }
>   if (path.props.fill === 'currentColor') {
>     path = deepSet(path, 'props.fill', color)
>   }
>   return path
> }
> ```

From where are you getting that definition of `deepSet` that you are using?

**Comment by thgh** [comment]
This one: https://gist.github.com/LukeChannings/15c92cef5a016a8b21a0

**Comment by Alvi24** [comment]
i am facing the same error with fillOpacity(not opacity prop) on iOS
`"react-native-svg": "15.12.1"`
