### ISSUE TITLE
GIF images are not animated on iOS and doesn't work at all on Android

### ISSUE THREAD

**Issue by oleksandr-dziuban** [software-mansion/react-native-svg#1346]
Tried to display GIF image with react-native-svg, on iOS it renders, but without animations, on Android platform there is no image rendered at all.

react-native-svg: 12.1.0
react-native: 0.61.5

## Steps To Reproduce

Code:

```
   <Svg>
      <G>
        <Rect x={50} y={50} width={200} height={200} stroke={'green'} stokeWidth={2} />
        <Image x={50} y={50} width={200} height={200} href={{ uri: 'https://www.thisiscolossal.com/wp-content/uploads/2018/08/Isopoly_01.gif' }}></Image>
      </G>
    </Svg>
```
For Android all libraries to support GIF images are included.
```
    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
```

GIF animation works fine on iOS/Android with simple react-native ``<Image />``

**Comment by oleksandr-dziuban** [comment]
@msand Could you please check when you have free time? Thanks

**Comment by oleksandr-dziuban** [comment]
![Screenshot 2020-04-14 at 17 42 39](https://user-images.githubusercontent.com/5430640/79237918-66da1e00-7e77-11ea-9fa5-6fcc8e25876f.png)

**Comment by SlaUA** [comment]
same issue

**Comment by viktorbk** [comment]
Same problem

**Comment by bncvnc** [comment]
Any one found the solution?

**Comment by cheng-alvin** [comment]
I don't think do @bncvnc

**Comment by ysimoo** [comment]
+1

**Comment by cheng-alvin** [comment]
Hello all! My solution in my app is that I used a usestate variable and updated when I needed to render the gif which will cause a re-render. Because in my case, I found out that the issue only occurs when you have a unloaded gif. The gif requires it to be re-rendered for it to be animated.

Excuse the bad English plz.

**Comment by parthy007** [comment]
Fresco updates their version so the older versions might not work, here is there page [https://frescolib.org/docs/index.html](url) 

as of now their current versions are below : 

dependencies {

  // For animated GIF support
  implementation 'com.facebook.fresco:animated-gif:3.1.3'

  // For WebP support, including animated WebP
  implementation 'com.facebook.fresco:animated-webp:3.1.3'
  implementation 'com.facebook.fresco:webpsupport:3.1.3'

  // For WebP support, without animations
  implementation 'com.facebook.fresco:webpsupport:3.1.3'

  // Provide the Android support library (you might already have this or a similar dependency)
  implementation 'com.android.support:support-core-utils:24.2.1'
}

**Comment by Hopefulee** [comment]
just check out the react native doc

e.g.
https://reactnative.dev/docs/<your version>/image

**Comment by bohdanprog** [comment]
Hello @oleksandr-dziuban,
We already fixed that, but if you still have that issue feel free to reopen.
Thank you.
