### ISSUE TITLE
Add Type for SVG Imports in Typescript

### ISSUE THREAD

**Issue by wodka** [software-mansion/react-native-svg#1353]
# Feature Request

https://github.com/react-native-community/react-native-svg#use-with-svg-files suggests to import svg files.

## Why it is needed

For good type suggestions a new type must be added to allow this

## Possible implementation

```typescript
declare module '*.svg' {
  import Svg from 'react-native-svg'

  const content: Svg;
  export default content;
}
```

### Code sample

Please show how the new code could work, if doable

**Comment by reifnotreef** [comment]
Bumping this.

**Comment by bombillazo** [comment]
Bump!!! Please, this is breaking our linter 😄

**Comment by boghison** [comment]
Any workaround for this?

**Comment by bohdanprog** [comment]
Hello,
As I see, it was already implemented if you still have any suggestions feel free to open a new issue.
Thank you.
