### ISSUE TITLE
What is the fastest way to pipe Animated.Values to the RN-SVG matrix

### ISSUE THREAD

**Issue by asinning** [software-mansion/react-native-svg#1356]
There are a few different threads in this community on this subject, most notably https://github.com/react-native-community/react-native-svg/issues/556

Our ultimate objective is to pan and zoom within our rn-svg component. We have a fairly okay solution working in our emulators; it's good enough for iOS, not so good for Android.

As I understand it, there are two approaches to solving this problem. 

- The easiest for me to understand, the one we are using, is to use the native-bridge to pipe the Animated.Value change events to the `setNativeProps()` method on the ref of the RN-Group. As I understand it, the problem with this solution is that in order to capture the change-event on the Animated.Value, we have to do this within the available CPUs of the javascript VM. So, even though the Animated.Value tweening is done natively, and the transform-matrix is applied natively, the pipe between the two requires JS VM CPUs.

- The other solution looks like it involves using `Animated.createAnimatedComponent` to create a native-wrapper around the component we wish to animate. I'm not sure how I could attach a animated matrix to an Animated RN-SVG-Group. I will discuss that in the second section below

Here's the pseudo-code for our solution which uses the first approach:

```
  animationValues = {
    scale: 1,
    shiftX: 0,
    shiftY: 0,
  };

   transforms.scale.addListener(({ value }) => {
      this.animationValues.scale = value;
      this.update();
    });
    transforms.shiftX.addListener(({ value }) => {
      this.animationValues.shiftX = value;
      this.update();
    });
    transforms.shiftY.addListener(({ value }) => {
      this.animationValues.shiftY = value;
      this.update();
    });
 
   function update() {
       // do some math to transpose animationValues scale, shiftX and shiftY
      groupRef.setNativeProps({matrix: [scale, 0, 0, shiftX, shiftY])
    }

<SVG>
  <G ref={ref => groupRef = ref} ... >
  ...
</SVG>
```

So, here is what we have found with the second approach. It seems to work:

```
  const scale = new Animated.Value(1);
  const posX = new Animated.Value(0);
  const posY = new Animated.Value(0);

  const AG = Animated.createAnimatedComponent(G);

// This does nothing
<SVG>
  <AG matrix={[scale, 0, 0, scale, posX, posY]}>
  ...
</SVG>

However, this works great
<SVG>
  <AG x={posX} y={posY} scale={scale}>
  ...
</SVG>
```

**Comment by bohdanprog** [comment]
Hello,

If you are still facing that problem, please open a new issue and include a simple example. 
This will make it easier for us to assist you.
Thank you.
