### ISSUE TITLE
ref.toDataURL does not exist when using react-native-web

### ISSUE THREAD

**Issue by wood1986** [software-mansion/react-native-svg#1358]
# Bug

[Your example](https://github.com/react-native-community/react-native-svg/issues/855#issuecomment-471371812) is using

```js
onRef = ref => {
    if (ref && !this.state.base64) {
      ref.toDataURL(
        base64 => {
          this.setState({ base64 });
        },
        { width: 200, height: 200 },
      );
    }
  };
```

#### Unexpected behavior

But ref.toDataURL is null

## Steps To Reproduce

1. Go to https://codesandbox.io/s/react-native-svg-test-wlfex
2. See the console.log as I have the following changes

```
<Svg
  xmlns="http://www.w3.org/2000/svg"
  width="275"
  height="200"
  viewBox="0 0 275 200"
  ref={ref => {
    console.log(ref.toDataURL);
    console.log(ref);
  }}
>
```

Describe what you expected to happen:

I can use ref.toDataURL

**Comment by wood1986** [comment]
It seems `WebShape` does not have this method
See https://github.com/react-native-community/react-native-svg/blob/ffa2e69c17ce02b21f393a5b57cdbef1c039fe3d/src/ReactNativeSVG.web.ts

**Comment by wood1986** [comment]
Dont close

**Comment by wood1986** [comment]
@msand Any updates?

**Comment by wood1986** [comment]
Don't close it

**Comment by chrispader** [comment]
Experiencing the same problem. Seems, `toDataURL` is available on native but not on web right now

**Comment by chrispader** [comment]
@WoLewicki are there plans to add this functionality to the library? I can help with implementation if needed, but it seems [this PR](https://github.com/software-mansion/react-native-svg/pull/1361) is a good start already

**Comment by willhalling** [comment]
I am hoping this will be available on the web too.

**Comment by WoLewicki** [comment]
Closing since #2072 has been merged :rocket:
