### ISSUE TITLE
Injecting images in a SVG

### ISSUE THREAD

**Issue by lucastonon** [software-mansion/react-native-svg#1360]
Hi everyone, I wanted to have a svg with a frame and then place a user photo inside of it.
Is it something I could do with react-native-svg?

I am currently exporting the .svg from Illustrator and importing it as

`import Frame from 'assets/svg/frame.svg'`

Thanks

**Comment by bohdanprog** [comment]
Hello @lucastonon,
If you still have the issue, feel free to reopen it.
Thank you
