### ISSUE TITLE
viewBox with a comma is invalid

### ISSUE THREAD

**Issue by wojtekxm** [software-mansion/react-native-svg#1363]
# Bug

If viewBox elements are separated by a comma (instead of space), I get a warning
```
Invalid `viewBox` prop:0,0,1000,1000`
```
and SVG is rendered incorrectly.

According to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox

> The numbers separated by whitespace and/**or a comma**

#### Unexpected behavior

When `viewBox="0 0 1000 1000"` everything looks fine:
<img width="200" alt="Zrzut ekranu 2020-04-29 o 17 57 25" src="https://user-images.githubusercontent.com/23526083/80617854-e6084e00-8a42-11ea-98cf-2e9a0324d273.png">

However when I set `viewBox="0,0,1000,1000"` this it the outcome:
<img width="202" alt="Zrzut ekranu 2020-04-29 o 17 58 18" src="https://user-images.githubusercontent.com/23526083/80617971-06d0a380-8a43-11ea-8335-45345c130be3.png">

# Repro

https://snack.expo.io/E_SGVE7CT

```
import React from 'react';
import {StyleSheet, View} from 'react-native';

import {SvgXml} from 'react-native-svg';

const xmlWithSpaces = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000">
<path d="M500,30l120,360h380l-300,220l110,360l-310-210l-310,210l110-360l-300-220h380z"
fill="#FF0" stroke="#FC0" stroke-width="20"/>
</svg>`;

const xmlWithCommas = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0,0,1000,1000">
<path d="M500,30l120,360h380l-300,220l110,360l-310-210l-310,210l110-360l-300-220h380z"
fill="#FF0" stroke="#FC0" stroke-width="20"/>
</svg>`;

const App = () => {
  return (
    <View style={styles.container}>
      <SvgXml xml={
        xmlWithCommas // check xmlWithSpaces
        } width={300} height={300} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 100,
    alignItems: 'center',
  },
});

export default App;
```

# Environment info

"react": "16.11.0",
"react-native": "0.62.2",
"react-native-svg": "^12.1.0"

Tested on both Android and iOS

Related issue: #1238

**Comment by ethanyuwang** [comment]
did you find a solution for this?

**Comment by HSalaila** [comment]
I've created a #1555 with a diff. in short,

```diff
diff --git a/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts b/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
index c4515b5..8053617 100644
--- a/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
+++ b/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
@@ -38,7 +38,7 @@ export default function extractViewBox(props: {
 
   const params = (Array.isArray(viewBox)
     ? viewBox
-    : viewBox.trim().split(spacesRegExp)
+    : viewBox.trim().replace(/,/g, '').split(spacesRegExp)
   ).map(Number);
 
   if (params.length !== 4 || params.some(isNaN)) {
```
