### ISSUE TITLE
Svg onPress not firing, Android Svg using Absolute Position overlay

### ISSUE THREAD

**Issue by dl-husky73** [software-mansion/react-native-svg#1367]
On Android, I am using an SVG image with absolute positioning and then placing 6 other svg images over it.  I am trying to make the 6 svg images which overlay each have a seperate onPress event.   But nothing is firing.  

I tried <SvgName onPress, then TouchableOpacity.  Tried both around the svg and then on the image.  I can't get anything to fire.  Any help would be appreciated.  Seems fairly straightforward.  

# Bug
Nothing happens, testing with a console.log.  Everything I read, should work.  I copied the two images and the main svg with one image that overlays.  Anythoughts?

          <View style={styles.jhomeAbsolute}>
            <Svg height="325" width="325" viewBox="0 0 325 325" onPress={() => console.log('Spots2 Pressed - 222')}>
              <SVG_Circle x='0' y='0' width={"100%"} height={"100%"} viewBox="0 0 975 975" />
            </Svg>
            <Svg style={[styles.jhomeIcon3]} width='70' height='77' viewBox={'0 0 70 77'}>
              <SVG_Favs1 x='0' y='0' width={70} height={77} viewBox="0 0 131 178"
                onPress={() => console.log('Spots3 Pressed - 333')} />
            </Svg>
          </View>

          const styles = StyleSheet.create({
  jhomeAbsolute: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
    backgroundColor: "#F4F3DF",
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 10,
  },
  jhomeIcon3: {
    position: 'absolute',
    top: 190,
    right: 50,
  }

## Environment info
RN-SVG:  12.1.0

System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.46 GB / 15.80 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Python: 3.7.7
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^16.13.1 => 16.13.1
    react-native: ^0.62.0 => 0.62.0

**Comment by clayton-herbst** [comment]
I have experienced frustratingly a very similar issue. The `<Svg>` component is wrapped by a `<View>` container with absolute positioning while other components overlay the _view_ listening for user interaction events. 

On _ios_ user touch events remained seamless however all interactivity went out the window on _android_. I would appreciate this issue being investigated further.

**Comment by thame** [comment]
When some of the solutions described here or modifying zIndex are not feasible for some reason, I've managed to get iOS and Android to share the same SVG interactivity by setting `pointerEvents={'box-none'}` on the positioned parent element. 

There's more information in the [React-Native](https://reactnative.dev/docs/view#pointerevents) Docs. This value seems to only be accepted on Android so you may have to selectively apply it to avoid an error on iOS (for example: `pointerEvents={Platform.OS === 'android' ? 'box-none' : 'auto'}`).

**Comment by WoLewicki** [comment]
I believe this issue has been fixed here: https://github.com/software-mansion/react-native-svg/pull/1808. You should be able to use it in the newest version of the library. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
