### ISSUE TITLE
cannot find symbol class NonNull

### ISSUE THREAD

**Issue by dunkl1lm** [software-mansion/react-native-svg#1373]
# Question
When attempting to run build on Android, get the error `cannot find symbol class NonNull`.

```
    "react-native": "0.59.10",
    "react-native-svg": "^12.1.0"
```

Works fine on ios.  Verified that all linking instructions have been followed.  Any ideas?

**Comment by BhuttoZen** [comment]
I am having same issue, did you find any solution?

**Comment by WoLewicki** [comment]
I believe this issue could have been a result of not having `androidx` available in the project or something similar, so I think it is not an issue now. I will close it then. Feel free to comment here if something is wrong and we can always reopen it then.
