### ISSUE TITLE
Text/TSpan setNativeProps doesn't work with x or y

### ISSUE THREAD

**Issue by Taylor123** [software-mansion/react-native-svg#1376]
# Bug

#### Unexpected behavior
I've tried using `setNativeProps` on both `Text` and `TSpan` to update the positioning of the text, but when setting `x` or `y` using `setNativeProps` the text disappears. Similar behavior happens when updating `children` of `Text` with a string, but a workaround for that is to and and update the children of `TSpan`

## Environment info

Library version: 12.1.0

## Short, Self Contained, Correct (Compilable), Example

Here's a snack to reproduce https://snack.expo.io/@taylor123/rnsvg-text-setnativeprops

**Comment by bohdanprog** [comment]
Hello, it seems like you attempted to change the x and y values, and as a result, it moved your component out of the viewBox. A better approach for moving elements is to use `useState`, `react-native Animated`, or `react-native-reanimated`. Just as a heads up, in fabric architecture, using setNativeProps can cause components to rerender. You can find more information about this in [this thread](https://github.com/facebook/react-native/issues/34391).

I'm closed the issue, but if you have any other questions feel free to ask.
Thank you.
