### ISSUE TITLE
Usage with Image and blurRadius

### ISSUE THREAD

**Issue by pke** [software-mansion/react-native-svg#1382]
RN `<Image/>` has a nice `blurRadius` property to make any image blurry. 
Does this SVG lib support the native Image (to provide its content) and therefor allow the usage of the `blurRadius" prop?

**Comment by bohdanprog** [comment]
Hello @pke,

While working on the react-native-svg libraries, we focused on [SVG](https://developer.mozilla.org/en-US/docs/Glossary/SVG) documentation. 
Here is a link to the SVG image tag: [SVG ImageElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGImageElement). Unfortunately, we don't have plans for that specific feature. However, I'm excited to share that we will soon release a new Filters feature. This will include a new filter - [feGaussianBlur](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur) - to help you achieve your goals.

I closed the issue. Feel free to open a new issue if you find some problems.

Thank you for your support and patience.
