### ISSUE TITLE
Svg component setNativeProps method doesn't accept viewBox prop

### ISSUE THREAD

**Issue by nicemanis** [software-mansion/react-native-svg#1383]
Here is the source code of the `Svg.setNativeProps` method:
```
  setNativeProps = (
    props: Object & {
      width?: NumberProp;
      height?: NumberProp;
      bbWidth?: NumberProp;
      bbHeight?: NumberProp;
    },
  ) => {
    const { width, height } = props;
    if (width) {
      props.bbWidth = width;
    }
    if (height) {
      props.bbHeight = height;
    }
    const { root } = this;
    root && root.setNativeProps(props);
  };
```

I'd like to animate panning and zooming with viewBox, however, it's currently not possible.

**Comment by pmunin** [comment]
Any updates from the team of contributors about this?

**Comment by philippeapril** [comment]
@nicemanis I know you posted this a long time ago but I needed to do the same thing and found out that the viewBox properties are calculated differently before inserting the native view.

The properties you want to modify with setNativeProps to manipulate the viewBox props exposed in React Native are: minx, miny, vbWidth, vbHeight.

See Svg.tsx (render function) and extractViewBox in src/lib/extract/extractViewBox.ts

**Comment by WoLewicki** [comment]
Yeah, as @philippeapril mentioned, you can copy the implementation of this method and use it to properly pass all the props you need. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
