### ISSUE TITLE
Adjust font size text, depends container width

### ISSUE THREAD

**Issue by albertcito** [software-mansion/react-native-svg#1384]
I tried to write the code shared in the issue [907](https://github.com/react-native-community/react-native-svg/issues/907#issuecomment-456497843) with hooks and TS. But I'm getting this error in the tag `<Text>` and `<Svg>`

> **Unknown event handler property onLayout**

I need to change the font size to adjust it to the size of the container.

You can see the code, small text works, but if it's big it doesn't  works: https://snack.expo.io/@albertcito/svg-text-adjust-text

May you help me please, how can I do it?

**Comment by WoLewicki** [comment]
I tested it on the newest version of the library and the `this code is never executed` text is visible, so the `onLayout` method is called properly. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
