### ISSUE TITLE
How to use this with Expo

### ISSUE THREAD

**Issue by Makio64** [software-mansion/react-native-svg#1387]
# I'm trying to add it to my expo project but can't make it work

Hi, I try different syntax with the SvgXML or directly but I got error each time and its really not clear which one I should follow, here my different attempts : 

In my babel.config.js 
```
    "plugins": [
      ["babel-plugin-inline-import", {
        "extensions": [
          ".svg"
        ]
      }]
    ]
```
in files
```
import EmptyBox from '../../assets/img/Union.svg';
//..
<EmptyBox width="20" height="20"/> 
```
errors : 
```
Failed to execute 'createElement' on 'Document': The tag name provided ('<svg width="22" height="20" viewBox="0 0 22 20" fill="none" xmlns="http://www.w3.org/2000/svg">
//....................... 
</svg>
') is not a valid name.
```

================================= 
```
import EmptyBox from '../../assets/img/Union.svg';
import { SvgXml } from 'react-native-svg'
//...
            <SvgXml
                width="20"
                height="20"
                xml={EmptyBox}
            /> 
```

Errors cause it can't read the SvgXml ( undefined on import )
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
` 

I thought it was gonna be easy to integrate but I got really confused by the getting started I guess?

=================================
also try to added in metro.config.js

```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
```
and in my app.json
```
    "packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": [
        "expo.ts",
        "expo.tsx",
        "expo.js",
        "expo.jsx",
        "ts",
        "tsx",
        "js",
        "jsx",
        "json",
        "wasm",
        "svg"
      ]
    }
``` 
but it doesn't help.

**Comment by adrenaline681** [comment]
```
import SvgUri from 'react-native-svg-uri'
<SvgUri width='300' height='200' source={require('../assets/example.svg')}/>
```

**Comment by joshuarize** [comment]
@adrenaline681 that hasn't been updated in years and there is even an article about the issue with this library: https://levelup.gitconnected.com/how-to-use-svgs-in-react-native-with-expo-ec34f085f5e0

@Makio64 did you manage to get this working somehow? i am also looking for an elegant solution similar to just importing SVGs

**Comment by WoLewicki** [comment]
This problem with Expo should have been already resolved. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
