### ISSUE TITLE
Invariant Violation using react-native-svg

### ISSUE THREAD

**Issue by CharlesTouret** [software-mansion/react-native-svg#1390]
Hello everyOne !
I have the following error when I try to use react-native-svg

![99439666_273159640758585_2928903125886566400_n](https://user-images.githubusercontent.com/56559850/83200944-baad7780-a144-11ea-93be-c4b86670a13b.jpg)

I use react-native-svg like this in my code : 
![Screenshot from 2020-05-29 00-39-41](https://user-images.githubusercontent.com/56559850/83201022-edf00680-a144-11ea-859b-46674e0d65ac.png)

and I call the component like this 
import BarChart from './BarChart'
...
 <BarChart/>

I am using react-native-svg : 9.13.3 and expo : 36
I installed react-native-svg with expo install react-native-svg and I already try to relaunch with reset cache.....
save me please lol
have a nice day !

**Comment by rmartinez-paack** [comment]
Hi, I do have the same error, but in my case I'm importing the xml source file to use `SvgXml` component.

**Comment by bjornarhagen** [comment]
Check out this page: https://docs.expo.io/versions/latest/sdk/svg/

I was able to get it working by making a component like this:

```tsx
import * as React from 'react';
import Svg, { Circle, Rect } from 'react-native-svg';

export default function SvgComponent(props) {
  return (
    <Svg height="50%" width="50%" viewBox="0 0 100 100" {...props}>
      <Circle cx="50" cy="50" r="45" stroke="blue" strokeWidth="2.5" fill="green" />
      <Rect x="15" y="15" width="70" height="70" stroke="red" strokeWidth="2" fill="yellow" />
    </Svg>
  );
}

```

**Comment by WoLewicki** [comment]
I believe this problem with expo has already been resolved, so I will close this issue. Feel free to comment here if something is wrong and we can always reopen it then.
