### ISSUE TITLE
Can't implement setState

### ISSUE THREAD

**Issue by PradyMagal** [software-mansion/react-native-svg#1395]
# Question

Hi Guys, I have this function:
```
async function search() {
     try {
    const response = await places.nearbysearch({
      location: text, // LatLon delimited by ,
      radius: distance,  // Radius cannot be used if rankBy set to DISTANCE
      type: ['cafe','bakery','meal_delivery','meal_takeaway','restaurant'], // Undefined type will return all types
      // rankby: "distance" // See google docs for different possible values
    });

    const { status, results, next_page_token, html_attributions } = response;

    var index = Math.floor(Math.random() * response.results.length);
    console.log(response.results[index].name);
  
    restName = response.results[index].name;
    console.log(restName);
  
  } catch (error) {
    console.log(error);
  }


 }
```

it is within `export default function App() {}`

I have made a text compenent within view like this:
```
return (
    <View style={styles.container}>

    <View style={{minWidth: '100%', minHeight: '100%', backgroundColor: '#f0fbff', alignFit:'stretch', marginTop: 0, alignItems:'center', justifyContent:'space-evenly'}}>
    <Card style={{padding: 5, margin: 1}}>
      <Text style={{ fontWeight: 'bold', fontSize: 25,  }}>{restName}{"\n"}</Text>

```
even though restName updates( I made a button that runs the search() function on press), the text does not update, how would I implement set state with this or refresh the variabel.

**In short, the actual variable changes but it doesn't display anything differently**

**Comment by WoLewicki** [comment]
I believe it is not an issue of the library itself and probably some issue with your code. It would be for sure easier if you made a small reproduction of the issue in a form of e.g. snack. I do not see any `react-native-svg` components here also. Would you be able to provide such reproduction?
