### ISSUE TITLE
Inkscape export troubles

### ISSUE THREAD

**Issue by KVinS** [software-mansion/react-native-svg#1402]
Hello! This library provides great opportunities, but I have two problems with my editor:

- By default, Inkscape does not indicate black. Assuming that if the color is not specified, then it is "black" (stroke / fill)

The library draws nothing if the line color is not specified.

- The editor saves some colors as a gradient. (Although there is no gradient there)

The library draws such lines in black.

Maybe there is some kind of setting for export? Like... "do not use gradients", "always indicate color".

**Comment by patriksletmo** [comment]
@KVinS Not sure if you're still experiencing issues here, but I'm posting anyway for future reference. You can specify default colors in the SVG root element which will be applied to every element without an explicitly set fill or stroke. If you import your SVG file as a React element you can do it like this:
```jsx
import MyVector from "./MyVector.svg";

const MyComponent = () => {
  return <MyVector fill="#000000" stroke="#000000" />;
};

**Comment by WoLewicki** [comment]
As for the problem with `fill`, the discussion and a fix is provided here: https://github.com/software-mansion/react-native-svg/issues/1543. As for the problem with colors as gradients, could you provide a repro of this so we could elaborate more?

**Comment by bohdanprog** [comment]
Hello @KVinS  @patriksletmo,
Could you share an example of how we can reproduce?
Thank you
