### ISSUE TITLE
iOS Crash

### ISSUE THREAD

**Issue by ajengrf** [software-mansion/react-native-svg#1403]
I'm trying to use SVG on my screen but my iOS app just closes immediately. Everything working fine on android, but I don't know why it won't run on iOS.

This is my code: 
`import Logo from './logo.svg`

then I use it:
`<Logo />`

Please help me because there's no error message on the console.

**Comment by hassankhan** [comment]
Did you set up your `metro.config.js` as per the [instructions](https://github.com/react-native-community/react-native-svg#use-with-svg-files)?

**Comment by daviddelusenet** [comment]
I'm experiencing the same issue but only with certain SVG's. This is my `metro.config.js`:

```
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
    const {
        resolver: { sourceExts, assetExts },
    } = await getDefaultConfig();

    return {
        transformer: {
            babelTransformerPath: require.resolve('react-native-svg-transformer'),
            getTransformOptions: async () => ({
                transform: {
                    experimentalImportSupport: false,
                    inlineRequires: false,
                },
            }),
        },
        resolver: {
            assetExts: assetExts.filter(ext => ext !== 'svg'),
            sourceExts: [...sourceExts, 'svg'],
        },
    };
})();
```

My code:

```tsx
import AppleMusicBadge from './apple-music-badge.svg';
import ItunesBadge from './itunes-badge.svg';

return (
    <AppleMusicBadge height={40} width={120} />
    <ItunesBadge height={40} width={120} />
);
```

The `ItunesBadge` does render but when I try to render `AppleMusicBadge` badge it crashes my app.

Also, while the `ItunesBadge` does render it doesn't look the same as the actual SVG:

<img width="619" alt="Screenshot 2020-06-30 at 09 11 59" src="https://user-images.githubusercontent.com/1398418/86095134-c5e02400-bab1-11ea-9ca6-e21071577308.png">

When I open this SVG in the browser it looks like this:

<img width="145" alt="Screenshot 2020-06-30 at 09 14 06" src="https://user-images.githubusercontent.com/1398418/86095407-27a08e00-bab2-11ea-986e-1b5d308dc85a.png">

I downloaded the badges here:
- [Apple Music Badge](https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#listen-on-apple-music-badge)
- [iTunes badge](https://www.apple.com/itunes/marketing-on-music/identity-guidelines.html#listen-on-apple-music-badge)

**Comment by Maxfurry** [comment]
> > I'm trying to use SVG on my screen but my iOS app just closes immediately. Everything working fine on android, but I don't know why it won't run on iOS.
> > This is my code:
> > `import Logo from './logo.svg`
> > then I use it:
> > `<Logo />`
> > Please help me because there's no error message on the console.
> 
> I had the same issue. These actions helped me in my case:
> 
> * change Flipper version in podfile: versions['Flipper'] ||= '~> 0.37.0'
> * cd ios && pod install --repo-update

Updating the Flipper to version 0.37.0 as stated solved fix it for me. Thanks.

**Comment by jbromberg** [comment]
I am having this issue. App crashes on launch after using svg files and updating metro config. Works fine in debug, only crashes in production.
