### ISSUE TITLE
Custom font doesn't work with Text

### ISSUE THREAD

**Issue by alexeymolchan** [software-mansion/react-native-svg#1422]
Font loaded with expo-font, it works fine with default text component, but doesn't work with svg Text.

reproducible example: https://snack.expo.io/@meme_police/restless-chocolate

![image](https://user-images.githubusercontent.com/22521355/88037332-6a073900-cb4d-11ea-9f0e-cb98b53a2acb.png)

react-native-svg: 12.1.0

**Comment by Van-Nostrand** [comment]
I've just run into this issue. Custom fonts work just fine with react native Text components, but they do not work on svg Text components. Seems this has been an ongoing issue for a few years now?

**Comment by michaelnagy** [comment]
Same problem here

**Comment by oli414** [comment]
Running into the same issue, has anyone found a solution? Seems like this has been an ongoing issue for years now, but no luck finding a solution/work-around

**Comment by FrSenpai** [comment]
Hey! Same here, I can't use custom font on Text from Svg. (expo)

**Comment by oli414** [comment]
We ended up finding that you cannot use the font-weight property, without it it was fine. May be the case for other text decoration properties too

**Comment by bohdanprog** [comment]
Hello @alexeymolchan,
Sorry for the delayed response regarding that issue.
I tried to reproduce it but couldn't.
Here is an [example](https://github.com/bohdanprog/rnsvg-custom-font).
Let me know if you are still experiencing the issue related to that problem. Thank you.

**Comment by deemaagog** [comment]
I can confirm, it works with Expo 52 and rnsvg 15.8.0
