### ISSUE TITLE
Android freezes while loading big svg files

### ISSUE THREAD

**Issue by islotwin** [software-mansion/react-native-svg#1423]
In my app, I have to show remote svgs that are downloaded from the server. They can be quite complicated (i.e. have 4000 elements/tags). 
Especially during loading svgs, Android app freezes and stops responding. After they're loaded, performance improves, however frame rate is lower than before. In real application user can feel worse performance, during animations/gestures like toggling drawer menu.
On iPhone app runs smoothly.

Do you have any suggestions about what can I do to improve performance on Android?
I've prepared expo snack to show the minimal reproduction of my problem - https://snack.expo.io/@islotwin/frisky-toffee.

**Comment by minafa96** [comment]
@islotwin did you find a solution??

**Comment by angadp** [comment]
Same problem. Any solution?

**Comment by minafa96** [comment]
@angadp I ended up using `react-native-remote-svg` instead of this package

**Comment by bohdanprog** [comment]
Hello @islotwin,
We can't reproduce that issue, if you still have that problem feel free to reopen issue 👍
