### ISSUE TITLE
Animate tag

### ISSUE THREAD

**Issue by linxu** [software-mansion/react-native-svg#1433]
Does Supported elements lack Animate tag?

**Comment by vomchik** [comment]
No, but you can use `react-native-reanimeted` library or Animated component for react-native for animation

**Comment by WoLewicki** [comment]
I believe it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1019 so I will close it to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.
