### ISSUE TITLE
TouchEvent issue on android for adjacent SVG paths 

### ISSUE THREAD

**Issue by ideveloperaz** [software-mansion/react-native-svg#1440]
# Bug

This is only for android! (For iOS it works like expected)

If for example we have two NONE overlapping but adjacent SVG paths (in different SVG components) but with overlapping rectangles of their circumscribed bounds (paths DO NOT overlapp) then touch event only works for last SVG or for not intersected circumscribed bounds ... or if you put zIndex higher for first SVG then touch will work for that image.... for iOS it works like expected and all none overlapping paths touchable (regardless their rectangle circumscribed bounds and zIndexes)

**Comment by Abisco** [comment]
I think I'm having this exact issue. I have an SVG of a car, detailing many of the parts of the vehicle (Each in its own path or line).  On iOS, each part is easily selectable, on android, some of the parts are unselectable (or require selecting on the line itself). Not sure what's going on with it!

**Comment by ideveloperaz** [comment]
Hello! Something will respond here?

**Comment by ideveloperaz** [comment]
@alloy  @kant  @yangyi ? could someone help to fix Android issue with clicking svg paths?

**Comment by alloy** [comment]
I don’t have Android experience.

It seems like you will have to debug/fix this yourself (and please do send a PR when you do).

**Comment by ideveloperaz** [comment]
@alloy  I;m not android developer but could fix it ..though having issue:

.../react-native-svg-develop/android/src/main/java/com/horcrux/svg/LineView.java:17: error: cannot find symbol
import com.facebook.react.bridge.Dynamic;
                                ^
  symbol:   class Dynamic
  location: package com.facebook.react.bridge

**Comment by ngima** [comment]
Any updates on this issue?

**Comment by bohdanprog** [comment]
Hello @ideveloperaz @ngima,
If the issue is still relevant, please provide an example to reproduce the problem.
Thank you.
