### ISSUE TITLE
Using ClipPath to create a custom shape and put an expo icon inside it.

### ISSUE THREAD

**Issue by ErezVictor** [software-mansion/react-native-svg#1446]
Hi, 

I'm trying to make a shape of a triangle with rounded corners and place in it a 'plus' sign with a yellow background.
![image](https://user-images.githubusercontent.com/18466814/92224805-004bb000-eeab-11ea-8c95-d3e17c2087f8.png)

I'm using a clip path to create the desired shape but I was wondering if I can show inside an expo icon like for example
<Entypo name="plus" size={24} color="black" /> with a yellow background.

The clipPath: 
`<Svg {...rest} width={width} height={height}>
      <Defs>
        <ClipPath id='clip'>
          <Path
            d='M 6.7 1.14
            l 2.8 4.7
            s 1.3 3 -1.82 3.22
            l -5.4 0
            s -3.28 -.14 -1.74 -3.26
            l 2.76 -4.7
            s 1.7 -2.3 3.4 0
            z'
            scale={5}
          />
        </ClipPath>
      </Defs>
   <Icon>???
    </Svg>`

I've tried a lot of ways but did not manage to do it.
Any ideas?

Thanks,
Erez

**Comment by bohdanprog** [comment]
Hello @ErezVictor,
Can you provide a simple example to repro that issue?
Thank you
