### ISSUE TITLE
Rendering noize in wrong place instead svg

### ISSUE THREAD

**Issue by Bardiamist** [software-mansion/react-native-svg#1453]
Hello, maybe anybody faced with some problem or can suggest something?

I use
```
import {
  Svg,
  Line,
  Polyline,
  Rect,
  LinearGradient,
  Stop,
  Polygon,
} from 'react-native-svg';
```
for render candle chart. And that works good. But recently on customer device (Xiaomi Mi 9; Android 10) appeared bug which I can't reproduce on my device or Android 10 emulator. 

<details>
  <summary>That renders some noize in wrong place instead svg</summary>
<img width="594" alt="Screenshot 2020-09-15 at 15 32 28" src="https://user-images.githubusercontent.com/22082342/93186464-ddea4a00-f768-11ea-98e6-5a2e2b32ef02.png">
</details>

<details>
  <summary>How it should look properly</summary>

![Screenshot_1600158900](https://user-images.githubusercontent.com/22082342/93186684-19851400-f769-11ea-849b-4f90c99a5b07.png)

</details>

react-native: 0.63.2
react-native-svg: 12.1.0

What can be?

**Comment by octobus55** [comment]
Is there any update or information regarding this bug. We have customer who has a really similar problem with svg rendering. The device and android version is the same in the original bug ticket.

Device: Xiaomi Mi 9t
Android: 10 
MIUI Version: Miui Global 12.0.5.

**Comment by bohdanprog** [comment]
Hello @octobus55,
Can you provide code to reproduce that issue, please

Thank you

**Comment by octobus55** [comment]
The problem turned out to be our user was using a dark mode and it was behaving problematically compare the other android version dark modes
@bohdanprog

**Comment by bohdanprog** [comment]
We closed that issue, but if you still have that issue, feel free to open a new issue.
Thank you.
