### ISSUE TITLE
Is there a way to get swiped over element? 

### ISSUE THREAD

**Issue by kamil-sobczyk** [software-mansion/react-native-svg#1455]
Simplified code: 

const onPointSwipe = (i: number) => {
    console.log("i", i);
  };

> <Svg width="100%" height="100%">
              <Rect
                x={0}
                y={0}
                width="50%"
                height="50%"
                fill="white"
                strokeWidth="3"
                stroke="black"
                onPressIn={() => onPointSwipe(0)}
                onPress={() => console.log("press")}
                onPressOut={() => console.log("press out")}
                delayPressIn={2}
              />
              <Rect
                x={"50%"}
                y={0}
                width="50%"
                height="50%"
                fill="white"
                strokeWidth="3"
                stroke="black"
                onPressIn={() => onPointSwipe(1)}
                onPress={() => console.log("press")}
                onPressOut={() => console.log("press out")}
              />
              <Rect
                x={0}
                y={"50%"}
                width="50%"
                height="50%"
                fill="white"
                strokeWidth="3"
                stroke="black"
                onPressIn={() => onPointSwipe(2)}
                onPress={() => console.log("press")}
                onPressOut={() => console.log("press out")}
              />
              <Rect
                x={"50%"}
                y={"50%"}
                width="50%"
                height="50%"
                fill="white"
                strokeWidth="3"
                stroke="black"
                onPressIn={() => onPointSwipe(3)}
                onPress={() => console.log("press")}
                onPressOut={() => console.log("press out")}
              />

            </Svg>

This is the square container SVG with 4 smaller squares inside. I need indicate which small square is swiped over and color it for example. 
Now onPressIn works only ones and is not triggered when swipe on another square. It is triggered again when finger is back on that one square.
Is it possible to achieve?

**Comment by Ogar616** [comment]
Any update on this?

**Comment by jakex7** [comment]
`react-native-svg` supports only basic gestures. For more advanced ones like swipe, pinch, or fling, I recommend using the `react-native-gesture-handler` library. You can find more details in its documentation: https://docs.swmansion.com/react-native-gesture-handler/

Feel free to reach out if you have any questions about integrating these two libraries. I'll try to help!
