### ISSUE TITLE
React Native Image doesn't render inside ForeignObject

### ISSUE THREAD

**Issue by St1ggy** [software-mansion/react-native-svg#1461]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug

React Native Image doesn't render in ForeignObject
![image](https://user-images.githubusercontent.com/13361661/93980031-4ad49400-fda8-11ea-87dc-75fa25118c80.png)
But if I will go to other screen and return here it renders as expected
![image](https://user-images.githubusercontent.com/13361661/93980093-60e25480-fda8-11ea-9fe7-edeaf83308d1.png)

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 11.0
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.49 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.2
  IDEs:
    Android Studio: 4.0.1 4.0.1
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
```

Library version: 12.1.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

Describe what you expected to happen:

1. Image renders as expected

declaration
```jsx
const maskDefinitions = (
  <DefinitionsBlock>
    <Mask id="NotificationMask">
      <Rect x={0} y={0} width="100%" height="100%" fill="#FFFFFF" />
      <Circle cx="100%" cy="5" r={7} fill="#000000" />
    </Mask>
  </DefinitionsBlock>
);
export const NotificationImageContainer = ({
  children,
  style,
}: {
  children: React$Node,
  style: ViewStyle,
}) => {
  const maskProps = {
    mask: 'url(#NotificationMask)',
  };

  return (
    <View>
      <Container style={style}>
        {maskDefinitions}
        <Group {...maskProps}>
          <ForeignObject y="0" x="0" width="100%" height="100%">
            <View style={{ backgroundColor: 'green' }}>{children}</View>
          </ForeignObject>
        </Group>
      </Container>
      <PriorityNotificationBadge high borderColor={colors.transparent} topOffset={-2} rightOffset={-7} />
    </View>
  );
};
```

using
```jsx
          <NotificationImageContainer
            style={styles.navBarIconContainer}
          >
            <Image source={dashboard} style={styles.navBarIcon} />
          </NotificationImageContainer>
```

Green background displays always but Image (children) does not

**Comment by St1ggy** [comment]
Yes, I could use Image component from RNSVG, but I need recolour PNG sometimes

**Comment by Benetzz** [comment]
Hi @St1ggy, do you figure how to fix? I'm having the same problem also with the RNSVG image component..

**Comment by sanpoChew** [comment]
have also just run into this, this seems to be the same issue https://github.com/react-native-svg/react-native-svg/issues/1357

**Comment by St1ggy** [comment]
> The repo [St1ggy/RNSVG-foreignobject-image-bug](https://github.com/St1ggy/RNSVG-foreignobject-image-bug) returns 404. Why did you delete the reproduction?

Because RN and RN SVG have too many changes for last three years. I would rather not keep useless dead repositories.

**Comment by jcubic** [comment]
Sure but how you can fix the issue if there is no reproduction?

**Comment by jcubic** [comment]
> The entire code you need to reproduce in my first message. As a workaround, just change key when you need to re-render.

But you lack the styles and my issue and my workaround with ForeignObject came from CSS.

**Comment by St1ggy** [comment]
> > The entire code you need to reproduce in my first message. As a workaround, just change key when you need to re-render.
> 
> 
> 
> But you lack the styles and my issue and my workaround with ForeignObject came from CSS.

So describe your solution and leave me alone.

**Comment by jcubic** [comment]
I wanted to test and comment for people that have the same issue, but it seems you don't want to help anyone including the authors of this project.

**Comment by St1ggy** [comment]
> I wanted to test and comment for people that have the same issue, but it seems you don't want to help anyone including the authors of this project.

You're just picking on me because of my nationality, racist. This issue is three years old. Everything you need to play is in the current thread.

**Comment by jcubic** [comment]
Sorry, but I have no idea where you come from.
