### ISSUE TITLE
re-rendering when using useNativeDriver causes animation to stop

### ISSUE THREAD

**Issue by rshibli** [software-mansion/react-native-svg#1467]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug

The animation of an SVG element stops when a re-rendering of the element is triggered if using useNativeDriver.  With useNativeDriver=false the animation does not stop (this is the expected behavior).

#### Unexpected behavior

If you have unexpected behavior, please create a clean project with the latest versions of react-native and react-native-svg

```bash
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..
modify App.js -> run the app
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 708.82 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 12.1.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. Please see SSCCE

Describe what you expected to happen:

1. The behavior of the re-rendered component should be the same as if useNativeDriver was off.

## Short, Self Contained, Correct (Compilable), Example

```
import React, {useState, useEffect} from 'react';
import { Text, Animated } from 'react-native';
import {Svg, G, Path, Circle} from 'react-native-svg';
import { TouchableOpacity } from 'react-native';

const AnimatedG = Animated.createAnimatedComponent(G);

export default LayoutScreen = () => {
    const interval = 1000
    const activeColor = 'rgba(0,0,0,1)'
    const disabledColor = 'rgba(128,128,128,1)'

    const [pulseAnim] = useState(new Animated.Value(0));
  
    useEffect(() => {
      Animated.loop(
        Animated.sequence([
          Animated.timing(pulseAnim, {
            toValue: 1,
            duration: interval,
            useNativeDriver: true,
          }),
          Animated.timing(pulseAnim, {
            toValue: 0,
            duration: interval,
            useNativeDriver: true,
          }),
        ]),
      ).start();
    }, [interval, pulseAnim]);
  
    const interpolatedColor = pulseAnim.interpolate({
      inputRange: [0, 1],
      outputRange: [activeColor, disabledColor],
    });
  
    [foo, setFoo] = useState(true)

    return (
        <>
            <Svg width={500} height={500} viewBox="0 -5 24 22">
                <G>
                    <AnimatedG fill={interpolatedColor}>               
                        <G>
                            <MyCircle stroke={foo? 'blue' : 'red'}/>
                        </G>
                    </AnimatedG>
                </G>
            </Svg>
            <TouchableOpacity onPress = { () => setFoo(!foo)}  >
                <Text>Toggle</Text>
            </TouchableOpacity>
        </>
    )
  }

  export const MyCircle = ( { stroke } ) => {
      return (
        <Circle cx={5} cy={0} r={5} stroke={stroke} strokeWidth={1}/>
      )
  }
```

**Comment by bohdanprog** [comment]
Hello @rshibli,
When I try to run that example without useNativeDriver, I get the warning:
`Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false``
But everything worked well.

Let me know if I can help you somehow.
Thank you.
