### ISSUE TITLE
G doesn't respond to onPress touch events

### ISSUE THREAD

**Issue by harveyconnor** [software-mansion/react-native-svg#1473]
# Bug

Whenever I nest my circles components within a `G` I cannot apply `onPress` to the `G` component props.
See my example repo here:
https://github.com/harveyconnor/TapGestureHandlerSvgBug

Ref: https://github.com/software-mansion/react-native-gesture-handler/issues/1206

#### Unexpected behavior
G is not receiving touch events.

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 473.44 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.13.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
    Python: 3.8.3 - /Users/harvey/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.0

## Steps To Reproduce

1. Clone the repo: https://github.com/harveyconnor/TapGestureHandlerSvgBug
2. `cd TapGestureHandlerSvgBug`
3. `npm install`
4. `npx pod-install`
5. `npx react-native run-android` or run in xcode for ios
6. Take a look at /App.tsx for main source code

Describe what you expected to happen:

1. The onPress event would fire when touching anything nested within the G.

**Comment by harveyconnor** [comment]
Refs https://github.com/software-mansion/react-native-gesture-handler/issues/1206

**Comment by AurangShah** [comment]
Any update?

**Comment by bohdanprog** [comment]
Hello @harveyconnor  @AurangShah,
That issue still exist?
