### ISSUE TITLE
Svg is not transparent

### ISSUE THREAD

**Issue by Ghamza-Jd** [software-mansion/react-native-svg#1474]
### Expected Result
I'm trying to make a bottom navigation tab with a notch [expected result](https://prnt.sc/uz3toi)

### Problem
I have a svg which have a transparent background [link to the original image](https://prnt.sc/uz3g9e)
I tested it on the web and here's what it look like [link to web image](https://prnt.sc/uz3j5i)
but when I use it in react native, the transparent part becomes white [link to react native image](https://prnt.sc/uz3p24)
then I've set the fill to red for a clear view of what's happening [fill="red"](https://prnt.sc/uz3psi)
The area that should be transparent is colored in white.

**Comment by vitto-moz** [comment]
The same behaviour :( @Ghamza-Jd  have you resolved? Could you share if so, please?

**Comment by vitto-moz** [comment]
I've the issue resolved with following styling:
```
  <View style={styles.footerWrap}>
        <Footer preserveAspectRatio="none" width={'100%'} />
      </View>

 footerWrap: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: '100%',
    height: 100,
  },

<svg width="459" height="134" viewBox="0 0 459 134" fill="none" xmlns="http://www.w3.org/2000/svg" > 
<path d="M0 42C176.576 -14.0595 277.09 -13.9398 459 42V134H0V42Z" fill="black"/>
</svg>

```

**Comment by Ghamza-Jd** [comment]
@vitto-moz thank you for sharing, I forgot how I solved it at that time, but I remember doing something similar to your solution (tweaking the position and dimension of the component). Also I was using (react-native-svg-transformer)[https://github.com/kristerkari/react-native-svg-transformer], to import and use svg files as components.

**Comment by WoLewicki** [comment]
Could you provide a simple code with reproduction of the issue? It will help us investigate the problem. Or is it already solved?
