### ISSUE TITLE
Solution: webpack + react-native-web + react-native-svg + monorepo

### ISSUE THREAD

**Issue by KEMBL** [software-mansion/react-native-svg#1478]
Guys, if you have a Monorepo and UI components package is reused form mobile and web version of react-native, the way suggested in the documentation might not work for you:

`import { Svg, etc... } from "react-native-svg/src/ReactNativeSVG.web";`

instead of this, you can do import in the `old way` 

`import { Svg, etc... } from 'react-native-svg';`

but add an alias into the webpack config:

... webpack.config.js ...
`  resolve: {`
`    extensions: ['.ts', '.tsx', '.js', '.web.js'],`
`    alias: {`
`      ... other aliases ...,`
`      './ReactNativeSVG': aliasPathJoin(['react-native-svg', 'lib', 'module', 'ReactNativeSVG.web.js']),`
`    }`
`  },`
`
... webpack.config.js ...

**Comment by aharris** [comment]
Using this option I am getting: 

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

using default examples for `SvgXml` and `SvgUri`

**Comment by bojanlosic** [comment]
Any solution for this? I'm using expo and getting error

**Comment by bojanlosic** [comment]
@aharris have you found solution to use `SvgUri` on web?

**Comment by joan-saum** [comment]
@bojanlosic Unfortunately, I don't find any `SvgUri` exported from ReactNativeSVG.web.ts. It is not supported in web.
It would be a great thing that `react-native-svg` can support SvgUri in web. Currently, I have to use `react-native-svg-uri`

**Comment by WoLewicki** [comment]
The problem with using `SvgXml` etc. on web is described here: https://github.com/software-mansion/react-native-svg/issues/1279. I will close this issue to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.
