### ISSUE TITLE
onPress not working on web

### ISSUE THREAD

**Issue by mehimanshupatil** [software-mansion/react-native-svg#1483]
onpress is not working for version of react-native-web 0.13.0 and above.

reproducible example
[codesandbox ](https://codesandbox.io/s/react-native-web-click-handle-not-working-sy57f?file=/src/App.js)
change react-native-web Version below 0.13.0 and it works

**Comment by codeion** [comment]
Any suggestions on how to fix/patch Warning: Unknown event handler property `onStartShouldSetResponder`.

**Comment by rsml** [comment]
@mehimanshupatil I'm using react-native-web 0.13.18 and I was able to get all of these events to work:

```
onClick
onFocus
onMouseDown
onMouseEnter
onMouseLeave
onMouseMove
onMouseOut
onMouseOver
onMouseUp
```

Specifically I used it on a <Rect> nested in a <G>

**Comment by mehimanshupatil** [comment]
Hello, @rsml 
My query is regarding onPress handler. The event you mentioned also works for me.

**Comment by SmartArray** [comment]
I second this.

We might approach it with the following mapping:

`onPress`: `onClick`
`onPressIn`: `onMouseDown`
`onPressOut`: `onMouseUp`
`onStartShouldSetResponder`: `onFocus`
`onResponderTerminationRequest`: null (does not exist)
`onResponderGrant`: null (does not exist)
`onResponderMove`: `onMouseMove`
`onResponderRelease`: `onMouseUp`
`onResponderTerminate`: `onBlur`

What are your thoughts?

I was wondering about these, because I thought react-native-web implemented those mappings already?

https://github.com/necolas/react-native-web/issues/1568

**Comment by ManAnRuck** [comment]
i have the same issue and a easy workaround until it is fixed:

`npm i --save-dev babel-plugin-rename-jsx-attribute`


.babelrc
```json
{
  "presets": ["react"],
  "plugins": [
    [
      "rename-jsx-attribute",
      {
        "attributes": {
          "onPress": "onClick"
        }
      }
    ]
  ]
}

```

**Comment by MorningK** [comment]
I solved this problem by explicitly declaring onPress and onClick methods at the same time
`<Rect
          onPress={() => onSelectRobot(id)}
          onClick={() => onSelectRobot(id)}
          key={`robot-${id}`}
          x={x}
          y={y}
          origin={`${x + width / 2}, ${y + height / 2}`}
          transform={transform}
          width={width}
          height={height}
          fill={color}
        />`

**Comment by ThePVY** [comment]
Hi, sorry for such a simple question, but how are you make onClick prop (and others web props) work on Rect, because onClick does not even exist in available props for Rect for me (there are only native events props, such as onPress, onPressIn, etc.).

**Comment by Joeao** [comment]
> Hi, sorry for such a simple question, but how are you make onClick prop (and others web props) work on Rect, because onClick does not even exist in available props for Rect for me (there are only native events props, such as onPress, onPressIn, etc.)?

`onClick` will work, but you'll get a type error.

**Comment by arthurhamon** [comment]
Hi,

I encounter the same error using an icon wrapped inside `TouchableWithoutFeedback` I managed to remove the warning replacing it with the new [react-native](https://reactnative.dev/docs/pressable) `Pressable` wrapper.


Hope it will help some of you

**Comment by kxtsn** [comment]
> i have the same issue and a easy workaround until it is fixed:
> 
> `npm i --save-dev babel-plugin-rename-jsx-attribute`
> 
> .babelrc
> 
> ```json
> {
>   "presets": ["react"],
>   "plugins": [
>     [
>       "rename-jsx-attribute",
>       {
>         "attributes": {
>           "onPress": "onClick"
>         }
>       }
>     ]
>   ]
> }
> ```


Hello, this works perfectly, however I only require the onClick on SVG related libraries. Do you know if there is anyway to specify?

**Comment by iam-yan** [comment]
> Hi, sorry for such a simple question, but how are you make onClick prop (and others web props) work on Rect, because onClick does not even exist in available props for Rect for me (there are only native events props, such as onPress, onPressIn, etc.)?

One workaround is to declare a type merging.
For example:
```
import "react-native-svg";
import { TouchableProps } from "react-native-svg";

declare module "react-native-svg" {
  interface GProps {
    onClick?: TouchableProps["onPress"];
  }
}

```

**Comment by manuelmhtr** [comment]
Is this related? https://github.com/akveo/react-native-ui-kitten/issues/1801

**Comment by oliviercperrier** [comment]
Still an issue: Warning: Unknown event handler property `onStartShouldSetResponder`. It will be ignored.

**Comment by NateDiamond** [comment]
I'm still unable to use onPress for a `react-native-svg` component on web. Here's my dependencies:
```
"react-native-svg": "^15.3.0",
"react-native-web": "~0.19.6", // Installs 0.19.10
```
and here's my code:
```
import Svg, { Circle, G } from "react-native-svg";

function X({x, y, r, onPress}) {
  return (
      <G>
        <Circle cx={x} cy={y} r={r} fill="black" onPress={() => onPress && onPress()}/>
      </G>
    );
}

function Y() {
  return (
    <Svg viewBox={`0 0 100 100`}>
        <X x={5} y={5} r={5} onPress={()=>console.log('hi')}/>
    </Svg>
  );
}
```

I'm seeing the following warning: "Unknown event handler property `onStartShouldSetResponder`. It will be ignored."

**Comment by ed-bennett-dodimead** [comment]
Has there been any update on this? I'm seeing the same issue on expo 51.

**Comment by bohdanprog** [comment]
Hello @ed-bennett-dodimead,
Can you provide an example of how we can reproduce that?
Thank you

**Comment by ed-bennett-dodimead** [comment]
So I just set up a new tamagui repo following the quick start: `npm create tamagui@latest --template expo-router`, then added an `      <Eye onPress={() => console.log("pressed")} />` component (I tried with a few different icons and saw the same thing on all of them) to the index page from the `@tamagui/lucide-icons` library and I'm seeing the same errors in the console when I start the web version. This is how we're using it in our project, but we are seeing it with *.svg files we're importing as components via react-native-svg-transformer too.

**Comment by horakjakub** [comment]
Plus one from me, I also used expo with router

**Comment by bohdanprog** [comment]
Hello @ed-bennett-dodimead  @horakjakub,
IDK why it doesn't work but I created a simple [example](https://github.com/bohdanprog/rnsvg-onPress).
Everything worked well.

**Comment by ed-bennett-dodimead** [comment]
> Hello @ed-bennett-dodimead @horakjakub, IDK why it doesn't work but I created a simple [example](https://github.com/bohdanprog/rnsvg-onPress). Everything worked well.

That's interesting, I cloned yours and I see all the same console errors, except the click handler does seem to fire properly. I'm not sure how to go about testing that further.

**Comment by bohdanprog** [comment]
@ed-bennett-dodimead 
here is the recording from my screen :)
It had some errors but, on click worked well.
Here is [PR](https://github.com/software-mansion/react-native-svg/pull/2312) with implementing handling web events.
https://github.com/user-attachments/assets/e863861a-0875-44e9-a69c-f3b5cbd9df42

**Comment by lavor** [comment]
@bohdanprog I think there will be an issue in your modification on this line:
https://github.com/software-mansion/react-native-svg/pull/2386/files#diff-3cc1377040327020cbae313a397ffdd051b0f13ccf59654f6e516b98bb853927R121

That resolves in a regression of this issue.

Your first fix was working correctly: 
https://github.com/software-mansion/react-native-svg/pull/2302/commits/ca703ff108c1c4bbbba69f4e52450f6f500eb13d#diff-8830d392c035c5b523ac5a9a48b3afbc9a4f7c1b56cce4ad36f7b41960c8042eR270

When I have changed condition back to `onPress != null` (with != operator), my event handlers start to work again.
I think there will be some issue in react-native-web when you always assign undefined to onClick handler.

**Comment by bohdanprog** [comment]
Hi @lavor,
Could you provide a simple example to reproduce that? I'll fix that

Thank you

**Comment by lavor** [comment]
@bohdanprog 
Yes, I localized the issue more specifically, when I was creating a simple example.
I've realized that I still have used onClick and not onPress in my code. But as I mentioned before, when condition in your change will be  `onPress != null`, the onClick will be working properly.

See demo in this snack:
https://snack.expo.dev/@lavor/react-native-svg-onclick

**Comment by abir701** [comment]
Hi everyone, 
I am facing the same issue regarding onPress in react-native-svg. The issue is only noticed on iOS 18 and above devices.
I have checked all the properties and found that the onPressIn method is working, but this is not appropriate for my case. I need the same behavior as onPress. So I have used this approach to solve the issue:

`react-native-svg: "15.11.2"`

```
 _getTouchProps = (item) => {
  if (this._isIOS18Plus()) {
    return {
      onResponderGrant: () => {
        this.touchStartTime = Date.now();
      },
      onResponderRelease: () => {
        const duration = Date.now() - this.touchStartTime;
        if (duration < 300) {
          this.props.onPressedThumbnail(item);
        }
      },
      onStartShouldSetResponder: () => true,
      onMoveShouldSetResponder: () => false
    };
  } else {
    return {
      onPress: (event) => {
        this.props.onPressedThumbnail(item);
      }
    };
  }
};
```
Can you explain why onPress is not working only on iOS 18 and above devices?
