### ISSUE TITLE
touch / press events on Svg only fire on regions where other elements are rendered.

### ISSUE THREAD

**Issue by boygirl** [software-mansion/react-native-svg#1488]
# Bug

Hi there, I'm the maintainer of victory / victory-native, and some folks have been struggling with an issue where events on the parent `Svg` are not picked up unless there happen to be other elements (`Path`, `Rect` etc.)  rendered in the same location. 

Here's a gif to demonstrate what I mean.  The entire Svg should be sensitive to touch events, and should trigger the tooltip on the nearest bar, but you can see it only works when the event originates directly on the bar. 
![native-voronoi-issue](https://user-images.githubusercontent.com/3719995/98736843-39e0e180-235a-11eb-933c-16f74c2e4a45.gif)

If I add a `Rect` child to my `Svg`, you can see the events on the Svg working as expected:

![correct-voronoi](https://user-images.githubusercontent.com/3719995/98737504-22eebf00-235b-11eb-9bfc-e61f7eb9787f.gif)

The demos above are using `react-native-svg@^12.1.0`

For `victory-native` users I'm adding a temporary fix of rendering a transparent `Rect` the same size as my `Svg` element so that all the events on the the parent `Svg` will be triggered as expected. https://github.com/FormidableLabs/victory-native/pull/611

**Comment by minafa96** [comment]
I have the exact opposite problem! the free space around a shape is pressable although I don't want it to be so.

**Comment by minafa96** [comment]
@boygirl  Do you have a opinion on this?

**Comment by SurajMDurgad** [comment]
This is happening with the `Path` as well, for example draw a circle using the path, you'll not be able to draw anything within the circle. But you can draw anything out side the circle.

![image](https://user-images.githubusercontent.com/13523678/148336390-92854f01-686e-4789-9c06-42dd4b27c3ee.png)

**Comment by bohdanprog** [comment]
Hello, @boygirl.
Can you provide a simple repro for that issue?
Thank you.
