### ISSUE TITLE
'No' string rendered as numero sign (No.) in react-native-svg Text element with a specific font (RyoGothicPlusN) on ios

### ISSUE THREAD

**Issue by Thaisagathem** [software-mansion/react-native-svg#1501]
The string 'No' renders as the numero sign № with the font RyoGothicPlusN-Regular on ios only. If I don't pass the font or pass something else f.e. Times New Roman, the string renders as expected.

`import { Text } from 'react-native-svg';`
`<Text x="0" y="10" dx="10" fontSize={14} fontFamily="RyoGothicPlusN-Regular">No</Text>`

Updating the package to the latest did not resolve.

**Comment by bohdanprog** [comment]
Hello @Thaisagathem,
I tried to reproduce that, but couldn't.
here is how it looks:
| IOS | Android |
|--------|--------|
|<img width="300" height="700" src="https://github.com/software-mansion/react-native-svg/assets/69891500/0aa00e39-8f11-41b6-9c4b-1d080d17557e" /> |  <img width="300" height="700" src="https://github.com/software-mansion/react-native-svg/assets/69891500/7c965b1b-5114-4150-8264-4702ab3c29f5" />| 

If you still have that issue feel free to open the new issue.
Thank you.
