### ISSUE TITLE
Does react-native-svg not support SVG inside SVG and Text nodes?

### ISSUE THREAD

**Issue by neeeeecka** [software-mansion/react-native-svg#1506]
So I am making an android app, using web preview ofc. And I encounter this problem:

Web build:
![image](https://user-images.githubusercontent.com/22796372/102244946-6322fd80-3f16-11eb-9529-d319d82a1c73.png)

Android build:
![image](https://user-images.githubusercontent.com/22796372/102245017-7930be00-3f16-11eb-92df-fa373f0119a5.png)

This is the code(getLines just returns SVG lines and SVG Texts):

![image](https://user-images.githubusercontent.com/22796372/102245081-92d20580-3f16-11eb-8fcf-0f2fcc228c0f.png)

As you can see, svg is not centered like it is on the web build, because child svg doesn't seem to do anything that it should.
Text nodes are invisible on android too, but there could be several reasons to it tho so not necessarily correlated.

**Comment by bohdanprog** [comment]
Hello @neeeeecka,
If you are still experiencing that problem, please provide a simple reproduction of the issue.
Thank you.
