### ISSUE TITLE
Avataaars svg library only shows avatars with circular type

### ISSUE THREAD

**Issue by Jcrowley17** [software-mansion/react-native-svg#1514]
I'm currently developing an app for IOS using RN and the React-native-svg library. The SVGs that I'm using are from getavataaars.com, and render when the 'avatarStyle' property is set to Circle. However, when I try to use a transparent background avatar, the entire SVG disappears and doesn't render. Can anyone help with this?

**Comment by bohdanprog** [comment]
Hello @Jcrowley17,
If the issue still persists, could you share an example and the steps to reproduce it?
Thank you.
