### ISSUE TITLE
Empty gradient prop value lead to app crash

### ISSUE THREAD

**Issue by komly** [software-mansion/react-native-svg#1515]
If you provide empty param value app will crash    ` <LinearGradient id="grad" x1="1" y1="0" x2="0" y2="">`

<img width="1328" alt="Снимок экрана 2021-01-08 в 11 30 54" src="https://user-images.githubusercontent.com/4579028/103992305-f9a8ae80-51a4-11eb-838b-3eecbc520925.png">

Maybe need additional validation

**Comment by bohdanprog** [comment]
Hello @komly,
I tried to reproduce that but couldn't. 
If the issue still persists, feel free to open a new issue.
Thank you.
