### ISSUE TITLE
Using this component in reactjs appliaction

### ISSUE THREAD

**Issue by webcluster4u** [software-mansion/react-native-svg#1516]
Hi,

I am working on reactjs application and would like to know ifnI can use this component inside my react-js application or not?

**Comment by bohdanprog** [comment]
Hello @webcluster4u,
Maybe easier will be to use SVG as Component.
here is the article with [example](https://blog.logrocket.com/how-to-use-svgs-react/).
If you still have some questions feel free to open a new issue.
Thank you.
