### ISSUE TITLE
How to set SvgCss height value with the viewbox height?

### ISSUE THREAD

**Issue by ethanyuwang** [software-mansion/react-native-svg#1517]
I have an api endpoint that returns svg charts with variable height depending on the data and I'm using SvgCss to render the returned svg string. Is there a way to extract viewbox height from the svg string to set the height of the SvgCss component so the height changes dynamically?

**Comment by bohdanprog** [comment]
Hello @ethanyuwang,
Can you provide an example of what you want to achieve, please?
Thank you.
