### ISSUE TITLE
Shape missing as exported member in `index.d.ts`

### ISSUE THREAD

**Issue by gaara4896** [software-mansion/react-native-svg#1521]
## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 860.80 MB / 31.25 GB
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
  Languages:
    Java: Not Found
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

react-native: 0.63.3,
react-native-svg: 12.1.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

```javascript
import Svg, {Shape} from 'react-native-svg';

const PreviewCanvas: React.FC = () => {
  const svgRef = useRef<Shape>(undefined);

  return (
    <Svg ref={svgRef} />
  )
}
```

```
Module '"../../../node_modules/react-native-svg/src"' has no exported member 'Shape'. ts(2614)
```

## Short, Self Contained, Correct (Compilable), Example

Include Shape as an exported member inside `src/index.d.ts` so that typescript can detect them properly.

**Comment by WoLewicki** [comment]
I believe it is no longer an issue since https://github.com/software-mansion/react-native-svg/pull/1806. I will close it then. Feel free to comment here if something is wrong and we can always reopen it then.
