### ISSUE TITLE
Touch Events not working in expo projects (where expo version >39.0.0)

### ISSUE THREAD

**Issue by yoyu777** [software-mansion/react-native-svg#1524]
I can re-produce this issue on snack.expo.io:
https://snack.expo.io/@yoyu777/react-native-svg-onpress-not-working-since-expo-v39

Same code, works for expo version v37 and v38, but not v39 and v40.

In my local project, it gives the following warnings:
```
Warning: Unknown event handler property `onStartShouldSetResponder`. It will be ignored.
Warning: Unknown event handler property `onResponderTerminationRequest`. It will be ignored.
Warning: Unknown event handler property `onResponderGrant`. It will be ignored.
Warning: Unknown event handler property `onResponderMove`. It will be ignored.
Warning: Unknown event handler property `onResponderRelease`. It will be ignored.
Warning: Unknown event handler property `onResponderTerminate`. It will be ignored.
```

**Comment by marianomms** [comment]
I would say same issue than https://github.com/react-native-svg/react-native-svg/issues/1483

**Comment by oliviercperrier** [comment]
Any plan on getting this fixed? ref: https://github.com/necolas/react-native-web/issues/1568
