### ISSUE TITLE
Svg file to variable

### ISSUE THREAD

**Issue by schmru** [software-mansion/react-native-svg#1525]
Hello, currently I am loading SVG files wit imports:
`import LogoSVG from '../../../assets/general/logo.svg';`

Now I am trying to create an image loading function that checks the source ending and recognize  if image is SVG or PNG.
For this I would need someway to create SVG in a function instead with an import and return it as a component.
Something like this:
`const LogoSVG = require("../../../assets/general/logo.svg");`

Is there a possibility?

**Comment by anoopjangra90** [comment]
try following to draw local sag files :

import { WithLocalSvg } from 'react-native-svg';

<WithLocalSvg
                    asset={require("../localAssets/ic_show_pass.svg")}
                />

**Comment by grifotv** [comment]
What is the difference between `LocalSvg` and `WithLocalSvg`? I haven't found them in the docs or type definition. #1443

**Comment by bohdanprog** [comment]
Hello @schmru,

I believe the issue has already been resolved. If you are still experiencing problems, please feel free to open a new one.
Thank you.
