### ISSUE TITLE
When load a remote SVG from url , is there a callback about svg is rendered/visible?

### ISSUE THREAD

**Issue by Xi-gofore** [software-mansion/react-native-svg#1528]
I am loading a remote SVG from a url like below:

```
import * as React from 'react';
import { SvgUri } from 'react-native-svg';

export default () => (
  <SvgUri
    width="100%"
    height="100%"
    uri="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/Steps.svg"
  />
);
```

The problem is it takes about 10 seconds to have the SVG image be visible on the screen, I think it depends on the network connection. For a better user experiences, I would like to show a loading spinner until the SVG is rendered/visible. But is there a callback for me to do that? If no, do you have any suggestion how to show a loading spinner until SVG is rendered/visible?

**Comment by bernhardoj** [comment]
I need this too

**Comment by bohdanprog** [comment]
Hello @Xi-gofore,

I believe you can manage the image loading state. You mentioned displaying a spinner until the image loads and then showing the image afterward.
If you still have any questions feel free to open an issue.
Thank you.
