### ISSUE TITLE
Cause app crash when loading remote svg

### ISSUE THREAD

**Issue by Xi-gofore** [software-mansion/react-native-svg#1529]
# Bug

I have a screen renders remote svg by using this library:

```
<View style={styles.content}>
         <SvgUri width="100%" height="100%" uri={remoteSvgUrl} />
</View>
```

Running on iPhone app crashes with following error message:

```
2021-02-10 20:15:04.668515+0200 MyApp[25668:56308417] [ServicesDaemonManager] interruptionHandler is called. -[FontServicesDaemonManager connection]_block_invoke
2021-02-10 20:15:04.673167+0200 MyApp[25668:56308415] [client] No error handler for XPC error: Connection interrupted
Message from debugger: Terminated due to memory issue
```

## Environment info
"react-native": "0.63.4",
"react-native-svg": "^12.1.0",

## Steps To Reproduce
Just run my app on iPhone 11 Pro , iOS 13.6

**Comment by MohdSaleh** [comment]
any updates on this??

**Comment by EvanKoe** [comment]
Same problem (react-native 0.70.6, Pixel 4 emulator (android 12), react-native-svg 13.6.0). Any updates ?

**Comment by bohdanprog** [comment]
Hello @Xi-gofore, @MohdSaleh  @EvanKoe,
If the issue still persists, could you share an example and the steps to reproduce it?

Thank you.
