### ISSUE TITLE
Usage in React Web app

### ISSUE THREAD

**Issue by coderbintech** [software-mansion/react-native-svg#1530]
Kindly suggest how i can use it in React Web app?

Thanks

**Comment by Sharcoux** [comment]
If you mean React-Native-Web, you can try [this](https://github.com/cantoo-scribe/rn-svg)
This is our fork to provide SvgXml and SvgCss for web.

**Comment by nchase** [comment]
@coderbintech See the documentation updates I added in #1625 –  it's possible that you'll just need to update your bundler to resolve `.web.js` files.

**Comment by WoLewicki** [comment]
I think the needed information has been provided in the previous comments. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
