### ISSUE TITLE
Circle of index.d.ts missing ref

### ISSUE THREAD

**Issue by ericbaobao** [software-mansion/react-native-svg#1531]
**I am aware of this but this is not my own code, this came from screenshot of the component source code**
![alpha](https://user-images.githubusercontent.com/78641493/107637252-cc21ba00-6ca8-11eb-8209-a410f6a8a779.png)

# Bug

This is just a tiny issue, the ref is missing as shown in picture above. It is needed to perform animation, example 

#### Unexpected behavior

none, it still work when using ref

```bash
<Circle
            ref={CIRCLE_REF}
            cx="50%"
            cy="50%"
            ...
/>
```

yes, it's still an issue with the latest versions,
https://snack.expo.io/ can't show the suggestion error can it?

## Environment info

every component of my project is using latest sdk.

Describe what you expected to happen:

1. The warning shown by vscode is annoying, and without intellisense suggestion people may not know it's supported.
2. Other component which support ref should add it

**Comment by WoLewicki** [comment]
I believe it is no longer an issue since https://github.com/software-mansion/react-native-svg/pull/1806. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
