### ISSUE TITLE
Animated values do not work in transform property

### ISSUE THREAD

**Issue by matthiasferch** [software-mansion/react-native-svg#1532]
> react 16.13.1
> react-native 0.63.3
> react-native-svg 12.1.0

I have noticed that a G's transform does not work with animated values on Android (I can't test it on Mac, unfortunately).

In the following example app, the first circle will be twice as big as the second one, even though they both should be the same size:

```
import React from 'react';

import { Animated, View, StyleSheet } from 'react-native';

import Svg, { G, Circle } from 'react-native-svg';

const AnimatedG = Animated.createAnimatedComponent(G);

export default function App() {
  const scale = 2.0;
  const animatedScale = new Animated.Value(2.0);

  return (
    <View style={styles.container}>
      <Svg>
        <AnimatedG transform={{ scale: scale }}>
          <Circle cx={50} cy={50} r={20} fill={'red'}></Circle>
        </AnimatedG>
        <AnimatedG transform={{ scale: animatedScale }}>
          <Circle cx={50} cy={50} r={20} fill={'blue'}></Circle>
        </AnimatedG>
      </Svg>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
});

```

Here's a screenshot from my phone:

![svg-bug](https://user-images.githubusercontent.com/767384/107860849-2609b780-6e42-11eb-9042-710659ffd106.jpg)

Using a CSS-like transform using the `style `attribute works but then the circle becomes blurry when scaled, so it's not a good workaround.

**Comment by wcandillon** [comment]
Reanimated seems the same issue where it seems to except a certain shape for transform. A workaround might be to create a clone of the createAnimatedComponent function where the transform prop is not treated as a special thinking like it is for View.

**Comment by bohdanprog** [comment]
Hello @matthiasferch,
As I see that issue is already solved, but if you still have some problems with that feel free to open a new issue.
Thank you.
