### ISSUE TITLE
Opening animated svg from url

### ISSUE THREAD

**Issue by schmru** [software-mansion/react-native-svg#1534]
Hello, I have been trying to open animated svg from url (sorry cant give you the url to svg since it is made for work). The svg was made by the designer and it works normal, it is animated,  when opening link. 

I am using "react-native-svg": "^12.1.0" and am opening svg this way:

`<SvgCssUri
             uri={imageURL}
             style={imageStyle}
             height={height}
             width={width}
  />`

Am I missing something or is this not supported?

**Comment by lfrkovic-spaceiq** [comment]
Did you ever get this working @schmru?

**Comment by ulisesmac** [comment]
@schmru I'm Wondering the same as @lfrkovic-spaceiq .

**Comment by thomasread99** [comment]
@schmru @lfrkovic-spaceiq @ulisesmac did any of you manage to get this working? I have some animated SVGs on a server and but when I load them using `SvgUri` I just get the static image back

**Comment by bohdanprog** [comment]
Hello @schmru, @thomasread99, @ulisesmac  @thomasread99,
Are you still experiencing that issue? Kindly provide an example and steps to reproduce it.
Thank you.

**Comment by thomasread99** [comment]
@bohdanprog yes I am still experiencing this issue. I have the animated SVGs stored on a server, and I retrieve them to the app with the following:
```react native
 <SvgUri
    uri={`${constants.images}`}
    style={styles.image}
 />

image: {
    width: wp(20),
    height: wp(20),
    marginVertical: hp(1),
},
```
where `constants.image` is the image URI. Let me know if you need any further information.

**Comment by bohdanprog** [comment]
@thomasread99, How do you animate your SVGs?  Do you have inside your SVG animate tag?

**Comment by thomasread99** [comment]
@bohdanprog the actual SVG itself is animated. I got them from an open source collection, and then added them to my own server. Here is an example of one of them. I do not have it inside an animate tag
![1000](https://github.com/software-mansion/react-native-svg/assets/37627415/7ab7af03-223e-4a5b-ad1b-5d7af9562d0c)

**Comment by bohdanprog** [comment]
@thomasread99, Unfortunately, we do not currently support that particular animation. Perhaps in the future, we may consider adding that feature, but it is currently unavailable.
