### ISSUE TITLE
"cannot read property push of null" while debug is on

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [software-mansion/react-native-svg#1536]
![Screenshot_2021-02-18-10-44-48-92](https://user-images.githubusercontent.com/32297380/108308921-9adc4900-71d6-11eb-8be9-87fedf547bd2.jpg)

**Comment by CHANDRAMOHANnegi** [comment]
this is happening only while debugging

**Comment by DEVfancybear** [comment]
how to fix it ?

**Comment by mrtcmn** [comment]
any thoughts? we have a problem at v12.1.1

**Comment by Adnan-Bacic** [comment]
i know this is an insane solution, but i got this error when it was exported like this:

`export { default as SomeName } from './someName.svg';`

but works when i exported it like this:

```
import SomeName from './someName.svg';

export {
  SomeName,
};
```

**Comment by CHANDRAMOHANnegi** [comment]
> i know this is an insane solution, but i got this error when it was exporting like this:
> 
> `export { default as SomeName } from './someName.svg';`
> 
> but works when i exported it like this:
> 
> ```
> import SomeName from './someName.svg';
> 
> export {
>   SomeName,
> };
> ```

**Comment by 12haa** [comment]
for me it was related to rendering and uri for an svg , i think the svg url was  corrupted or something.
