### ISSUE TITLE
WithLocalSvg did not override fill color property

### ISSUE THREAD

**Issue by anoopjangra90** [software-mansion/react-native-svg#1545]
# Bug

I’m using WithLocalSvg component to draw local SVG images. Its working fine to draw local svg images. but for white labelling purpose I need to override fill color property. I want to change the filled colour dynamically. 

#### Unexpected behaviour

fill colour propes does not override already filled colour.

React native info output:
  "react": "16.13.1",
  "react-native": "0.63.4",

Library version: "react-native-svg": "^12.1.0"
## Steps To Reproduce

import React, { Component } from 'react'
import { View } from 'react-native'
import { WithLocalSvg } from 'react-native-svg';
export default class LoginView extends Component {
  
    render() {
        return (
            <View style={{
                flex: 1, alignItems: "center",
                justifyContent: "center",
                backgroundColor: "#eee"
            }}>
                <WithLocalSvg
                    asset={require("../localAssets/ic_show_pass.svg")}
                    fill={"#1e1"}
                    />
            </View>
        )
    }
}

**Comment by WoLewicki** [comment]
It looks like a duplcate of https://github.com/software-mansion/react-native-svg/issues/1317 so I will close it to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.
