### ISSUE TITLE
fix: Allow ',' in viewBox attribute

### ISSUE THREAD

**Issue by HSalaila** [software-mansion/react-native-svg#1555]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@12.1.0` for the project I'm working on.

I have added a replace regex to remove comma's (,) in viewBox. According to [MDN viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox) numbers are separated by whitespace and/or a comma.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts b/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
index c4515b5..8053617 100644
--- a/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
+++ b/node_modules/react-native-svg/src/lib/extract/extractViewBox.ts
@@ -38,7 +38,7 @@ export default function extractViewBox(props: {
 
   const params = (Array.isArray(viewBox)
     ? viewBox
-    : viewBox.trim().split(spacesRegExp)
+    : viewBox.trim().replace(/,/g, '').split(spacesRegExp)
   ).map(Number);
 
   if (params.length !== 4 || params.some(isNaN)) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Let me know if I you want me to create a pull request or not.

**Comment by gp3gp3gp3** [comment]
This patch does not account for numbers that are separated by commas but not whitespace(for example: `0, 0, 400,69.83316168898044`), updating it to the following will address that issue.

```
viewBox.trim().replace(/,/g, ' ').replace(/  +/g, ' ').split(spacesRegExp)
```
