### ISSUE TITLE
How can I access the props of a svg component?

### ISSUE THREAD

**Issue by namti** [software-mansion/react-native-svg#1562]
I am using <SvgCssUi /> to load remote SVG files which are in different sizes. I wonder if there is a way to access the SVG props. I have tried to create a ref but it doesn't work. 

Or if there is a way to keep the original ratio of the SVG view area would be great. 

I appreciate your kind help.

**Comment by bohdanprog** [comment]
Hello @namti,
If the issue still persists, could you share an example?
Thank you.
