### ISSUE TITLE
Scale not working the way that transform scale works with svg

### ISSUE THREAD

**Issue by velociwabbit** [software-mansion/react-native-svg#1565]
in a G component (and others)

scale option has one value which is a number scale= 2

In the transform attribute of a g element the scale option has both x and y attributes transform='scale(2,4)

Perhaps there is another way to accomplish this with matrix (but i did not see matrix as an option)

If matrix is an option then this should be documented as part of the scale documentation

**Comment by WoLewicki** [comment]
`scale` prop can take both dimensions as its value, there are also `scaleX` and `scaleY` props: https://github.com/software-mansion/react-native-svg/blob/afaf500db9eae44394a3e55dbba3889931ff02dd/src/lib/extract/types.ts#L172-L174. Is it what you need? Or am I missing something?

**Comment by WoLewicki** [comment]
I believe it should answer your question. I'll close this issue then. If it is not true, please comment here and we can always reopen the issue then.
