### ISSUE TITLE
Default strokeLinecap value is different between Android and iOS/Web versions

### ISSUE THREAD

**Issue by souldreamer** [software-mansion/react-native-svg#1566]
# Bug

In your example project, in the circles section you have the pie example. Looking at the android preview of it, it seemed strange and very un-pie-like. Setting the strokeLinecap on the Circle to 'butt' made it look as it does on the web and iOS previews. It seems that the default value for this on Android is 'round'.

![Default Android look](https://user-images.githubusercontent.com/1394436/114603525-82515200-9ca0-11eb-88a7-30394d0a4c3c.png)
![Default Web/iOS look](https://user-images.githubusercontent.com/1394436/114603577-909f6e00-9ca0-11eb-8e21-92d3bc98ab8d.png)

## Short, Self Contained, Correct (Compilable), Example

The example expo snack: ![https://snack.expo.io/hTb8nT1zw](https://snack.expo.io/hTb8nT1zw)

**Comment by bohdanprog** [comment]
Hello @souldreamer, 
 I tried to reproduce that issue but couldn't.
Feel free to open a new one if you still have some issue.
