### ISSUE TITLE
App crashed on android release build

### ISSUE THREAD

**Issue by Vaibhaw-Redapple** [software-mansion/react-native-svg#1568]
-keep public class com.horcrux.svg.** {*;}

already applied above in proguard-rules.pro

**Comment by topheroes** [comment]
Having the same issue - app crashes. The svg files is like follows:

```
const arrow = `<svg width="9" height="8" viewBox="0 0 9 8" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M8.35355 4.35355C8.54882 4.15829 8.54882 3.84171 8.35355 3.64645L5.17157 0.464466C4.97631 0.269204 4.65973 0.269204 4.46447 0.464466C4.2692 0.659728 4.2692 0.976311 4.46447 1.17157L7.29289 4L4.46447 6.82843C4.2692 7.02369 4.2692 7.34027 4.46447 7.53553C4.65973 7.7308 4.97631 7.7308 5.17157 7.53553L8.35355 4.35355ZM0 4.5L8 4.5V3.5L0 3.5L0 4.5Z" fill="#EB5757"/>
</svg>
`;
export default arrow
```

It gets imported from the file like this:

`import logo2 from "../icons/user";`

And then used like this:

`<SvgXml width="40" height="40" xml={logo2} />`

**Comment by wanxue0804** [comment]
same issue

**Comment by sushil5** [comment]
same issue. any solution?

**Comment by charlesYun** [comment]
same issue. any solution?

**Comment by saczx** [comment]
Same

**Comment by WoLewicki** [comment]
Does this issue still persist in the newest version of library and with the proguard rules applied?

**Comment by bohdanprog** [comment]
Hello @saczx @wanxue0804  @Vaibhaw-Redapple,
Can you provide an example to reproduce that issue?
thank you.
