### ISSUE TITLE
How to use getBBox? Seems to be a problem with it being synchronous.

### ISSUE THREAD

**Issue by msageryd** [software-mansion/react-native-svg#1572]
I need to get hold of my BBox before rendering. I suppose I need to wait for the second render to get the BBox. That's fine, but I cannot get it to work. 

I'm probably doing something wrong.

Here is the getBBox part of the code. The `textRef` is assigned in the surrounding `<G>` element.

```
  const textRef = useRef();
  const [bbox, setBBox] = useState(null);

  useEffect(() => {
    if (textRef.current) {
      textRef.current.getBBox((bbox) => {
        console.log(bbox);
        setBBox(bbox);
      });
    }
  }, [bbox]);
```

I'm getting this error:
![image](https://user-images.githubusercontent.com/4483085/116050953-5c508800-a678-11eb-878c-441a4c6338bb.png)

**Comment by vomchik** [comment]
As far I know you cannot use chrome debug mode for native methods .

**Comment by msageryd** [comment]
Thanks @vomchik 
I don't follow you, though. The code above is all JS. After calling getBBox the bbox value is in JS land and should console.log without problem, AFAIK.
