### ISSUE TITLE
Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by petkovv** [software-mansion/react-native-svg#1580]
Hey guys. I have an issue for which I couldn't find any information. Most likely it is not a bug with the library but something I am doing wrong, I just couldn't figure out what can cause the problem. So The problem itself is that I receive a very strange error for which I will attach an image of my simulator.
![Simulator Screen Shot - iPhone 11 - 2021-05-07 at 14 25 33](https://user-images.githubusercontent.com/40954224/117446681-197a9400-af45-11eb-9866-22fe32be27ab.png)

That happens using SvgUri from the react-native-svg like this
```javascript
<SvgUri
  uri={silkUrl}
  height={svgSilkHeight}
  width={svgSilkWidth}                              
/>
```

Versions:

"react-native": "0.63.4",
"react": "16.13.1",
"react-native-svg": "12.1.1",

If some more info is needed I will add it. Thanks in advance :)

**Comment by selibrah** [comment]
can share with us an example of the values of these variables:
slikUrl
svgSilkHeight
svgSilkWidth
usually, this error appears when you tape some word or letter without putting it inside a <Text><Text/> components, I assume u just miss-click some button so u wrote a letter outside Text componenets and u didn't notice it.
Try to comment on the SvgUri and check if the problem still there.

**Comment by petkovv** [comment]
Hey @selibrah, when I comment or remove the SvgUri the error disappears too.

**Comment by petkovv** [comment]
The problem is not reproducible on version 11.0.1 of the library. At least for me downgrading to 11.0.1 worked. :)

**Comment by TomasSestak** [comment]
Getting the same issue on 12.1.1 Expo, downgrading to 11.0.1 didn't help me,
here is the uri: https://demo.nsure.cz/assets/img/insurance-items/8.svg

**Comment by TomasSestak** [comment]
@selibrah could you have a look at it?

**Comment by kriss-u** [comment]
@TomasSestak I encountered this issue because we had an extra character (malformed svg file). The issue was gone once we fixed the SVG file.

**Comment by petkovv** [comment]
Hey guys, I was wrong actually it is reproducible on every version of the library I try. Well, the issue is that from the external SVG I use some of them are quite broken. What I mean is that they have some texts in random places in them. I tried to make a separate call for each via the fetch API, but unfortunately even those which are broken returns status 200 and ok: true. It is a big problem because the app crashes and we can not afford this to happen on production. IF someone has any solution I will be very happy if he/she shares it with us here. Thanks in advance.

**Comment by SikoraKam** [comment]
Same happens to me

**Comment by WoLewicki** [comment]
@NilsBaumgartner1994 you have `undefined` string inside the svg, if you remove it, it renders correctly on my device. Since this svg renders correctly in the browser, it seems like a bug in the parser implementation, so I would start with looking there for why it adds `undefined` as a string. You can check it here by passing your svg e.g. here: https://www.svgviewer.dev/svg-to-react-native-jsx

**Comment by yume-chan** [comment]
This works:

```js
import { Text, View, StyleSheet } from 'react-native';
import { Svg, Text as SvgText } from 'react-native-svg';

function MyFancyText() {
  return 'Hello World';
}

export default function App() {
  return (
    <Text>
      Here is my fancy text:
      <MyFancyText />
    </Text>
  );
}
```

But this not:

```js
<Svg>
  <SvgText y={20} fill="black">
    Here is my fancy text in SVG:
    <MyFancyText />
  </SvgText>
</Svg>
```

**Comment by ZeroToNine09** [comment]
In my case it was due to invalid svg file.
Specifically, one tag may not have an opening (<)

**Comment by bohdanprog** [comment]
Hello, 
I believe the issue has already been resolved. If you are still experiencing problems, please feel free to open a new one.
Thank you
