### ISSUE TITLE
Android: increase compileSdkVersion to 30

### ISSUE THREAD

**Issue by pvegh** [software-mansion/react-native-svg#1586]
We want to move to java 11 in our project updating these lines:
sourceCompatibility JavaVersion.VERSION_1_8

We have a build error because some libs like react-native-svg are still compiling with < 30 like:
compileSdkVersion safeExtGet('compileSdkVersion', 28)

Error:
In order to compile Java 9+ source, please set compileSdkVersion to 30 or above

So please compile with 30 so that we can do our update.

Maybe also even switch to:
sourceCompatibility JavaVersion.VERSION_11

**Comment by iAmNoobDev** [comment]
Hey, were you able to solve above problem ??
