### ISSUE TITLE
Image not shown in web

### ISSUE THREAD

**Issue by pefuer** [software-mansion/react-native-svg#1587]
Hey guys,

Maybe you can help me with an issue with the Image component of your library. I am trying to use a png/jpg file as background for a svg. This works fine on Android, but the images are not shown in a web browser.

### Bug

Maybe it's a bug. If not I'd be happy if you could explain me how to properly reference images such that they're also shown in the browser.

### Unexpected behavior

The behavior can be observed here: [https://snack.expo.io/@pefue/image-demo](https://snack.expo.io/@pefue/image-demo)

No images are shown when targeting 'web'. Images are shown when for example targeting Android.

#### Web
![Web](https://i.ibb.co/TKkBsjC/web.png)
#### Android
![Android](https://i.ibb.co/QrF78Tx/android.png)

### Workaround in Example Snack
The react-native-svg-example has a workaround ([https://snack.expo.io/@msand/react-native-svg-example](https://snack.expo.io/@msand/react-native-svg-example)).
In the example, two additional components `SnackImageCompat.js` and `SnackImageCompat.web.js` are used as wrappers for `Image`. However, this workaround appears to not work anymore with more recent Expo versions. One can get it running by choosing  Expo v38.0.0. Unfortunately I did not succeed in fixing the workaround.

**Comment by molchanovskiy** [comment]
Same for me!
@pfuersattel Did you found any solutions?

**Comment by pfuersattel** [comment]
@molchanovskiy sorry, I wasn't able to figure out a workaround. Anyone else?

**Comment by jimmi-joensson** [comment]
Experiencing the same issue

**Comment by bohdanprog** [comment]
Hello @pefuer @molchanovskiy @jimmi-joensson @Estevete,
I tried to reproduce that but couldn't.
I believe the issue has already been resolved. If you are still experiencing problems, please feel free to open a new one.
Thank you.
