### ISSUE TITLE
TypeScript type definitions do not permit `color` property in `<Svg>` `style` prop

### ISSUE THREAD

**Issue by SimpleCreations** [software-mansion/react-native-svg#1589]
# Bug

```typescript
import React from "react";
import Svg, {Rect} from "react-native-svg";

export default function App() {
    return (
        <Svg style={{color: "#F00"}}>
            <Rect x={0} y={0} width={50} height={50} fill="currentColor" />
        </Svg>
    );
}
```

#### Unexpected behavior

    TS2322: Type '{ color: string; }' is not assignable to type 'StyleProp<ViewStyle>'.   Object literal may only specify known properties, and 'color' does not exist in type 'ViewStyle | RecursiveArray<Falsy | ViewStyle | RegisteredStyle<ViewStyle>>'.

The `color` property is not permitted, although the color is still rendered correctly with `@ts-ignore`.

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 146.23 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: ^0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.1

**Comment by developerdizzle** [comment]
Also running into this!

**Comment by isonlaxman** [comment]
Was there any resolution on this? I'm running into the same issue

**Comment by SimpleCreations** [comment]
@isonlaxman I personally just suppress it with `@ts-ignore` 🤷‍♂️
I could do a PR but I don't think it would be merged anytime soon.

**Comment by caiothemaintab** [comment]
As a workaround I am using this:

```typescript
import { TextStyle } from "react-native";
import { SvgProps } from "react-native-svg";

type CustomSvgStyle = Pick<SvgProps, "style"> & { color: Pick<TextStyle, "color"> };

export type CustomSvgProps = Omit<SvgProps, "style"> & { style: CustomSvgStyle };

```

**Comment by bombillazo** [comment]
Im getting a similar error but for the `style` prop... :/

**Comment by WoLewicki** [comment]
The error is correct since the `color` prop does not exist in the `style` prop and it should be passed a direct prop of `Svg`, like that: `<Svg color="#F00">`. I'll close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by bombillazo** [comment]
Why does it work then, though? Kind of misleading. 😕

**Comment by SimpleCreations** [comment]
I agree with @bombillazo. Passing the color as style does help achieve the desired result. The problem here is that the types are defined in a way that does not allow this.

**Comment by WoLewicki** [comment]
It works since the props passed to the style are flattened and treated as if you passed them as normal props. Still, the types are correct, `style` object does not accept `color` prop.

**Comment by SimpleCreations** [comment]
@WoLewicki IMO if the library behaves a certian way but it is not reflected in the type definitions, it is a bug. I think we should either remove the functionality you described or make sure the types include it, otherwise it might lead to confusion (which made me create this issue in the first place).

If you reopen the issue I'll be happy so submit a PR that adds the types (as removing functionality might be a breaking change).

**Comment by bombillazo** [comment]
Shouldn't then the solution be to create and use a custom props type, not `StyleProp<ViewStyle>`, for the `<SVG />` component to enable this behavior? Typing should reflect the behavior and doesn't have to conform to existing types. The custom type can extend the existing StyleProp.

**Comment by WoLewicki** [comment]
To be honest I don't think it is a problem. You can try it with a RN's `View` component: `<View style={{flex: 1}} backgroundColor="red">` and `<View style={{flex: 1, backgroundColor: 'red'}}>` will yield the same effect because style prop is flattened.

**Comment by bombillazo** [comment]
I'm not sure if you use TypeScript, functionally it may not be a problem since perhaps like you say internally the prop is flattened but with TypeScript it becomes evident very fast that TS will view it as invalid because `backgroundColor` is not defined as a prop of `View`. Plus you don't get any IntelliSense completion. If one has linters/type checks as part of their development pipeline, the build will fail due to typing errors.

**Comment by WoLewicki** [comment]
So what is the problem exactly? Typescript does not allow `color` since it should not be used as a prop of `style` object, but as a direct prop of `Svg`.
