### ISSUE TITLE
Change `rgbaArray` type definition to a tuple

### ISSUE THREAD

**Issue by acashjos** [software-mansion/react-native-svg#1590]
# Feature Request

More of a tiny typedef improvement suggestion. 
I accidentally imported  `rgbaArray` from `index.d.ts` of this module today, and noticed that its a `ReadonlyArray<number>`.
This type can have n number of items, while I'd expect an rgba type to have only 4 number items.

### Code sample
Changing
`export type rgbaArray = ReadonlyArray<number>;`
to
`export type rgbaArray =Readonly<[r:number, g: number, b: number, a: number]>`;

**Comment by WoLewicki** [comment]
This type has been removed as a part of https://github.com/software-mansion/react-native-svg/pull/1726, so I believe this is not a problem anymore. Thanks for your contribution though! I will close this issue. Feel free to comment here if something is wrong and we can always reopen it then.
