### ISSUE TITLE
Marker - display issues on android

### ISSUE THREAD

**Issue by mlecoq** [software-mansion/react-native-svg#1592]
# Bug

I am using `Markers`, it works well on iOS, but on Android markers are only displayed on `<Path/>` (I can't see them on `<Line/>`, `<Ellipse/>` and `<Rectangle/>`)

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 97.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.1

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/mlecoq/svg-draw
2. cd svg-draw
3. yarn
4. yarn start

Describe what you expected to happen:

1. Use pen to draw on picture (you see the markers in blue on both iOS and android) 
2. Use line, rect or circle (no marker on android but it works on iOS)

**Comment by iguiIllanes** [comment]
Hey! I'm having the same issue on android when trying to put a marker on a line, I saw that you added support on android code itself. Is there anyway to accomplish this on expo?

**Comment by iguiIllanes** [comment]
> Hey! I'm having the same issue on android when trying to put a marker on a line, I saw that you added support on android code itself. Is there anyway to accomplish this on expo?

nvm, a quick google search taught me how to do it [here](https://docs.expo.dev/workflow/customizing/)
