### ISSUE TITLE
<Rect/>: A negative 'height' with 'rx' will crash the app

### ISSUE THREAD

**Issue by thiskevinwang** [software-mansion/react-native-svg#1602]
# Bug

This seems like a pretty small / straightforward-to-repro bug

Using
- `"expo": "~41.0.1",`
- `"react-native-svg": "12.1.0",`

✅ For a `<Rect/>` component, a negative `height` (ex. `-10` or `"-10"`) still renders fine

❌ But when you have a negative height **AND** you specify `rx`, the app crashes, and with zero console output (at least I wasn't able to log anything). Through trial and error, I finally narrowed down the repro steps.

### THIS WILL CRASH YOUR CODE
```diff
<Rect
  x="15"
  y="15"
  width="70"
- height="70"
+ height="-70"
  stroke="red"
  strokeWidth="2"
  fill="yellow"
+ rx="10"
/>
```

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 899.54 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: `"react-native-svg": "12.1.0",`

**Comment by mrmuffyman** [comment]
Also happening to me. Thanks for making this known.

**Comment by dion-george** [comment]
Facing the same issue, any workarounds?

**Comment by chintrinh-groove** [comment]
happing to me. Please help me to solve it.

**Comment by itsramiel** [comment]
Can confirm this is happening on 13.9.0

**Comment by AndreCosta101** [comment]
Also happening to me. Expo 48.0.18 react-native-svg: 13.4.0

**Comment by bohdanprog** [comment]
Hello @thiskevinwang,
I couldn't reproduce that problem, if you still have some issues, feel free to open a new issue.
Thank you
