### ISSUE TITLE
/node_modules/react-native-svg/android/build/intermediates/annotation_processor_list/debug/annotationProcessors.json (No such file or directory)

### ISSUE THREAD

**Issue by crly** [software-mansion/react-native-svg#1605]
android bulid error

/node_modules/react-native-svg/android/build/intermediates/annotation_processor_list/debug/annotationProcessors.json (No such file or directory)

**Comment by bohdanprog** [comment]
Hello @crly,
I suggest updating the library and starting fresh from the beginning. If the issue persists, please feel free to open a new problem report.
Thank you.
