### ISSUE TITLE
Did anyone measure performance of SvgXml vs tags? 

### ISSUE THREAD

**Issue by beshur** [software-mansion/react-native-svg#1609]
Hello.

I'm building an application that has a lot of SVG icons on the screen at all times.
It grew a habit on this project to use `SvgXml` for icon contents.

Did anyone measure performance of SvgXml vs tags (`Svg`, `Path` etc.) or how can it be done?

**Comment by vomchik** [comment]
@beshur Using `SvgXml ` should be slower, as you need to spend time parsing SVG content in runtime.
