### ISSUE TITLE
Font not displayed correctly

### ISSUE THREAD

**Issue by IPbianco** [software-mansion/react-native-svg#1623]
# Bug

**The problem is on iOS, Android looks alright. Font family that is used is RyoGothicPlusN-EL**

Fonts should be displayed correctly. However we have these problems in iOS:

- We specify different fonts but they all look the same using svg text, see difference with normal react native text in screenshot
- November is displayed as No. vember

**iOS (Has the problem) vs Android (Looks alright)**

<img width="336" alt="Screenshot 2021-08-04 at 17 38 36" src="https://user-images.githubusercontent.com/26870666/128220355-2e3b4fc6-3441-4c54-8a46-645f06092678.png"><img width="353" alt="Android" src="https://user-images.githubusercontent.com/26870666/128226323-bb361030-4b60-43ce-a099-d62650fd441f.png">

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 11.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 402.86 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/ignacio/.rvm/rubies/ruby-2.6.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 31
      Build Tools: 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 31.0.0
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Library version: 12.1.1

## Steps To Reproduce

https://github.com/IPbianco/rnsvg-bug-repro

1. git  clone https://github.com/IPbianco/rnsvg-bug-repro.git
2. cd rnsvg-bug-repro
3. yarn
4. cd ios
5. pod install
6. cd ..
4. npx react-native start (start metro bundler)
5. npx react-native run-ios (start app)
6. Open CleanProject app on the simulator

Describe what you expected to happen:

Fonts should be displayed correctly. However we have these problems in iOS:

- We specify different fonts but they all look the same using svg text, see difference with normal react native text in screenshot
- November is displayed as No. vember

**Comment by gfmoore** [comment]
No solution, but I'd be interested in knowing how you get these fonts to display anyway. When I try using fontFamily I can get a serif and a sans-serif, but they look awful
(Android simulator Pixel 5) 

```
<Svg height="100%" width="100%" viewBox={`0 0 100 100`}>
   ...
   <Text x='10' y='70' stroke='white' fill='white' fontFamily='sans-serif-thin' fontSize='10'  >0 kph</Text>
</Svg>
```
![image](https://user-images.githubusercontent.com/22768967/134508248-3f8d3790-51e2-4ce4-a58f-28107283d3bb.png)

Note how blocky it is and no space between letters, horrible.

I've tried serif, sans-serif, sans-serif-thin, sans-serif-light
I tried your RyoGothicPlusN-EL, but no change (I assume this is some custom font or one you downloaded?)

Gordon

**Comment by gfmoore** [comment]
This is a bit odd. I just copied your code from the repo and tried on the android simulator, made a couple of adjustments to the positioning and didn't get any change in font style at all, unlike in your image above.

![image](https://user-images.githubusercontent.com/22768967/134652494-82ff1f42-65fa-4dde-913c-d24929da9b8f.png)

These are the installed fonts according to this https://www.exeideas.com/2016/02/list-of-default-fonts-in-android.html, but   RyoGothicPlusN-EL isn't one of them? I assume again that you have downloaded and installed this.

However, I have tried your code using some of the fonts in the link and get this:

![image](https://user-images.githubusercontent.com/22768967/134654269-20d4d53c-afc9-45d4-8d5c-87a40fa3d201.png)

Sorry, if this is obvious to some people, but I'm a bit new to React-Native and svg.

I realise it doesn't help with the ios issue as well.

And for completeness here is the code:
```
      <View style={styles.svgTextSection}>
        <Text style={styles.title}>******** SVG Text ********</Text>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="sans-serif"
            fontStyle='normal'
            >
            sans-serif normal
          </SvgText>
        </Svg>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="sans-serif"
            fontStyle='italic'>
            sans-serif italic
          </SvgText>
        </Svg>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="sans-serif"
            fontWeight="bold">
            sans-serif-bold
          </SvgText>
        </Svg>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="sans-serif-thin"
            fontStyle="normal">
            sans-serif thin
          </SvgText>
        </Svg>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="sans-serif-light"
            fontStyle="normal">
            sans-serif light
          </SvgText>
        </Svg>
        <Svg height="50" width="400">
          <SvgText
            fill="white"
            x="20"
            y="50"
            fontSize={20}
            fontFamily="serif"
            fontStyle="normal">
            serif regular
          </SvgText>
        </Svg>
      </View>
 
```

**Comment by gfmoore** [comment]
So after a days work I discovered that my issue was due to the use of 
```
<Svg height='100%' width='100%'  viewBox="0 0 100 100">
```
The use of viewBox really didn't work well with the fontSize and style. I don't know why.

I stopped using it and wrote my own mapping function:
```
  const dw = Dimensions.get('window').width  //don't forget to import Dimension in react-native
  const dh = Dimensions.get('window').height
  const aspect = dw / dh

 //convert x (0->100) to svg coords on screen, y follows aspect ratio for same
  const xs = (x) => { return x/100 * dw  }
  const ys = (y) => { return y/100 * aspect * dh }

//and now call xs(some number between 0 and 100) and ys(between 0 and probably much more than 100 for the y pos)

```

This seems to work really well in my use case. The text now displays clearly and properly.

Sorry that I have hijacked this thread somewhat :( but if anyone came here they might have wondered what a possible solution is to my use case and this was the only search result I found that even referenced the sort of problem I was having.)

However, it might point the way forward for the use of ios code, though your test case didn't use a viewBox, so maybe not? (I don't have a mac)

I hope that this issue gets some priority as obviously this is a pretty major problem.
