### ISSUE TITLE
svg pixel mask looks broken

### ISSUE THREAD

**Issue by dodicandra** [software-mansion/react-native-svg#1624]
# Bug

The element that I masked looks really ugly, like a broken pixel

## Environment info
using expo

Library version: next

Describe what you expected to happen:

1.I hope the pixel elements that I mask look good

# Snack
[snack.io](https://snack.expo.dev/@dodicandra/github.com-dodicandra-react-navigation-costume-bottom-bar@main)

# screen shot
<img width="392" alt="Screen Shot 2021-08-08 at 12 34 50 PM" src="https://user-images.githubusercontent.com/48325708/128622126-9056c430-3526-47ff-9810-00106d6166f3.png">

**Comment by bohdanprog** [comment]
Hello @dodicandra,
Are you still experiencing that issue?
