### ISSUE TITLE
How to make Image with border radius 

### ISSUE THREAD

**Issue by taitran2512** [software-mansion/react-native-svg#1640]
# Question
I'm using react-native-svg-charts (pie chart) and I customizing the Image for each value, but I can not set border radius for the image. I find anywhere but no one can solve it. How can I do it? Thanks

This is my code
![image](https://user-images.githubusercontent.com/65691647/133425369-25db5fc0-06d0-473e-a970-48b5223ba4c3.png)

and this is result 
![image](https://user-images.githubusercontent.com/65691647/133425429-87c97115-51dd-449c-98d6-00dbc2d2dabf.png)

**Comment by bohdanprog** [comment]
@taitran2512 Do you still have that issue?
