### ISSUE TITLE
Add the id of the gradient that has no stops in the logged warning

### ISSUE THREAD

**Issue by pke** [software-mansion/react-native-svg#1642]
The painter logs a warning when a gradient does not contain a stop attribute.

https://github.com/react-native-svg/react-native-svg/blob/fa71673b5834e593b5f8b021e28530ec2a466853/apple/Brushes/RNSVGPainter.m#L196

Would it be possible to print the `id` of the gradient to the log too?

Same goes for Android (where the logged message is also slightly different)

**Comment by bohdanprog** [comment]
Hello @pke,
If you are still experiencing that issue, please provide a simple example to reproduce the problem.
Thank you.
