### ISSUE TITLE
Placeholder & error callback for SvgUri, SvgFromUri and SvgWithCssUri

### ISSUE THREAD

**Issue by AurangShah** [software-mansion/react-native-svg#1643]
**I have used SvgUri, SvgFromUri and SvgWithCssUri for loading the SVG from URI.** 

I just want to know if this library has the feature to load another placeholder image if the URI is not found or is loading a webpage instead of SVG.

_It doesn't have the error callback as well._

Please let me know, It's an essential feature I think.

**Comment by WoLewicki** [comment]
I think the thing you need has been added in #1503 (see https://github.com/react-native-svg/react-native-svg/pull/1503#issuecomment-1059109229 how to use it to try and load another `svg`). There is also https://github.com/react-native-svg/react-native-svg/pull/1718 adding same behavior to `SvgCssUri`. Could you check if it is what you need?

**Comment by WoLewicki** [comment]
Closing since #2071 has been merged and it provides better handling of parsing error.
