### ISSUE TITLE
Reactive-Native-SVG: Export with Adobe XD Fireblade plugin. Works with IOS, but blank screen with Android/

### ISSUE THREAD

**Issue by susanmckenna** [software-mansion/react-native-svg#1648]
Works in IOS, but I get a blank screen with Android.

I'm a New Bee to mobile app development, but a web developer for decades.  Although I'm grateful for all the knowledge I've gained in the last two weeks (~100 hrs), I'm stumped.  My graphic designer at work designed a phone app with Adobe XD, but needed help publishing it.  So I volunteered.    Oh boy, do I need help too. Thank you in advance for any help you can provide.  

My Reactive-Native build is based on NPM/EXPO installed on my own computer, but I've also tried to get it to work with the help of https://snack.expo.dev/ as well as https://codesandbox.io/ .  Same result on everything.

I've tried re-installing everything to the latest version.  Tried installing several emulators using Android Studio, as well as scanning the QR code with Expo Go (Android) and the Camera app (iOS), but to know avail.

My local install versions:

react:  "version": "16.13.1"
react-native:  "version": "0.63.2"
react-native-svg:  "version": "12.1.1"

Simplest version of problem CODE:

//==========================================
import { Text, View, StyleSheet, ScrollView } from 'react-native';
import Constants from 'expo-constants';
import React, {Component} from 'react';
import {TextInput, FlatList, Picker, TouchableHighlight} from 'react-native';
import {Image as ReactImage} from 'react-native';
import Svg, {Defs, Pattern} from 'react-native-svg';
import {Path as SvgPath} from 'react-native-svg';
import {Text as SvgText} from 'react-native-svg';
import {Image as SvgImage} from 'react-native-svg';

export default class Iphone1212Pro1 extends Component {

  render() {
    return (
    <ScrollView data-layer="54c4c849-1f05-4abe-bd9f-b6178a2469cc" style={styles.iphone1212Pro1}>
        <View data-layer="dde52a0c-b2da-47c0-8428-5ae36a36a3b8" style={styles.iphone1212Pro1_rectangle10}></View>
        <View data-layer="cf4fa74a-8a9b-4d40-bdce-af968308d915" style={styles.iphone1212Pro1_group10}>
            <Svg data-layer="5debcaf4-166a-4f90-9cd1-1a6c68373a29" style={styles.iphone1212Pro1_group10_path16} preserveAspectRatio="none" viewBox="131.80499267578125 89.02698516845703 165.3900146484375 124.7330322265625" fill="rgba(168, 54, 58, 1)"><SvgPath d="M 277.489013671875 89.77700042724609 L 151.5099945068359 89.94100189208984 C 141.0829925537109 89.95500183105469 132.5549926757812 98.49500274658203 132.5549926757812 108.9229965209961 L 132.5549926757812 194.0789947509766 C 132.5549926757812 204.5050048828125 141.0829925537109 213.0249938964844 151.5099945068359 213.0099945068359 L 277.489013671875 212.8459930419922 C 287.9140014648438 212.8320007324219 296.4450073242188 204.2899932861328 296.4450073242188 193.8659973144531 L 296.4450073242188 108.7089996337891 C 296.4450073242188 98.28299713134766 287.9140014648438 89.76300048828125 277.489013671875 89.77700042724609 Z M 285.7210083007812 194.2890014648438 C 285.7210083007812 199.0339965820312 281.8590087890625 202.8939971923828 277.1130065917969 202.8939971923828 L 151.8860015869141 202.8939971923828 C 147.1399993896484 202.8939971923828 143.2799987792969 199.0339965820312 143.2799987792969 194.2890014648438 L 143.2799987792969 108.5 C 143.2799987792969 103.7539978027344 147.1399993896484 99.89299774169922 151.8860015869141 99.89299774169922 L 277.1130065917969 99.89299774169922 C 281.8590087890625 99.89299774169922 285.7210083007812 103.7539978027344 285.7210083007812 108.5 L 285.7210083007812 194.2890014648438 Z"  /></Svg>
 </View>
 </ScrollView>

    );
    
  }
}

const styles = StyleSheet.create({
  iphone1212Pro1: {
    opacity: 1,
    position: "relative",
    backgroundColor: "rgba(255, 255, 255, 1)",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 390,
    height: 844,
    left: 0,
    top: 0
  },
  iphone1212Pro1_rectangle10: {
    opacity: 1,
    position: "absolute",
    backgroundColor: "rgba(36, 71, 98, 1)",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0)",
    borderRightWidth: 1,
    borderRightColor: "rgba(0, 0, 0, 0)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0)",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(0, 0, 0, 0)",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: 389,
    height: 843,
    left: -0.5,
    top: -0.5
  },
  iphone1212Pro1_group10: {
    opacity: 1,
    position: "absolute",
    backgroundColor: "transparent",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 163.89,
    height: 123.23,
    left: 114,
    top: 174
  },
  iphone1212Pro1_group10_path16: {
    opacity: 1,
    position: "absolute",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 165.89,
    height: 125.23,
    left: -1,
    top: -1
  }
 
});
//==========================================

# Bug
SVGA works in IOS, but I get a blank screen with Android.

## Environment info
// I'm having trouble running react-native info in my terminal window.  I don't think my terminal window is working any longer

react:  "version": "16.13.1"
react-native:  "version": "0.63.2"
react-native-svg:  "version": "12.1.1"

## Steps To Reproduce

![android](https://user-images.githubusercontent.com/37411678/135506799-1d984796-0bc4-405a-a1b5-b3f8d3c738d8.png)
![Iphone](https://user-images.githubusercontent.com/37411678/135506814-84714155-1523-4001-91a8-cf953823fecf.png)

Please let me know if I've left out anything.  I notice that my render() { return ()} is not visible under the Preview tab.  Is that normal?

Thank you again for your time and effort in helping me, and helping all that reach out to you.

Sincerely,
Susan

**Comment by susanmckenna** [comment]
Not sure why the render() { return ()} code is not showing here.

**Comment by susanmckenna** [comment]
`import { Text, View, StyleSheet, ScrollView } from 'react-native';
import Constants from 'expo-constants';
import React, {Component} from 'react';
import {TextInput, FlatList, Picker, TouchableHighlight} from 'react-native';
import {Image as ReactImage} from 'react-native';
import Svg, {Defs, Pattern} from 'react-native-svg';
import {Path as SvgPath} from 'react-native-svg';
import {Text as SvgText} from 'react-native-svg';
import {Image as SvgImage} from 'react-native-svg';

export default class Iphone1212Pro1 extends Component {

  render() {
    return (
    <ScrollView data-layer="54c4c849-1f05-4abe-bd9f-b6178a2469cc" style={styles.iphone1212Pro1}>
        <View data-layer="dde52a0c-b2da-47c0-8428-5ae36a36a3b8" style={styles.iphone1212Pro1_rectangle10}></View>
        <View data-layer="cf4fa74a-8a9b-4d40-bdce-af968308d915" style={styles.iphone1212Pro1_group10}>
            <Svg data-layer="5debcaf4-166a-4f90-9cd1-1a6c68373a29" style={styles.iphone1212Pro1_group10_path16} preserveAspectRatio="none" viewBox="131.80499267578125 89.02698516845703 165.3900146484375 124.7330322265625" fill="rgba(168, 54, 58, 1)"><SvgPath d="M 277.489013671875 89.77700042724609 L 151.5099945068359 89.94100189208984 C 141.0829925537109 89.95500183105469 132.5549926757812 98.49500274658203 132.5549926757812 108.9229965209961 L 132.5549926757812 194.0789947509766 C 132.5549926757812 204.5050048828125 141.0829925537109 213.0249938964844 151.5099945068359 213.0099945068359 L 277.489013671875 212.8459930419922 C 287.9140014648438 212.8320007324219 296.4450073242188 204.2899932861328 296.4450073242188 193.8659973144531 L 296.4450073242188 108.7089996337891 C 296.4450073242188 98.28299713134766 287.9140014648438 89.76300048828125 277.489013671875 89.77700042724609 Z M 285.7210083007812 194.2890014648438 C 285.7210083007812 199.0339965820312 281.8590087890625 202.8939971923828 277.1130065917969 202.8939971923828 L 151.8860015869141 202.8939971923828 C 147.1399993896484 202.8939971923828 143.2799987792969 199.0339965820312 143.2799987792969 194.2890014648438 L 143.2799987792969 108.5 C 143.2799987792969 103.7539978027344 147.1399993896484 99.89299774169922 151.8860015869141 99.89299774169922 L 277.1130065917969 99.89299774169922 C 281.8590087890625 99.89299774169922 285.7210083007812 103.7539978027344 285.7210083007812 108.5 L 285.7210083007812 194.2890014648438 Z"  /></Svg>
 </View>
 </ScrollView>

    );
    
  }
}

const styles = StyleSheet.create({
  iphone1212Pro1: {
    opacity: 1,
    position: "relative",
    backgroundColor: "rgba(255, 255, 255, 1)",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 390,
    height: 844,
    left: 0,
    top: 0
  },
  iphone1212Pro1_rectangle10: {
    opacity: 1,
    position: "absolute",
    backgroundColor: "rgba(36, 71, 98, 1)",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0)",
    borderRightWidth: 1,
    borderRightColor: "rgba(0, 0, 0, 0)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0)",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(0, 0, 0, 0)",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    width: 389,
    height: 843,
    left: -0.5,
    top: -0.5
  },
  iphone1212Pro1_group10: {
    opacity: 1,
    position: "absolute",
    backgroundColor: "transparent",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 163.89,
    height: 123.23,
    left: 114,
    top: 174
  },
  iphone1212Pro1_group10_path16: {
    opacity: 1,
    position: "absolute",
    marginTop: 0,
    marginRight: 0,
    marginBottom: 0,
    marginLeft: 0,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    width: 165.89,
    height: 125.23,
    left: -1,
    top: -1
  }
 
});`

**Comment by susanmckenna** [comment]
I did not mean to close this.  trying to figure out how to re-open.

**Comment by susanmckenna** [comment]
Yay for the re-open buttton!!!

**Comment by susanmckenna** [comment]
Maybe this can help:

https://snack.expo.dev/Fjc3n2_al

**Comment by bohdanprog** [comment]
Hello @susanmckenna,
I tried to reproduce that issue, but couldn't.
Let me know if you still have that issue.
Thank you

**Comment by susanmckenna** [comment]
Hi,  that was from a couple of years ago
