### ISSUE TITLE
Detecting if a point (x, y)  is inside SVG

### ISSUE THREAD

**Issue by ritathesaver** [software-mansion/react-native-svg#1651]
I know that there are some native methods that are experimental but not fully implemented. And one of this methods is isPointInFill to determine if the point is inside the SVG shape. Can you share with some initial implementation of this function to take it into developing, if you have a such one? So maybe I can continue implementation of this method.

**Comment by bohdanprog** [comment]
Helo @ritathesaver,
I'm not sure if it's still a relevant question, but I found a [thread](https://github.com/software-mansion/react-native-svg/pull/1135#issuecomment-538013151) discussing what you asked about.
If you still have any questions, please don't hesitate to ask.
