### ISSUE TITLE
class attribute not working for path

### ISSUE THREAD

**Issue by DanielKalmuratov** [software-mansion/react-native-svg#1653]
class attribute not working for path
my xml: 
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600">
<defs>
<style>.cls-1{fill:#fff;}.cls-2{fill:#44e000;}</style>
</defs>
<title>Ресурс 1</title>
<g id="Слой_2" data-name="Слой 2">
<g id="Layer_1" data-name="Layer 1">
<rect class="cls-1" width="600" height="600"/>
<path d="M84,319.31q-9.36,0-15.21-3.23A15.5,15.5,0,0,1,61.92,309a17,17,0,0,1-1.62-7.37V300.2a17.43,17.43,0,0,1,1.52-7.41,14.79,14.79,0,0,1,6.75-7q5.85-3.09,15.4-3.09h2q9.56,0,15.26,2.66a15.31,15.31,0,0,1,6.84,5.8,10.6,10.6,0,0,1,1.57,5.47v.52H97.85c0-.13-.21-.57-.52-1.33a6,6,0,0,0-1.93-2.07A12.48,12.48,0,0,0,91.67,292a23.4,23.4,0,0,0-6.75-.77q-7.23,0-10.46,2.9a8.08,8.08,0,0,0-2.56,6.28V301a9.48,9.48,0,0,0,.64,3.4,8.1,8.1,0,0,0,2.07,3Q78,310.7,85,310.7q7.37,0,10.64-2.85a5.2,5.2,0,0,0,1.76-2.14l.48-1.28h11.74V305a11.43,11.43,0,0,1-.38,2.78,10.37,10.37,0,0,1-1.29,2.93,15.36,15.36,0,0,1-6.89,5.89q-6,2.76-15.16,2.76Z"/>
<path d="M207.47,318.69l-3.32-6.46H182.71l-3.18,6.46H168.26l17.87-35.36h14.36l18.91,35.36Zm-7.41-14.45L193.21,291l-6.56,13.26Z"/>
<path d="M232.43,306.9v11.79H221.35V283.33h26.52q9,0,13,3.32a10.09,10.09,0,0,1,3.47,8.18v.47a10,10,0,0,1-3.52,8.18q-4.14,3.42-13,3.42Zm0-7.94h15.25c3.42,0,5.14-1.23,5.14-3.7v-.15c0-2.5-1.72-3.75-5.14-3.75H232.43Z"/>
<path d="M280.74,318.69v-27H265.53v-8.36h41.64v4.54L305,291.69h-13v27Z"/>
<path d="M309,283.33h41.35v7.46H320.1v5.37h14.74q10.21,0,14.54,3c2.38,1.75,3.57,4.34,3.57,7.8v.47a12.13,12.13,0,0,1-.81,4.57,8,8,0,0,1-2.71,3.42c-2.92,2.15-7.79,3.23-14.64,3.23H309ZM334.74,311q3.66,0,5.28-1.09a2.94,2.94,0,0,0,1.38-2.62v-.14a2.83,2.83,0,0,0-1.38-2.57c-1-.63-2.77-.95-5.28-.95H320.1V311Z"/>
<path d="M380.79,310.51q-1.53,2.63-2.52,4a11.49,11.49,0,0,1-2.14,2.28,8.42,8.42,0,0,1-2.92,1.45,16.1,16.1,0,0,1-4.16.45h-6.94v-8.56h6.22c.83,0,1.24-.25,1.24-.76v0a1.81,1.81,0,0,0-.21-.81,5.9,5.9,0,0,0-.55-.86l-16.68-24.33H365l11,17.16,10-17.16H397Z"/>
<path d="M418.36,282.85h11.08V286h9.07a24.61,24.61,0,0,1,6.3.8,17,17,0,0,1,5.35,2.43,12.21,12.21,0,0,1,3.92,4.44,13.37,13.37,0,0,1,1.4,6.3v.52q0,7-5.32,10.79a16.25,16.25,0,0,1-5.32,2.47,24,24,0,0,1-6.28.81h-9.12v4.57H418.36V314.6h-9.12a24,24,0,0,1-6.28-.81,16.25,16.25,0,0,1-5.32-2.47q-5.33-3.75-5.32-10.79v-.47a13.25,13.25,0,0,1,1.42-6.3,12.89,12.89,0,0,1,3.95-4.49,16.93,16.93,0,0,1,5.32-2.43,24.38,24.38,0,0,1,6.27-.8h9.08Zm-6.6,11.27a10.39,10.39,0,0,0-6.11,1.54,5.09,5.09,0,0,0-2.16,4.4v.38a5.28,5.28,0,0,0,2.16,4.47,10.1,10.1,0,0,0,6.11,1.61h2.88l7.44-12.4Zm14,12.4H436a10.1,10.1,0,0,0,6.11-1.61,5.28,5.28,0,0,0,2.16-4.47v-.38a5.08,5.08,0,0,0-2.18-4.4,10.43,10.43,0,0,0-6.09-1.54h-2.88Z"/>
<path d="M457.89,283.33h37.26v4L493,291.36H468.82v5.23h25.71v8.08H468.82v5.8h26.81v8.22H457.89Z"/>
<path d="M512.57,318.69v-27H497.36v-8.36H539v8.36H523.74v27Z"/>
<polygon points="139.53 305.32 127.35 283.39 111.67 283.39 111.67 318.63 122.28 318.63 122.28 294.23 136.17 318.63 142.09 318.63 155.97 294.23 155.97 318.63 166.86 318.63 166.86 283.39 151.75 283.39 139.53 305.32"/>
<path class="cls-2" d="M258.61,455.55c28.81,3.27,55.55-26.94,46.43-38.25-6.56-8.14-6.56-8.14-4.48-11.72,13.59-21,24.48-41.21,36.74-77.16.73-.76.82-.86,2.63-.48a6.82,6.82,0,0,1,1.68,1c-3.67,12.47-11.31,38.43-27.43,67.64h0c-.39,1.92.8,2.17,3.69,2.77,9.22.49,30.58-67.9,30.78-68.59,1-.74,1-.74,4.09-.2,3.42,1.61-12.64,47.33-23.42,69.17-.37,1.94.81,2.18,3.68,2.77,9.09.61,29.08-68.21,29.27-68.9,1-.75,1.18-.72,3.5-.34a7.49,7.49,0,0,1,1.68,1c-3.05,12.59-9.38,38.8-23.62,68.54-.32,1.9.79,2.13,3.74,2.75,9,.58,26.74-68.69,26.91-69.39,1-.76,1-.76,4-.24,3,1.39-8.57,47.15-24.13,80.81h0l-.4.78h0c-2.59,3.64-6.63,5-9.56,5.5a43.93,43.93,0,0,0-20.63,8.8c-9,7.21-14.56,17.91-24.79,23.79-8.13,4.68-12.56,5.14-18.87,4.39l-21.49-4.49"/>
<path class="cls-2" d="M369.58,259.75c12.41-.05,17.91-8.4,16.32-24.82-3.73-38.73-12.63-65.73-26.45-80.25-3.66-3.85-9.59-9.2-18.76-11.23L319.2,139c28.7,9.73,29.4,63.2,27.26,94.2-1,15,11.58,26.64,23.12,26.59"/>
<path class="cls-2" d="M229.72,339.25c-12.41.05-17.91,8.4-16.32,24.82,3.73,38.73,12.63,65.73,26.45,80.25,3.66,3.85,9.59,9.19,18.76,11.23L280.1,460c-28.7-9.73-29.4-63.2-27.26-94.2,1-15-11.58-26.64-23.12-26.59"/>
<path class="cls-2" d="M340.69,143.45c-28.81-3.27-55.55,26.94-46.43,38.25,6.56,8.14,6.56,8.14,4.48,11.72-13.59,21-24.48,41.21-36.73,77.16-.74.76-.83.86-2.64.48a7,7,0,0,1-1.68-1c3.67-12.47,11.31-38.43,27.43-67.65h0c.39-1.92-.8-2.17-3.69-2.78-9.21-.48-30.58,67.91-30.78,68.6-1,.74-1,.74-4.09.2-3.42-1.62,12.64-47.33,23.42-69.17.37-1.94-.81-2.18-3.68-2.77-9.09-.61-29.08,68.21-29.27,68.9-1,.75-1.18.72-3.5.34a7.21,7.21,0,0,1-1.67-1c3-12.6,9.37-38.8,23.61-68.54.32-1.9-.79-2.13-3.73-2.75-9-.58-26.75,68.68-26.92,69.38-1,.77-1,.77-4,.25-3-1.39,8.57-47.15,24.13-80.82h0l.4-.78h0c2.59-3.64,6.63-5,9.56-5.51a43.77,43.77,0,0,0,20.63-8.79c9-7.21,14.56-17.91,24.79-23.79,8.13-4.68,12.56-5.14,18.87-4.39l21.49,4.49"/>
</g>
</g>
</svg>

**Comment by bohdanprog** [comment]
Hello @DanielKalmuratov,
I can't reproduce the issue in the example you provided. If you still face that issue, feel free to open a new issue and provide a simple example of how we can reproduce the problem.
Thank you.
