### ISSUE TITLE
Using with svg files question

### ISSUE THREAD

**Issue by LuLuSaBee** [software-mansion/react-native-svg#1654]
Hi, I'm ready to use this in my project, but I have a question about [this](https://github.com/react-native-svg/react-native-svg#use-with-svg-files).

If use babel-plugin-inline-import, can svg be normal when build ?

**Comment by bohdanprog** [comment]
Hello @LuLuSaBee,
If you still have a problem with it please share with us the simple repro of what you want to achieve.
Thank you
