### ISSUE TITLE
Do this lib support `animate` tag of SVG standart?

### ISSUE THREAD

**Issue by psnet** [software-mansion/react-native-svg#1663]
SVG has standard tag `animate` that can animate anything in SVG. It usage is like this:
```tsx
<Rect x="25" y="0" width="750" height="290" stroke="url(#Gradient)" strokeWidth="50" fill="transparent">
  <animate attributeType="XML" attributeName="y" from="0" to="50" dur="2s" repeatCount="indefinite" />
</Rect>
```

Does this lib support this tag (`animate`)?

**Comment by bohdanprog** [comment]
Hello @psnet,
Unfortunately, we don't support that tag, maybe in the future we will add that feature but now we haven't.
