### ISSUE TITLE
Is it possible to use FastImage to clip path ?

### ISSUE THREAD

**Issue by mehthabux** [software-mansion/react-native-svg#1665]
i want to use fastimage inside svg. I need to mask an image inside an svg shape. i know about the image component from react-native-svg. is it possible for me to you the fastimage instead ?

`<Svg
      xmlns="http://www.w3.org/2000/svg"
      width={'100%'}
      height={70}
      viewBox="0 0 801 504"
      {...props}>
      <ClipPath id="clip">
        <G id="Vector 1">
          <Path
            id="Vector 1_2"
            d="M800 1H1V474C425 539 800 474 800 474V1Z"
            fill="rgba(0,0,0,0.2)"
          />
        </G>
      </ClipPath>
      <Image
        x="0%"
        y="0%"
        width="100%"
        height="100%"
        preserveAspectRatio="xMidYMid slice"
        href={props?.source}
        clipPath="url(#clip)"
      />
    </Svg>
  );`

Please let me know 
thanks

**Comment by Wicat21** [comment]
Same here, did you found a solution?

**Comment by GrimDev** [comment]
Same here, even the React Native Image component could suit me in fact

**Comment by brahimmouhamou** [comment]
Any news on this. Which workaround did you apply?

**Comment by Wicat21** [comment]
I used the Image component from react-native-svg. 
I had a gallery with FastImages, and if you select one, I download the image to the phone (so the react-native-svg Image component is good), and you can edit that. Also I reduced the sizes of the images.
