### ISSUE TITLE
is it possible to change svg color using svguri

### ISSUE THREAD

**Issue by kimsean** [software-mansion/react-native-svg#1667]
Hi, i would like to ask if its possible to change the svg color using the svguri here is my code

`import { SvgUri } from 'react-native-svg'
<SvgUri
       width="24"
       height="24"
        uri="https://thenewcode.com/assets/images/thumbnails/homer-simpson.svg"
 />`

**Comment by WoLewicki** [comment]
I believe it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1667, so I will close this issue to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.

**Comment by WoLewicki** [comment]
Ups 😅 Do you have an idea where should it have lead to?

**Comment by ricbermo** [comment]
@WoLewicki probably [this](https://github.com/software-mansion/react-native-svg/issues/1317#issuecomment-861498269)
