### ISSUE TITLE
PanGestureHandler and react-native-svg: Class example works, but hooks example doesn't

### ISSUE THREAD

**Issue by hugows** [software-mansion/react-native-svg#1672]
Hello all,

the examples that @msand provided [here](https://github.com/react-native-svg/react-native-svg/issues/1064) in 2019 are gold - thanks very much for those.

**But** its interesting that [only the class version works for me:](https://github.com/react-native-svg/react-native-svg/issues/1064#issuecomment-518028920) - as soon as I move to the [hooks version](https://github.com/react-native-svg/react-native-svg/issues/1064#issuecomment-518225872) it doesn't work anymore. Nothing else changed.

I had not written a class component for a few years now so that is very surprising to me. I cannot see the issue.

**Any** idea why something like that would happen? The code is very, very similar. 

I can use the class-based version now but would love to understand what is going on here.

Thank you in advance!

**Comment by bohdanprog** [comment]
Hello @hugows,
can you provide an example of how you try to do that?
Thank you
