### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Svg which is inside StrictMode.

### ISSUE THREAD

**Issue by dogunbound** [software-mansion/react-native-svg#1673]
Fix:
https://stackoverflow.com/a/63603903/5676613

I just don't want this amazing library to die because react won't support findDomNode.

The workaround for users who want to use react-native-svg is just to not use strict mode in your index.js.
If you do, just ignore the warning.

**Comment by bohdanprog** [comment]
I believe that particular issue is not relevant. However, if you encounter any further problems with `react-native-svg`, please feel free to open a new issue.

Thank you.
