### ISSUE TITLE
setNativeProps is not implemented on web, animating svg properties via reanimated is not possible

### ISSUE THREAD

**Issue by DrRefactor** [software-mansion/react-native-svg#1674]
# Bug

Reanimated.createAnimatedComponent requires .setNativeProps to be implemented to animate attributes like `Path.strokeDashoffset`

## Environment info

Library version: 12.1.0

## Steps To Reproduce

Use following code in newest reanimated (2.3.0 currently) and react-native-svg, run on web.

```
const AnimatedPath = Animated.createAnimatedComponent(Path);
(...)

const progress = useSharedValue(0);
useEffect(() => {
  progress.value = withRepeat(withTiming(1, {duration: 1500, easing: Easing.linear}), -1, true);
}, []);
const animatedProps = useAnimatedProps(() => {
  const offset = interpolate(progress.value, [0, 1], [0, MAX_OFFSET], Extrapolate.CLAMP);
  return {strokeDashoffset: offset};
});

return <AnimatedPath animatedProps={animatedProps} />;
```

Describe what you expected to happen:

Animate properly, like it does on iOS, Android

**Comment by mBarlescu** [comment]
> # Bug
> Reanimated.createAnimatedComponent requires .setNativeProps to be implemented to animate attributes like `Path.strokeDashoffset`
> 
> ## Environment info
> Library version: 12.1.0
> 
> ## Steps To Reproduce
> Use following code in newest reanimated (2.3.0 currently) and react-native-svg, run on web.
> 
> ```
> const AnimatedPath = Animated.createAnimatedComponent(Path);
> (...)
> 
> const progress = useSharedValue(0);
> useEffect(() => {
>   progress.value = withRepeat(withTiming(1, {duration: 1500, easing: Easing.linear}), -1, true);
> }, []);
> const animatedProps = useAnimatedProps(() => {
>   const offset = interpolate(progress.value, [0, 1], [0, MAX_OFFSET], Extrapolate.CLAMP);
>   return {strokeDashoffset: offset};
> });
> 
> return <AnimatedPath animatedProps={animatedProps} />;
> ```
> 
> Describe what you expected to happen:
> 
> Animate properly, like it does on iOS, Android

this issue seems to still exist

**Comment by mBarlescu** [comment]
> # Bug
> Reanimated.createAnimatedComponent requires .setNativeProps to be implemented to animate attributes like `Path.strokeDashoffset`
> 
> ## Environment info
> Library version: 12.1.0
> 
> ## Steps To Reproduce
> Use following code in newest reanimated (2.3.0 currently) and react-native-svg, run on web.
> 
> ```
> const AnimatedPath = Animated.createAnimatedComponent(Path);
> (...)
> 
> const progress = useSharedValue(0);
> useEffect(() => {
>   progress.value = withRepeat(withTiming(1, {duration: 1500, easing: Easing.linear}), -1, true);
> }, []);
> const animatedProps = useAnimatedProps(() => {
>   const offset = interpolate(progress.value, [0, 1], [0, MAX_OFFSET], Extrapolate.CLAMP);
>   return {strokeDashoffset: offset};
> });
> 
> return <AnimatedPath animatedProps={animatedProps} />;
> ```
> 
> Describe what you expected to happen:
> 
> Animate properly, like it does on iOS, Android

did you find a proper solution?

**Comment by DrRefactor** [comment]
Unfortunately not.
I created dedicated animations for web, based on css.

**Comment by bohdanprog** [comment]
Hello @DrRefactor,
Are you still experiencing that issue?
Please provide an example with all environments. It would help us to understand the problem.
Thank you
