### ISSUE TITLE
How to dynamically set gradient fill in svg

### ISSUE THREAD

**Issue by jrhager84** [software-mansion/react-native-svg#1676]
# Question

I've got react-native-svg set up with react-native-svg-transformer and it all works as intended. However, there is a bug(?) or issue as it relates to setting the gradient fill in the svgs. I'm not sure how to do it, but I've tried many things. The color and fill props work as a solid fill on the svg, but I can't target the linearGradient inside the svg outside of the svg. I'll show some code to illustrate my point:

```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="0 0 26 26" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient gradientUnits="userSpaceOnUse" x1="12.99" y1="0" x2="12.99" y2="25.92" id="gradient" gradientTransform="matrix(0.707053, -0.707161, 1.001161, 1.001008, -9.106794, 9.237734)">
      <stop offset="0" style="stop-color: rgb(161, 70, 183);"/>
      <stop offset="1" style="stop-color: rgb(0, 38, 94);"/>
    </linearGradient>
  </defs>
  <path d="M13.91.38a1.3 1.3 0 0 0-1.84 0L.33 12.14c-.4.4-.35.73-.29.89.06.16.25.44.8.44h1.32v10.45a2 2 0 0 0 1.92 2h5.95v-7.08h5.76v7.08h6.1c1.03 0 1.9-.93 1.9-2V13.47h1.36c.54 0 .73-.28.79-.44.06-.16.1-.5-.28-.9L13.9.39Z" fill-rule="evenodd" fill="currentColor" />
</svg>
```

Ideally, I'd rather just set the linearGradient *outside* of the svg somehow, but the documentation doesn't really make it clear if that is possible. If I can't do it externally, I'd at least like to be able to target the id of the linearGradient within the svg (usually you do `fill="url(#gradient)"`). Is there a way to accomplish this? Thanks!

**Comment by BarbWire-1** [comment]
Did you find a way to address the defs-settings? I'm actually fighting with the same issue 😅

**Comment by TaiwoJazz** [comment]
I'm having this same problem

**Comment by WoLewicki** [comment]
What is the exact issue here? You can use `id` prop similar to how it is done on web to use the `linearGradient` in your other components, e.g.: 
```
<?xml version="1.0" encoding="utf-8"?>
<svg viewBox="0 0 26 26" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad" gradientUnits="userSpaceOnUse" x1="12.99" y1="0" x2="12.99" y2="25.92" id="gradient" gradientTransform="matrix(0.707053, -0.707161, 1.001161, 1.001008, -9.106794, 9.237734)">
      <stop offset="0" style="stop-color: rgb(161, 70, 183);"/>
      <stop offset="1" style="stop-color: rgb(0, 38, 94);"/>
    </linearGradient>
  </defs>
  <path d="M13.91.38a1.3 1.3 0 0 0-1.84 0L.33 12.14c-.4.4-.35.73-.29.89.06.16.25.44.8.44h1.32v10.45a2 2 0 0 0 1.92 2h5.95v-7.08h5.76v7.08h6.1c1.03 0 1.9-.93 1.9-2V13.47h1.36c.54 0 .73-.28.79-.44.06-.16.1-.5-.28-.9L13.9.39Z" fill-rule="evenodd" fill="url(#grad)" />
</svg>
```
Am I missing something?
