### ISSUE TITLE
dont support animateMotion tag ? how i to use ?

### ISSUE THREAD

**Issue by ZhangCoder0812** [software-mansion/react-native-svg#1681]
# Question

Before submitting it, please ensure that this was not already asked in another issue, or on StackOverflow. Ideally, you should always refer to StackOverflow first.

This issue should serve for you to ask a question about the library to the maintainers and other fellow developers - remember that even if the issue gets closed, the conversation can move forward 🤗
Also, ideally this issue should culminate in a PR to the documentation for this library so that future developers will have that doubt cleared.

**Comment by WoLewicki** [comment]
I'm closing this issue due to not following the contributing guidelines mentioned in the template. Feel free to comment here if something is wrong and we can always reopen it then.
