### ISSUE TITLE
Could not compile build file no matter what 

### ISSUE THREAD

**Issue by bsor-dev** [software-mansion/react-native-svg#1688]
React native version 0.66.4
"react-native-svg": "^12.1.1",

I can't run my app in android if react-native-svg is installed. I tried different versions but still same. How to fix this?

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Mobiles\petshop\node_modules\react-native-svg\android\build.gradle'

* What went wrong:
Could not compile build file 'D:\Mobiles\petshop\node_modules\react-native-svg\android\build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61
```

**Comment by bohdanprog** [comment]
Hello @bsor-dev,
That issue may not be relevant.
But if you still have some issues with `react-native-svg `feel free to open the new issue.
Thank you.
