### ISSUE TITLE
Reference element by URL from a different SVG

### ISSUE THREAD

**Issue by vydimitrov** [software-mansion/react-native-svg#1694]
# Reference element by URL from a different SVG

In the Web SVG it is possible to reference an SVG element by URL from one SVG wrapper to other SVG wrapper. But it seems this not possible with `react-native-svg`. Is this a bug or by design it is not possible? 

```jsx
<Svg height="150" width="300">
  <Defs>
    <LinearGradient id="grad" x1="0" y1="0" x2="1" y2="0">
      <Stop offset="0" stopColor="#FFD080" stopOpacity="1" />
      <Stop offset="1" stopColor="red" stopOpacity="1" />
    </LinearGradient>
  </Defs>
</Svg>
<Svg height="150" width="300">
  <Ellipse cx="150" cy="75" rx="85" ry="55" fill="url(#grad)" />
</Svg>
```
Demo to reproduce the issue: https://snack.expo.dev/@dimitrov/react-native-svg-gradient

**Comment by bohdanprog** [comment]
Hello @vydimitrov,
you can do that in this way:
```
