### ISSUE TITLE
Simple Svg works on iOS but not on Android

### ISSUE THREAD

**Issue by charity-detalytics** [software-mansion/react-native-svg#1696]
# Bug

Simple Svg works on iOS but not on Android
<img width="570" alt="Screen Shot 2022-02-19 at 16 04 44" src="https://user-images.githubusercontent.com/63986409/154794383-a6fa762b-16d3-4a98-a189-c2404a8f4773.png">

## Steps To Reproduce

I have just created this new and simple repo for reproducing the issue:
https://github.com/charity-detalytics/SrgErr

```js
import React from 'react';
import type {Node} from 'react';
import {
  View,
} from 'react-native';
import X from './x.svg'

const App: () => Node = () => {
  return (
    <View>
      <X/>
    </View>
  );
};

export default App;
```

```svg
<svg width="100%" height="100%" viewBox="0 0 325 432">
  <mask id="id" x="143" y="278" width="182" height="69">
    <path d="M143.867 278.211H325V346.467H143.867V278.211Z" fill="white"/>
  </mask>
  <g mask="url(#id)">
    <path d="M167.267 323.524L487.933 264.391L818.133 323.524" stroke="red" stroke-width="13"/>
  </g>
</svg>

```

Describe what you expected to happen:
Please see the screen shot above!

**Comment by Cnilton** [comment]
Hi guys, I could reproduce this issue either. When there is more than one item together with masks in the svg, it cuts the image on android:

<img width="183" alt="Captura de Tela 2022-02-25 às 12 44 33" src="https://user-images.githubusercontent.com/40298250/155744419-eda24c80-9fac-4b64-85b9-40210469204c.png">

**Comment by bohdanprog** [comment]
Hello @charity-detalytics,
I tried to reproduce your issue but couldn't.
Do you still have that problem?
