### ISSUE TITLE
onPress is not working in some Paths of SVG?

### ISSUE THREAD

**Issue by Nadeem-Ashraf007** [software-mansion/react-native-svg#1710]
onPress is not working in some Paths of SVG? But when I change the emulator then it's working but not on all SVG. This means its works on different Paths of SVG when different emulators, in some emulators it works only first half and in others, it works more than half.
![image](https://user-images.githubusercontent.com/77587999/155832301-733e487a-0366-4b30-8ae8-8d8cbafebd19.png)
in this picture, onPress is not working for the center bottom and left-right car but works only for the top car. anyone helps me how I resolve this problem.

my code ViewBox looks like this. any best practices for using viewBox in react native app

 <Svg
      role="img"
        width="100%"
        height="100%"
        // iewBox="0 0 300 300"
        preserveAspectRatio="xMinYMin meet"
        viewBox={`0 0 ${originalWidth} ${originalHeight}`}>
      
    @yangyi @yangyi @kant @op @ @ericanderson @msand @Metroxe @terribleben

**Comment by bohdanprog** [comment]
Hello @Nadeem-Ashraf007,
If you still have that problem, please provide a simple repro.
thank you
