### ISSUE TITLE
Can not display svg image

### ISSUE THREAD

**Issue by thanhdatpd** [software-mansion/react-native-svg#1722]
# Bug
Can not display [this svg](https://gist.github.com/thanhdatpd/d4b55a9917f4d1b63a5ffa39e5c27651) image using SvgXml

#### Unexpected behavior

Image not render

## Environment info

```bash
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.07 GB / 7.43 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: Not Found
  Languages:
    Java: 11.0.13 - /c/Program Files/Common Files/Oracle/Java/javapath/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.3.0

## Steps To Reproduce

Using SvgXml or any kind to display this image  [this svg](https://gist.github.com/thanhdatpd/d4b55a9917f4d1b63a5ffa39e5c27651) 

Describe what you expected to happen:

1. Show image as normal

**Comment by gremlin529** [comment]
I tried to create a code sandbox of this, and indeed of the example of just loading and it failed, in a way I can't really understand. https://codesandbox.io/s/mystifying-leakey-mktzzc?file=/src/App.tsx
