### ISSUE TITLE
best practice to load local images

### ISSUE THREAD

**Issue by aknad** [software-mansion/react-native-svg#1728]
# Question

I can't understand what's the best way to load local images

the [documentation](https://github.com/react-native-svg/react-native-svg#use-with-svg-files) suggests to use [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer)

In this [issue](https://github.com/react-native-svg/react-native-svg/issues/1306#issuecomment-686420284) I found the _WithLocalSvg_ component but it's not officially documented

Also, in the [latest comment](https://github.com/react-native-svg/react-native-svg/issues/1306#issuecomment-990196006) of that issue there's another implementation suggestion

Which one should I use?
Thanks

**Comment by olessavluk** [comment]
As I have understood from reading the issue you have referenced, the best practice is to:
 - use [transformer as suggested](https://github.com/react-native-svg/react-native-svg#use-with-svg-files)
 - if for some reason you are unable to use the transformer, `LocalSvg` could work, but with possibly of worse performance
 
 
From the [author comment](https://github.com/react-native-svg/react-native-svg/issues/1306#issuecomment-596299536):
> i'd still prioritise both battery energy and render time / user perceived latency by using the transformer approach, it'll quite certainly give wider budgets and thus handle more complex content with acceptable performance, especially on low-end devices, or when low on resources in general.

**Comment by bohdanprog** [comment]
Hello @aknad,
As @olessavluk mentioned, the optimal method is to utilize [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer). If you have any further questions, please don't hesitate to open a new issue for discussion.

Thank you.
