### ISSUE TITLE
error: cannot find symbol

### ISSUE THREAD

**Issue by trinadhkoya** [software-mansion/react-native-svg#1732]
```
import com.facebook.react.bridge.ColorPropConverter;
                                ^
  symbol:   class ColorPropConverter
  location: package com.facebook.react.bridge
```

   OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 41.12 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
    Watchman: 2021.12.13.00 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by lylysunshinee** [comment]
follow up

**Comment by njacob1001** [comment]
same issue here

**Comment by vadherjitu** [comment]
same isssue bro

**Comment by nivetha12101997** [comment]
Same issue

**Comment by vanso-hubsi** [comment]
The issue seems to come with the latest version of react-native-svg 12.3.0, this change: #1705.

As it seems the missing class `ColorPropConverter` comes with ReactNative 0.63. So, from 12.3.0 on react-native-svg requires RN 0.63 or newer.
I was able to fix it for me by downgrading to 12.2.0.

I think this new requirement should be added to the release notes and adjusted in `package.json`.

**Comment by lylysunshinee** [comment]
> The issue seems to come with the latest version of react-native-svg 12.3.0, this change: #1705.
> 
> As it seems the missing class `ColorPropConverter` comes with ReactNative 0.63. So, from 12.3.0 on react-native-svg requires RN 0.63 or newer. I was able to fix it for me by downgrading to 12.2.0.
> 
> I think this new requirement should be added to the release notes and adjusted in `package.json`.
Thank you so much @vanso-hubsi 
downgrading to 12.2.0    ->  "react-native-svg": "12.2.0",
everything  "Work like a charm" 💯

**Comment by thatCbin** [comment]
> 这个问题似乎与最新版本的react-native-svg 12.3.0有关，此更改：#1705。
> 
> 因为似乎缺少的类带有ReactNative 0.63。因此，从 12.3.0 开始，react-native-svg 需要 RN 0.63 或更高版本。我能够通过降级到12.2.0来为我修复它。`ColorPropConverter`
> 
> 我认为这个新要求应该添加到发行说明中，并在 中进行调整。`package.json`

同样的兄弟, 0.59 版本

**Comment by cnhuz** [comment]
> The issue seems to come with the latest version of react-native-svg 12.3.0, this change: #1705.
> 
> As it seems the missing class `ColorPropConverter` comes with ReactNative 0.63. So, from 12.3.0 on react-native-svg requires RN 0.63 or newer. I was able to fix it for me by downgrading to 12.2.0.
> 
> I think this new requirement should be added to the release notes and adjusted in `package.json`.

It is working, I also downgrading react-native@6.8.2 back to react-native@0.62.2

**Comment by minhdangoz** [comment]
yarn add react-native-svg@12.1.0
solve my problem

**Comment by aryalsujay** [comment]
Neither react-native-svg 12.2.0/12.1.0 is working...
Anyone find the solution, pls share
Thanks

**Comment by paladhamma** [comment]
This is a major issue, please look into it.
Please share if you find the solution to this.

**Comment by bohdanprog** [comment]
Hello @trinadhkoya,
Do you still have that issue?
If you still have that issue, please provide a simple example to reproduce that.
Thank you.

**Comment by aryalsujay** [comment]
The issue is still there.

**Comment by bohdanprog** [comment]
@aryalsujay Could you provide an example of how we can reproduce that?
Thank you.

**Comment by aryalsujay** [comment]
Same as how @trinadhkoya has commented.
