### ISSUE TITLE
OnPress event on G is not working.

### ISSUE THREAD

**Issue by shivika24** [software-mansion/react-native-svg#1746]
OnPress event on G is not working. Even i tried to have a circle inside G still doesn't works.

<G onPress={onPress}>
  <Circle />
</G>

**Comment by markzhang-abbott** [comment]
onPressOut is working but not onPress on Android real devices.

**Comment by bohdanprog** [comment]
Hello @shivika24  @summerlove57  @markzhang-abbott,
Can you share a simple repro for that problem?
Because I tried to reproduce that but couldn't.
Thank you.
