### ISSUE TITLE
SvgUri not handling style property for svg element correctly

### ISSUE THREAD

**Issue by ghost** [software-mansion/react-native-svg#1770]
# Bug

Using `<SvgUri />` component and passing it a uri of an svg that has a style property in the `<svg>` element that specifies border-radius in percentages
`<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512" style="border-radius:50%">`
causes an error of:
```
Error while updating property 'borderRadius' of a view managed by: RNSVGSvgView
java.lang.String cannot be cast to java.lang.Double
```

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
yarn run v1.22.18
$ /Users/teemurytsola/Documents/random/SvgUriError/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.56 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/kl/d95vrzxd0ln68_9sg6q3582m0000gn/T/yarn--1652728664565-0.19948751534863773/node
    Yarn: 1.22.18 - /var/folders/kl/d95vrzxd0ln68_9sg6q3582m0000gn/T/yarn--1652728664565-0.19948751534863773/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2021.11.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs ARM 64 v8a, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Users/teemurytsola/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
Done in 1.49s.
```

Library version: 12.3.0

## Steps To Reproduce

Readme of example [Example repo](https://github.com/teeryt/svg-uri-bug).

1. Use <SvgUri /> component, 
2. Pass uri of an svg that has a property `style="border-radius:50%"` to component ([for example](https://hatscripts.github.io/circle-flags/flags/gb.svg))
2. Error occurs when trying to render the svg

Describe what you expected to happen:
1. <SvgUri /> correctly handles the style property of `svg` element in the svg uri

## Short, Self Contained, Correct (Compilable), Example

[Example](https://github.com/teeryt/svg-uri-bug)

**Comment by bohdanprog** [comment]
Hello,
I tried to reproduce that issue, but couldn't.
If you still have that problem, feel free to open a new issue.

Thank you

**Comment by PrimulaX** [comment]
I have basically the same issue. When SVG contains a double value, I'm getting: `java.lang.Double cannot be cast to java.lang.Integer`

**Comment by PrimulaX** [comment]
So problem was using `style` prop on SvgUri itself, I had this style: 

```javascript
secondaryIcon: {
	position: "absolute",
	top: 12,
	left: 12,
	outlineColor: theme.colors.white,
	outlineWidth: 1.5,
	borderRadius: theme.radius.xxs,
},
```

then i just wrap the SvgUri and now works: 
```javascript
<View style={styles.secondaryIcon}>
     <SvgUri width={20} height={20} uri={secondaryIconUri} />
</View>
```
