### ISSUE TITLE
deprecated_flat_project_structure warning and depreciation error when building with Gradle 8

### ISSUE THREAD

**Issue by brett-james-rocketlab** [software-mansion/react-native-svg#1771]
# Question

With a fresh install, the error here occurs:
(clean is a faster way to see warnings than build)
./gradlew clean --warning-mode all
`> Configure project :react-native-vector-icons
Subproject ':react-native-vector-icons' has location '/Users/brett/development/adultmatchmaker/node_modules/react-native-vector-icons/android' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.3.3/userguide/upgrading_version_7.html#deprecated_flat_project_structure`

**Comment by bohdanprog** [comment]
Hello @brett-james-rocketlab ,
I believe the issue has already been resolved. If you are still experiencing problems, please feel free to open a new one.

Thank you.
