### ISSUE TITLE
SvgXml, SvgUri

### ISSUE THREAD

**Issue by ger0m0** [software-mansion/react-native-svg#1772]
SvgXml, SvgUri - faced with the fact that these components do not work out of the box. I have been looking for a solution for 3 days, I found that periodically people also have a problem and there is no clear answer to it.
one of the topics: https://github.com/react-native-svg/react-native-svg/issues/1121

please make a working code and a link in expo. Still haven't solved the problem so I hope you will do so

**Comment by ger0m0** [comment]
in continuation of the topic, I went through the code. I found out that in **node_modules\react-native-svg\src\xml.tsx** there is a problem with imports
solution: copy the file to your project, import {Svg Url} and replace the imports
`// import Rect from 'react-native-svg/src/elements/Rect';
// import Circle from 'react-native-svg/src/elements/Circle';
// import Ellipse from 'react-native-svg/src/elements/Ellipse';
// import Polygon from 'react-native-svg/src/elements/Polygon';
// import Polyline from 'react-native-svg/src/elements/Polyline';
// import Line from 'react-native-svg/src/elements/Line';
// import Svg from 'react-native-svg/src/elements/Svg';
// import Path from 'react-native-svg/src/elements/Path';
// import G from 'react-native-svg/src/elements/G';
// import Text from 'react-native-svg/src/elements/Text';
// import TSpan from 'react-native-svg/src/elements/TSpan';
// import TextPath from 'react-native-svg/src/elements/TextPath';
// import Use from 'react-native-svg/src/elements/Use';
// import Image from 'react-native-svg/src/elements/Image';
// import Symbol from 'react-native-svg/src/elements/Symbol';
// import Defs from 'react-native-svg/src/elements/Defs';
// import LinearGradient from 'react-native-svg/src/elements/LinearGradient';
// import RadialGradient from 'react-native-svg/src/elements/RadialGradient';
// import Stop from 'react-native-svg/src/elements/Stop';
// import ClipPath from 'react-native-svg/src/elements/ClipPath';
// import Pattern from 'react-native-svg/src/elements/Pattern';
// import Mask from 'react-native-svg/src/elements/Mask';
// import Marker from 'react-native-svg/src/elements/Marker';

import {
  Rect,
  Circle,
  Ellipse,
  Polygon,
  Polyline,
  Line,
  Svg,
  Path,
  G,
  Text,
  TSpan,
  TextPath,
  Use,
  Image,
  Symbol,
  Defs,
  LinearGradient,
  RadialGradient,
  Stop,
  ClipPath,
  Pattern,
  Mask,
  Marker
} from 'react-native-svg';`

I hope it will be fixed in the future

**Comment by JWesorick** [comment]
For me, and anyone else who ends up here, it looks like SvgUri only is for ios/android and is not exported for web.

**Comment by WoLewicki** [comment]
The problem with using `SvgXml` etc. on web is described here: https://github.com/software-mansion/react-native-svg/issues/1279. I will close this issue to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.
