### ISSUE TITLE
Text Component crashes

### ISSUE THREAD

**Issue by sepehrni** [software-mansion/react-native-svg#1788]
hi,Text Component crashes without any error on react native cli:

```
        <Svg height="60" width="200">
  <Text
    fill="none"
    stroke="purple"
    fontSize="20"
    fontWeight="bold"
    x="100"
    y="20"
    textAnchor="middle"
  >
    STROKED TEXT
  </Text>
</Svg>
```

**Comment by taduyde** [comment]
the same issue on android when build release

**Comment by bohdanprog** [comment]
Hello @sepehrni @taduyde,
I tried to reproduce that problem but couldn't.
If you still have that problem, feel free to open a new issue.
Thank you.
