### ISSUE TITLE
"mask-type" is not supported in <mask> element.

### ISSUE THREAD

**Issue by MuthupandiG** [software-mansion/react-native-svg#1790]
The problem is explained here very well.  https://github.com/gregberge/svgr/issues/336

The same should be addressed in this library as well.

**Comment by MohammadKurjieh** [comment]
Any updates on this issue?

**Comment by MuthupandiG** [comment]
> Any updates on this issue?

Seems, they have fixed it in v0.32.0

resvg supports the mask-type attribute as of v0.32.0. RazrFalcon/resvg#582

**Comment by mdj-goathamster** [comment]
Need this!

**Comment by MuthupandiG** [comment]
Upgrade to the version v0.32.0

**Comment by MuthupandiG** [comment]
Refer this https://github.com/RazrFalcon/resvg/issues/582

**Comment by mdj-goathamster** [comment]
> Refer this [RazrFalcon/resvg#582](https://github.com/RazrFalcon/resvg/issues/582)

Maybe i'm silly, but i don't see how that is relevant in this post.

Status is, still, that react-native-svg doesn't support mask-type/maskType, right?

**Comment by jm-masteos** [comment]
Up! Still no update on that ?
I'm using svgr/cli to generate my Icons components from .svg files and some of them are genrated with a <Mask> component with style property. Which is not handled by react-native-svg in the latest version

**Comment by eljonathas** [comment]
> Up! Still no update on that ? I'm using svgr/cli to generate my Icons components from .svg files and some of them are genrated with a component with style property. Which is not handled by react-native-svg in the latest version

the same here

**Comment by JacobWennebro** [comment]
Having this same issue

**Comment by SaadAhmadSaddiqui** [comment]
Facing this issue right now.

**Comment by kartikeyvaish** [comment]
Any Updates?

**Comment by bohdanprog** [comment]
Hello,
Can someone provide a simple example to reproduce that problem?
Thank you.

**Comment by jakex7** [comment]
Hi,
this issue has been resolved in #2152 and will be release in the next version!
Thanks 🚀
