### ISSUE TITLE
SVG files which work in Web Applications are not rendering using react-native-svg.

### ISSUE THREAD

**Issue by xtl-geiger** [software-mansion/react-native-svg#1791]
# Bug

Some SVGs which work fine in Web are not compatible with react-native-svg.
![Screenshot_1655380176](https://user-images.githubusercontent.com/35232135/174076105-d9260b3e-5e7f-4cef-a0fe-a6fb191f0fe9.png)

How can I filter out the tags in my SVGs just as https://www.svgviewer.dev/ is doing but in react-native?
I do not know the content of the SVGs in advance.
Which tags are not supported by react-native-svg? Or more so which normal svg/XML tags are supported? Is there a complete list?

## Environment info

React native info output:

```bash
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
    Memory: 1.40 GB / 31.27 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.12.0 - ~/.nvm/versions/node/v16.12.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.12.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.12.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 12.3.0

## Steps To Reproduce

1. git clone https://github.com/xtl-geiger/svgIssueExample
2. cd svgIssueExample
3. npm i
4. etc.

Describe what you expected to happen:

1.The SVG file to render correctly.

**Comment by NilsBaumgartner1994** [comment]
Having the same (with different file) problem.

**Comment by Jekkt** [comment]
same

**Comment by Geccles** [comment]
I'm not seeing svg's load as well in web and I'm not able to to rend SvgUri or SvgXml, they come back undefined.

**Comment by willykurmann** [comment]
Same

**Comment by bohdanprog** [comment]
Hello @xtl-geiger,
Thank you for sharing the example application. Upon review, I came across the observation that it's not possible to specify width and height using percentages.
Can you try to do that again?
I recommend updating the `rn-svg library`.
