### ISSUE TITLE
The component SvgCss is not working

### ISSUE THREAD

**Issue by tommasini** [software-mansion/react-native-svg#1794]
# Bug
SvgCss is not working!

SVG:
`<svg id="svg" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMinYMin meet" viewBox="0 0 24 24"> <g><animate id='a' attributeName='display' values='inline;none;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c18' x='9' y='14'></rect><rect class='c18' x='10' y='14'></rect><rect class='c18' x='11' y='14'></rect><rect class='c18' x='12' y='14'></rect><rect class='c18' x='13' y='14'></rect><rect class='c18' x='14' y='14'></rect><rect class='c18' x='15' y='14'></rect><rect class='c18' x='10' y='15'></rect><rect class='c18' x='11' y='15'></rect><rect class='c18' x='12' y='15'></rect><rect class='c18' x='13' y='15'></rect><rect class='c18' x='14' y='15'></rect><rect class='c18' x='11' y='16'></rect><rect class='c18' x='12' y='16'></rect><rect class='c18' x='13' y='16'></rect></g><g><animate id='b' attributeName='display' values='none;inline;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c18' x='9' y='15'></rect><rect class='c18' x='10' y='15'></rect><rect class='c18' x='11' y='15'></rect><rect class='c18' x='12' y='15'></rect><rect class='c18' x='13' y='15'></rect><rect class='c18' x='14' y='15'></rect><rect class='c18' x='15' y='15'></rect><rect class='c18' x='10' y='16'></rect><rect class='c18' x='11' y='16'></rect><rect class='c18' x='12' y='16'></rect><rect class='c18' x='13' y='16'></rect><rect class='c18' x='14' y='16'></rect><rect class='c18' x='11' y='17'></rect><rect class='c18' x='12' y='17'></rect><rect class='c18' x='13' y='17'></rect></g><g><animate id='a' attributeName='display' values='inline;none;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c20' x='7' y='11'></rect><rect class='c20' x='8' y='11'></rect><rect class='c20' x='9' y='11'></rect><rect class='c20' x='10' y='11'></rect><rect class='c20' x='11' y='11'></rect><rect class='c20' x='12' y='11'></rect><rect class='c20' x='13' y='11'></rect><rect class='c20' x='14' y='11'></rect><rect class='c20' x='15' y='11'></rect><rect class='c20' x='9' y='12'></rect><rect class='c17' x='10' y='12'></rect><rect class='c17' x='11' y='12'></rect><rect class='c20' x='12' y='12'></rect><rect class='c27' x='13' y='12'></rect><rect class='c27' x='14' y='12'></rect><rect class='c20' x='15' y='12'></rect><rect class='c20' x='9' y='13'></rect><rect class='c20' x='10' y='13'></rect><rect class='c20' x='11' y='13'></rect><rect class='c20' x='12' y='13'></rect><rect class='c20' x='13' y='13'></rect><rect class='c20' x='14' y='13'></rect><rect class='c20' x='15' y='13'></rect></g><g><animate id='b' attributeName='display' values='none;inline;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c20' x='7' y='12'></rect><rect class='c20' x='8' y='12'></rect><rect class='c20' x='9' y='12'></rect><rect class='c20' x='10' y='12'></rect><rect class='c20' x='11' y='12'></rect><rect class='c20' x='12' y='12'></rect><rect class='c20' x='13' y='12'></rect><rect class='c20' x='14' y='12'></rect><rect class='c20' x='15' y='12'></rect><rect class='c20' x='9' y='13'></rect><rect class='c17' x='10' y='13'></rect><rect class='c17' x='11' y='13'></rect><rect class='c20' x='12' y='13'></rect><rect class='c27' x='13' y='13'></rect><rect class='c27' x='14' y='13'></rect><rect class='c20' x='15' y='13'></rect><rect class='c20' x='9' y='14'></rect><rect class='c20' x='10' y='14'></rect><rect class='c20' x='11' y='14'></rect><rect class='c20' x='12' y='14'></rect><rect class='c20' x='13' y='14'></rect><rect class='c20' x='14' y='14'></rect><rect class='c20' x='15' y='14'></rect></g><g><animate id='a' attributeName='display' values='inline;none;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c00' x='8' y='17'></rect><rect class='c00' x='9' y='17'></rect><rect class='c00' x='10' y='17'></rect><rect class='c00' x='11' y='17'></rect><rect class='c00' x='12' y='17'></rect><rect class='c00' x='13' y='17'></rect><rect class='c00' x='14' y='17'></rect><rect class='c00' x='15' y='17'></rect><rect class='c00' x='16' y='17'></rect><rect class='c00' x='17' y='17'></rect><rect class='c00' x='8' y='18'></rect><rect class='c29' x='9' y='18'></rect><rect class='c26' x='10' y='18'></rect><rect class='c29' x='11' y='18'></rect><rect class='c26' x='12' y='18'></rect><rect class='c29' x='13' y='18'></rect><rect class='c26' x='14' y='18'></rect><rect class='c29' x='15' y='18'></rect><rect class='c26' x='16' y='18'></rect><rect class='c00' x='17' y='18'></rect><rect class='c00' x='8' y='19'></rect><rect class='c26' x='9' y='19'></rect><rect class='c29' x='10' y='19'></rect><rect class='c26' x='11' y='19'></rect><rect class='c29' x='12' y='19'></rect><rect class='c26' x='13' y='19'></rect><rect class='c29' x='14' y='19'></rect><rect class='c26' x='15' y='19'></rect><rect class='c29' x='16' y='19'></rect><rect class='c00' x='17' y='19'></rect><rect class='c00' x='8' y='20'></rect><rect class='c00' x='9' y='20'></rect><rect class='c00' x='10' y='20'></rect><rect class='c00' x='11' y='20'></rect><rect class='c00' x='12' y='20'></rect><rect class='c00' x='13' y='20'></rect><rect class='c00' x='14' y='20'></rect><rect class='c00' x='15' y='20'></rect><rect class='c00' x='16' y='20'></rect><rect class='c00' x='17' y='20'></rect></g><g><animate id='b' attributeName='display' values='none;inline;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c00' x='8' y='18'></rect><rect class='c00' x='9' y='18'></rect><rect class='c00' x='10' y='18'></rect><rect class='c00' x='11' y='18'></rect><rect class='c00' x='12' y='18'></rect><rect class='c00' x='13' y='18'></rect><rect class='c00' x='14' y='18'></rect><rect class='c00' x='15' y='18'></rect><rect class='c00' x='16' y='18'></rect><rect class='c00' x='17' y='18'></rect><rect class='c00' x='8' y='19'></rect><rect class='c29' x='9' y='19'></rect><rect class='c26' x='10' y='19'></rect><rect class='c29' x='11' y='19'></rect><rect class='c26' x='12' y='19'></rect><rect class='c29' x='13' y='19'></rect><rect class='c26' x='14' y='19'></rect><rect class='c29' x='15' y='19'></rect><rect class='c26' x='16' y='19'></rect><rect class='c00' x='17' y='19'></rect><rect class='c00' x='8' y='20'></rect><rect class='c26' x='9' y='20'></rect><rect class='c29' x='10' y='20'></rect><rect class='c26' x='11' y='20'></rect><rect class='c29' x='12' y='20'></rect><rect class='c26' x='13' y='20'></rect><rect class='c29' x='14' y='20'></rect><rect class='c26' x='15' y='20'></rect><rect class='c29' x='16' y='20'></rect><rect class='c00' x='17' y='20'></rect><rect class='c00' x='8' y='21'></rect><rect class='c00' x='9' y='21'></rect><rect class='c00' x='10' y='21'></rect><rect class='c00' x='11' y='21'></rect><rect class='c00' x='12' y='21'></rect><rect class='c00' x='13' y='21'></rect><rect class='c00' x='14' y='21'></rect><rect class='c00' x='15' y='21'></rect><rect class='c00' x='16' y='21'></rect><rect class='c00' x='17' y='21'></rect></g><g><animate id='a' attributeName='display' values='inline;none;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c00' x='10' y='6'></rect><rect class='c00' x='11' y='6'></rect><rect class='c00' x='12' y='6'></rect><rect class='c00' x='13' y='6'></rect><rect class='c00' x='9' y='7'></rect><rect class='c11' x='10' y='7'></rect><rect class='c11' x='11' y='7'></rect><rect class='c11' x='12' y='7'></rect><rect class='c11' x='13' y='7'></rect><rect class='c00' x='14' y='7'></rect><rect class='c00' x='14' y='8'></rect><rect class='c11' x='15' y='8'></rect><rect class='c11' x='16' y='8'></rect><rect class='c11' x='17' y='8'></rect><rect class='c11' x='18' y='8'></rect><rect class='c11' x='19' y='8'></rect><rect class='c11' x='20' y='8'></rect><rect class='c00' x='21' y='8'></rect><rect class='c00' x='7' y='9'></rect><rect class='c11' x='8' y='9'></rect><rect class='c11' x='9' y='9'></rect><rect class='c10' x='10' y='9'></rect><rect class='c10' x='11' y='9'></rect><rect class='c10' x='12' y='9'></rect><rect class='c10' x='13' y='9'></rect><rect class='c10' x='14' y='9'></rect><rect class='c11' x='15' y='9'></rect><rect class='c00' x='16' y='9'></rect><rect class='c00' x='7' y='10'></rect><rect class='c11' x='8' y='10'></rect><rect class='c10' x='9' y='10'></rect><rect class='c01' x='10' y='10'></rect><rect class='c01' x='11' y='10'></rect><rect class='c01' x='12' y='10'></rect><rect class='c01' x='13' y='10'></rect><rect class='c01' x='14' y='10'></rect><rect class='c10' x='15' y='10'></rect><rect class='c00' x='16' y='10'></rect><rect class='c00' x='16' y='11'></rect><rect class='c00' x='7' y='12'></rect><rect class='c11' x='8' y='12'></rect><rect class='c00' x='16' y='12'></rect><rect class='c00' x='7' y='13'></rect><rect class='c11' x='8' y='13'></rect><rect class='c00' x='16' y='13'></rect><rect class='c00' x='3' y='14'></rect><rect class='c10' x='4' y='14'></rect><rect class='c11' x='5' y='14'></rect><rect class='c10' x='6' y='14'></rect><rect class='c01' x='7' y='14'></rect><rect class='c01' x='8' y='14'></rect><rect class='c00' x='6' y='15'></rect><rect class='c11' x='7' y='15'></rect><rect class='c11' x='8' y='15'></rect><rect class='c11' x='9' y='15'></rect><rect class='c11' x='15' y='15'></rect><rect class='c00' x='16' y='15'></rect><rect class='c00' x='6' y='16'></rect><rect class='c11' x='7' y='16'></rect><rect class='c11' x='8' y='16'></rect><rect class='c11' x='9' y='16'></rect><rect class='c11' x='10' y='16'></rect><rect class='c11' x='14' y='16'></rect><rect class='c11' x='15' y='16'></rect><rect class='c00' x='16' y='16'></rect><rect class='c00' x='6' y='17'></rect><rect class='c10' x='7' y='17'></rect><rect class='c00' x='6' y='18'></rect><rect class='c10' x='7' y='18'></rect><rect class='c00' x='7' y='19'></rect><rect class='c00' x='4' y='21'></rect><rect class='c11' x='5' y='21'></rect><rect class='c11' x='6' y='21'></rect><rect class='c00' x='7' y='21'></rect><rect class='c00' x='8' y='21'></rect><rect class='c11' x='9' y='21'></rect><rect class='c11' x='10' y='21'></rect><rect class='c00' x='11' y='21'></rect><rect class='c00' x='8' y='22'></rect><rect class='c11' x='9' y='22'></rect><rect class='c11' x='10' y='22'></rect><rect class='c00' x='12' y='22'></rect><rect class='c11' x='13' y='22'></rect><rect class='c11' x='14' y='22'></rect><rect class='c00' x='15' y='22'></rect><rect class='c00' x='9' y='23'></rect><rect class='c00' x='10' y='23'></rect><rect class='c00' x='13' y='23'></rect><rect class='c00' x='14' y='23'></rect></g><g><animate id='b' attributeName='display' values='none;inline;' repeatCount='indefinite' dur='.45s' begin='0s'/><rect class='c00' x='8' y='4'></rect><rect class='c00' x='9' y='4'></rect><rect class='c00' x='11' y='4'></rect><rect class='c00' x='12' y='4'></rect><rect class='c00' x='15' y='4'></rect><rect class='c00' x='7' y='6'></rect><rect class='c11' x='8' y='6'></rect><rect class='c11' x='18' y='6'></rect><rect class='c11' x='19' y='6'></rect><rect class='c11' x='20' y='6'></rect><rect class='c00' x='6' y='7'></rect><rect class='c11' x='7' y='7'></rect><rect class='c11' x='8' y='7'></rect><rect class='c00' x='10' y='7'></rect><rect class='c00' x='11' y='7'></rect><rect class='c00' x='12' y='7'></rect><rect class='c00' x='13' y='7'></rect><rect class='c34' x='18' y='7'></rect><rect class='c11' x='19' y='7'></rect><rect class='c09' x='20' y='7'></rect><rect class='c00' x='3' y='8'></rect><rect class='c00' x='4' y='8'></rect><rect class='c00' x='5' y='8'></rect><rect class='c11' x='6' y='8'></rect><rect class='c11' x='7' y='8'></rect><rect class='c10' x='8' y='8'></rect><rect class='c11' x='11' y='8'></rect><rect class='c11' x='12' y='8'></rect><rect class='c11' x='13' y='8'></rect><rect class='c00' x='14' y='8'></rect><rect class='c34' x='18' y='8'></rect><rect class='c11' x='19' y='8'></rect><rect class='c11' x='20' y='8'></rect><rect class='c00' x='3' y='9'></rect><rect class='c00' x='4' y='9'></rect><rect class='c00' x='5' y='9'></rect><rect class='c00' x='8' y='9'></rect><rect class='c00' x='9' y='9'></rect><rect class='c00' x='10' y='9'></rect><rect class='c00' x='11' y='9'></rect><rect class='c00' x='12' y='9'></rect><rect class='c00' x='13' y='9'></rect><rect class='c11' x='14' y='9'></rect><rect class='c00' x='15' y='9'></rect><rect class='c00' x='8' y='10'></rect><rect class='c00' x='9' y='10'></rect><rect class='c00' x='10' y='10'></rect><rect class='c10' x='11' y='10'></rect><rect class='c10' x='12' y='10'></rect><rect class='c10' x='13' y='10'></rect><rect class='c10' x='14' y='10'></rect><rect class='c11' x='15' y='10'></rect><rect class='c00' x='16' y='10'></rect><rect class='c00' x='7' y='11'></rect><rect class='c00' x='8' y='11'></rect><rect class='c10' x='9' y='11'></rect><rect class='c01' x='10' y='11'></rect><rect class='c01' x='11' y='11'></rect><rect class='c01' x='12' y='11'></rect><rect class='c01' x='13' y='11'></rect><rect class='c01' x='14' y='11'></rect><rect class='c10' x='15' y='11'></rect><rect class='c00' x='16' y='11'></rect><rect class='c00' x='16' y='12'></rect><rect class='c00' x='7' y='13'></rect><rect class='c11' x='8' y='13'></rect><rect class='c00' x='16' y='13'></rect><rect class='c00' x='7' y='14'></rect><rect class='c11' x='8' y='14'></rect><rect class='c00' x='16' y='14'></rect><rect class='c00' x='6' y='15'></rect><rect class='c00' x='7' y='15'></rect><rect class='c11' x='8' y='15'></rect><rect class='c00' x='16' y='15'></rect><rect class='c00' x='6' y='16'></rect><rect class='c10' x='7' y='16'></rect><rect class='c11' x='8' y='16'></rect><rect class='c11' x='9' y='16'></rect><rect class='c11' x='15' y='16'></rect><rect class='c00' x='16' y='16'></rect><rect class='c00' x='6' y='17'></rect><rect class='c11' x='7' y='17'></rect><rect class='c11' x='8' y='17'></rect><rect class='c11' x='14' y='17'></rect><rect class='c11' x='15' y='17'></rect><rect class='c00' x='16' y='17'></rect><rect class='c00' x='6' y='18'></rect><rect class='c10' x='7' y='18'></rect><rect class='c00' x='6' y='19'></rect><rect class='c10' x='7' y='19'></rect><rect class='c00' x='7' y='20'></rect><rect class='c00' x='8' y='22'></rect><rect class='c11' x='9' y='22'></rect><rect class='c11' x='10' y='22'></rect><rect class='c00' x='12' y='22'></rect><rect class='c11' x='13' y='22'></rect><rect class='c11' x='14' y='22'></rect><rect class='c00' x='15' y='22'></rect><rect class='c00' x='9' y='23'></rect><rect class='c00' x='10' y='23'></rect><rect class='c00' x='13' y='23'></rect><rect class='c00' x='14' y='23'></rect></g><style>rect{width:1px;height:1px;}#svg{shape-rendering: crispedges;}.c00{fill:#000000}.c01{fill:#222034}.c02{fill:#45283c}.c03{fill:#663931}.c04{fill:#8f563b}.c05{fill:#df7126}.c06{fill:#d9a066}.c07{fill:#eec39a}.c08{fill:#fbf236}.c09{fill:#99e550}.c10{fill:#6abe30}.c11{fill:#37946e}.c12{fill:#4b692f}.c13{fill:#524b24}.c14{fill:#323c39}.c15{fill:#3f3f74}.c16{fill:#306082}.c17{fill:#5b6ee1}.c18{fill:#639bff}.c19{fill:#5fcde4}.c20{fill:#cbdbfc}.c21{fill:#ffffff}.c22{fill:#9badb7}.c23{fill:#847e87}.c24{fill:#696a6a}.c25{fill:#595652}.c26{fill:#76428a}.c27{fill:#ac3232}.c28{fill:#d95763}.c29{fill:#d77bba}.c30{fill:#8f974a}.c31{fill:#8a6f30}.c32{fill:#814848}.c33{fill:#9d4a4a}.c34{fill:#403640}.c35{fill:#868282}.c36{fill:#424058}.c37{fill:#2f315a}.c38{fill:#34378b}.c39{fill:#dcd530}.c40{fill:#fefff4}.c41{fill:#e3e1e1}.c42{fill:#634464}.c43{fill:#7d4881}.c44{fill:#b549bc}.c45{fill:#343cff}.c46{fill:#f6d953}.c47{fill:#bd8228}.c48{fill:#ebb337}</style></svg>`

Code: 
`return <SvgCss width={100} height={100} xml={dataImage} />`

Screenshot
![image](https://user-images.githubusercontent.com/46944231/176872265-6c42a1c0-204b-4252-8fb0-550a8333afe8.png)

#### Unexpected behavior
No SVG is showing

## Environment info
React-native-svg version: 12.1.1

System:
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3

**Comment by tommasini** [comment]
Update, version 12.4.0 not working as well
Neither SvgXml component

**Comment by WoLewicki** [comment]
I believe the problem mentioned here is the same as the one discussed in https://github.com/software-mansion/react-native-svg/issues/1019, which is that the library does not support `animate` props. I will close this issue then to keep the discussion in one place. Feel free to comment here if I am wrong and we can always reopen it then.

**Comment by tommasini** [comment]
@WoLewicki yes a very similar issue, the only thing I can notice the [#1019](https://github.com/software-mansion/react-native-svg/issues/1019) it's stale. There are no further plans to support the animate svg tag?

Thanks for the answer!
