### ISSUE TITLE
react-native-svg@12.3.0 error react-native run-android

### ISSUE THREAD

**Issue by luan-nvg** [software-mansion/react-native-svg#1799]
# Question

"react": "^18.0.0",
"react-native": "^0.69.1",
"react-native-svg": "^12.3.0",

react-native run-android erro:

`

> Task :react-native-svg:compileDebugShaders FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings
22 actionable tasks: 2 executed, 20 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':react-native-svg:compileDebugShaders' (type 'ShaderCompile').
  - Type 'ShaderCompile' property 'sourceDir' is annotated with @InputFiles but missing a normalization strategy.
    
    Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
    
    Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_normalization_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':react-native-svg:compileDebugShaders' (type 'ShaderCompile').
  - Type 'ShaderCompile' property 'sourceDir' is annotated with @InputFiles but missing a normalization strategy.
    
    Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
    
    Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_normalization_annotation for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

    at makeError (/app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/app/node_modules/@react-native-communi

`

**Comment by bohdanprog** [comment]
Hello @luan-nvg,
I suggest updating the library and starting fresh from the beginning. If the issue persists, please feel free to open a new problem report.

Thank you.
