### ISSUE TITLE
Can't build on windows "error Type 'Microsoft.Graphics.Canvas.Brushes.ICanvasBrush' could not be found" 

### ISSUE THREAD

**Issue by taduyde** [software-mansion/react-native-svg#1803]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug

Please provide a clear and concise description of what the bug is.
Include screenshots if needed.
Please test using the latest release of the library, as maybe said bug has been already fixed.

#### Unexpected behavior

If you have unexpected behavior, please create a clean project with the latest versions of react-native and react-native-svg

```bash
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..
modify App.js -> run the app
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

I got the error on windows, when run the application
 cppwinrt : error Type 'Microsoft.Graphics.Canvas.Brushes.ICanvasBrush' could not be found

"D:\ItArtists\ProAir\ProMobile\windows\packages\Microsoft.Windows.CppWinRT.2.0.210312.4\build\native\..\..\bin\"cppwinrt @"Debug\proair.vcxproj.cppwinrt_ref.rsp"
         cppwinrt : error Type 'Microsoft.Graphics.Canvas.Brushes.ICanvasBrush' could not be found
          method: Brush
          type: RNSVG.IBrushView
          database: D:\ItArtists\ProAir\ProMobile\windows\Debug\RNSVG\RNSVG.winmd
    10>D:\abc\Pro\appli\windows\packages\Microsoft.Windows.CppWinRT.2.0.210312.4\build\native\Microsoft.Windows.CppWinRT.targets(752,9): error MSB3073: The command ""D:\ItArtists\ProAir\ProMobile\windows\packages\Microsoft.
       Windows.CppWinRT.2.0.210312.4\build\native\..\..\bin\"cppwinrt @"Debug\proair.vcxproj.cppwinrt_ref.rsp"" exited with code 1. [D:\abc\Pro\appli\windows\proair\proair.vcxproj]

**Comment by creambyemute** [comment]
@marlenecota I'm running into the same issue. Do you have an idea what might cause this?

**Comment by taduyde** [comment]
Hi @creambyemute, I resolved this issue by install nuget package: 
https://www.nuget.org/packages/Microsoft.Graphics.Win2D/

**Comment by creambyemute** [comment]
@taduyde That does indeed work. But now I'm running into another Problem with the App/MainPage.xaml Files.
I'll stay on 12.3.0 and for now without windows support and check later when I upgraded React-Native as well as RN-Windows versions.

**Comment by Puyodead1** [comment]
Having the same issue, I tried upgrading to 1.26.0 of Win2D but got other issues about react-native-svg not being able to find 1.25.0. using react native 66.0

**Comment by nicoceledonc** [comment]
> Hi @creambyemute, I resolved this issue by install nuget package: https://www.nuget.org/packages/Microsoft.Graphics.Win2D/

Hi, which version of react-native, react-native-windows and react-native-svg are you using?

**Comment by 17Amir17** [comment]
I get the following error
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'auto winrt::impl::consume_Windows_Foundation_Collections_IVector<winrt::Windows::Foundation::Collections::IVector<winrt::Windows::UI::Xaml::UIElement>,T>::Append(const winrt::Windows::UI::Xaml::UIElement &) const': cannot convert argument 1 from 'winrt::Microsoft::Graphics::Canvas::UI::Xaml::CanvasControl' to 'const winrt::Windows::UI::Xaml::UIElement &'	RNSVG	C:\Users\dev\app\node_modules\react-native-svg\windows\RNSVG\SvgView.cpp	27	

```
