### ISSUE TITLE
cant compile react native windows

### ISSUE THREAD

**Issue by BienvenidoBoriko** [software-mansion/react-native-svg#1809]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is D:\gol-manager-2-prodJULIO\EMPTY\golmanager\windows\\packages\Microsoft.UI.Xaml.2.7.0\build\native\Microsoft.UI.Xaml.targets.	RNSVG	D:\gol-manager-2-prodJULIO\EMPTY\golmanager\node_modules\react-native-svg\windows\RNSVG\RNSVG.vcxproj	237

**Comment by thienphuoc** [comment]
same problem? Are you resolve this issue ?

**Comment by lnisi** [comment]
I have the same problem, it seems to be caused by react-native-svg even if it seems like this library supports windows since 12.4.0

Maybe someone managed to solve this? 

Using react-native 0.69.0
