### ISSUE TITLE
Delay when rendering xml content for SvgXml

### ISSUE THREAD

**Issue by sherif-cyber** [software-mansion/react-native-svg#1820]
# Bug

there's a **big delay** or **screen blocking** for a while when trying to render a lot of **SvgXml** images

for example:
1- create a screen component that render some of **SvgXml** with different xml content for each one.
2- when you try to **navigate** to this screen or open modal contain this images.
3- you can find a **delay** or **blocking** when trying to navigate or opening this modal / screen.

**FYI**: if i used `react-native-remote-svg` it renders faster

**Note:** it's happened with 
FlatList 
&
removeClippedSubviews={false}

**Comment by bohdanprog** [comment]
Hello @sherif-cyber,
can you share a simple repro of that problem?
Thank you.

**Comment by mangBert** [comment]
The <SvgXml /> component within a FlatList is causing performance issues. Could you please take a look and suggest any possible solutions?

**Comment by bohdanprog** [comment]
Hello @mangBert,
could you share a simple example?
