### ISSUE TITLE
Svg Text OnPress not working in android

### ISSUE THREAD

**Issue by skanwarjeet** [software-mansion/react-native-svg#1826]
Hey, I added onPress in SVG Text it's working fine for IOS, but it's not working for android.

```
     <G
            onPressIn={()=> alert("onPress worked")}
            strokeWidth={10}
            stroke={'transparent'}
            fontSize={24}>
            <SvgText
              fill={bottomTextColor}
              fontSize={constantStrings.TWELEV}
              fontFamily={fonts.REGULAR}
              fontWeight={constantStrings.FOUR_HUNDRED}
              y={constantStrings.TWENTY}
              textAnchor="middle">
              {bottomText}
            </SvgText>
          </G>
```
This is the code I'm using. Please help.

**Comment by aman-technyx** [comment]
facing same issue on ios
code:

  <Svg>
            <Rect
                x={textLayout.x}
                y={textLayout.y}
                width={textLayout.width}
                height={textLayout.height}
                fill="rgba(255,255,255,0.6)"
            />
            <SvgText
                onPressIn={() => console.log('sss')}
                x={labelX}
                y={labelY}
                textAnchor="middle"
                fontWeight="bold"
                fontStyle="normal"
                fontSize={fontSize}
                onLayout={onTextLayout}
                fill={fillColor}>
                {'label'}
            </SvgText>
        </Svg>

**Comment by bohdanprog** [comment]
Hello @skanwarjeet @aman-technyx,
I tried to reproduce that problem but couldn't, for me everything worked well.
If you still have that problem, feel free to open a new issue.
Thank you.
