### ISSUE TITLE
Can't compile for react-native-windows

### ISSUE THREAD

**Issue by lnisi** [software-mansion/react-native-svg#1863]
I'm working on a react-native-windows UWP application, I'm trying to add the library but It seems like I can't compile on windows platform.

> This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is C:\RN\testapp\windows\\packages\Microsoft.UI.Xaml.2.7.0\build\native\Microsoft.UI.Xaml.targets. | RNSVG | C:\RN\testapp\node_modules\react-native-svg\windows\RNSVG\RNSVG.vcxproj | 237 |  

Is there something I am missing?

react-native-svg: 13.1.0
react-native: 0.69.0

**Comment by exotexot** [comment]
Same issue 

  "react": "18.1.0",
   "react-native": "^0.70.0",
"react-native-windows": "0.70.0"
    "react-native-svg": "^13.1.0",

**Comment by sameer-shelavale** [comment]
hi @lnisi @exotexot have you found any solution to this?
I have stumbled upon same issue.

**Comment by mattia-sanfilippo** [comment]
Using `NuGet restore` should be enough to solve this.

Then it will probably warn you about missing [Win2D package](https://www.nuget.org/packages/Win2D.uwp), which you can import by:
- opening the project on Visual Studio
- Tools menu -> NuGet package manager -> Manage NuGet packages for this solution
- install Win2D.uwp 1.25

Now it should build correctly. The real problem is that SVG components will not show correctly in the app or not show at all. And I couldn't find any way to make it work, at least with `react-native-windows@0.69.7`.

**Comment by lnisi** [comment]
> Using `NuGet restore` should be enough to solve this.
> 
> Then, and also [according to this issue](https://github.com/software-mansion/react-native-svg/issues/1803), it will probably warn you about missing [Win2D package](https://www.nuget.org/packages/Win2D.uwp), which you can import by:
> 
> * opening the project on Visual Studio
> * Tools menu -> NuGet package manager -> Manage NuGet packages for this solution
> * install Win2D.uwp 1.25
> 
> Now it should build correctly. The real problem is that SVG components will not show correctly in the app or not show at all. And I couldn't find any way to make it work, at least with `react-native-windows@0.69.7`.

Yeah, actually I did the same and been able to compile but can't render any svg at all, as you mentioned.

I thought there was something wrong with the NuGet package used so I reverted everything and asked here for help.
By now I totally bypassed react-native-svg, but I hope someone can tell us more about it.

**Comment by marlenecota** [comment]
@mattia-sanfilippo @lnisi - the rendering issues should be fixed by #1928. Let me know if you're still having issues once that merges.
