### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'css_what_1.SelectorType.Universal')

### ISSUE THREAD

**Issue by ANUGLYPLUGIN** [software-mansion/react-native-svg#1873]
# Bug

When upgrade from version 12.1 to version 13(version 12.1 is ok), the app can build successfully but come with the error and show nothing
```
 ERROR  TypeError: undefined is not an object (evaluating 'css_what_1.SelectorType.Universal')
```

### Version
```
"react": "17.0.2",
"react-native": "0.68.1",
"react-native-svg": "^13.1.0",
```

**Comment by anmolpandeyy** [comment]
> Please provide a reproduction of the issue so we can work on it, otherwise it's really hard to provide any feedback.

@WoLewicki could you take a look into this https://github.com/react-native-svg/react-native-svg/issues/1084#issuecomment-1173406462 this is being ignored since last 2 months. Please give some feedback or input?

**Comment by anmolpandeyy** [comment]
> @anmolpandeyy is it connected to this issue? Also, do you have a code that could be used to reproduce the crash mentioned in #1084?

That's the problem we are unable to find the cause of this issue to be able to create a re-pro, I wanted to know what are the possibilities for it to throw that crash so that I can create some workaround to prevent it. There are thousands of crashes being reported on firebase-crashlytics. The logs that are being generated by the crash do not help.

**Comment by ethanrmiles** [comment]
@anmolpandeyy @ANUGLYPLUGIN   I was facing this same error. I do not have `react-native-svg` installed as a core dependency in my project, however it is used by a couple others as peer dependencies in my project. The two were: `native-base`, as well as `react-native-pathjs-charts`. The latter of the two has been archived, so I removed it, and my `native-base` was on version` 3.0.0`. At the time of writing this, the latest stable version is `3.4.25.` After updating to the most stable current version, the above error went away!

**Comment by ANUGLYPLUGIN** [comment]
> Please provide a reproduction of the issue so we can work on it, otherwise it's really hard to provide any feedback.

Sorry I don't look github response recently, the error message is very strange which told error in nowhere after upgrading this version ( just one useful)
`TypeError: Cannot read property 'Universal' of undefined, js engine: hermes
`

**Comment by ANUGLYPLUGIN** [comment]
> @anmolpandeyy is it connected to this issue? Also, do you have a code that could be used to reproduce the crash mentioned in #1084?

I guess it is package interrupting with other package dependencies right now.

**Comment by ANUGLYPLUGIN** [comment]
Close it for having solved it, it's because of package conflicts so everyone may solve it by check your dependencies.
