### ISSUE TITLE
Strange spike on number 2 digit

### ISSUE THREAD

**Issue by mojorisin7** [software-mansion/react-native-svg#1882]
Using Text component in the react native svg library. The only issue us with the number 2. Has a small stroke/spike from the bottom left corner of the number. Every other digit is fine except this one. I have stripped back all the Text props but it still persists.

```
      <Text
        fill="black"
        stroke="black"
        strokeWidth="1"
        fontSize="12"
        x="50"
        y="45"
        textAnchor="middle"
      >
       1234567890
      </Text>
```

<img width="361" alt="Screenshot 2022-09-26 at 16 44 46" src="https://user-images.githubusercontent.com/2281054/192324910-9d6e967c-9b87-44da-abe9-45669a3182c4.png">

**Comment by mojorisin7** [comment]
![Screenshot 2022-09-28 at 11 04 32](https://user-images.githubusercontent.com/2281054/192752759-900e44c1-cb3d-4642-af3d-d9062e5d3220.png)

So for some reason just the number 2 has this misshapen star. I've removed the stroke and it has disappeared 🤷🏽‍♂️

![Screenshot 2022-09-28 at 11 06 02](https://user-images.githubusercontent.com/2281054/192752946-4476d409-ab9c-4f69-8f0f-8f45c69c3dcf.png)

**Comment by bohdanprog** [comment]
Hello @mojorisin7 
I believe the issue has already been resolved. If you are still experiencing problems, please feel free to open a new one.
Thank you.
