### ISSUE TITLE
How to get path validation when importing SVG file

### ISSUE THREAD

**Issue by fabiendem** [software-mansion/react-native-svg#1892]
# Question

Hello everyone, 

In our `react-native` project, we're importing local SVG files as per the instructions at https://github.com/react-native-svg/react-native-svg/blob/main/USAGE.md#use-with-svg-files

```ts
import Logo from './logo.svg';
```

But at the moment, it's possible to write the import `from './logo.svg'` even if the `logo.svg` file does not exist.
We do not see any error in VSCode, neither via ESLint, neither view Typescript compilation `tsc`.
The only way to error out is to run the project, and get `metro` to try to load the file.

Is there any way to get an error at "compile" time or in the IDE, instead of at runtime?

Cheers!

**Comment by bohdanprog** [comment]
Hello @fabiendem,
 IDK if it is still relevant but as I see now I show an error at compile time:
| Correct import | Wrong import |
|--------|--------|
|<img width="1734" alt="Screenshot 2024-09-02 at 09 00 49" src="https://github.com/user-attachments/assets/767e5f55-d5e5-48e7-b6b0-dac8e52f767c"> | <img width="1732" alt="Screenshot 2024-09-02 at 09 01 04" src="https://github.com/user-attachments/assets/b214ede9-c0a1-4c47-b830-2fd1f4d200a2"> | 

I closed that issue, but feel free to ask any questions.
