### ISSUE TITLE
some Local SVG's not working while others are fine

### ISSUE THREAD

**Issue by gremlin529** [software-mansion/react-native-svg#1894]
I'm attempting to display an SVG by doing the following

`import FooBar from "./../../assets/<filename>.svg";`

then later in the project

`<FooBar height="40" width="40" />`

what I get is some SVG we have work like this:

This SVG just shows blank:
(Screenshot)
![image](https://user-images.githubusercontent.com/56889386/195934435-7c47864c-400a-4d4a-83cb-fa17847b7692.png)
(SVG)
![ShowsBlank](https://user-images.githubusercontent.com/56889386/195934462-8a7047de-acbc-49a6-849f-1a49074ae727.svg)

Other's show washed out:
(ScreenShot of the icon in React vs the browser)
![image](https://user-images.githubusercontent.com/56889386/195936090-04c38364-7638-4730-800c-33bec2ccfff9.png)

(SVG which is washed out)
![WashedOut](https://user-images.githubusercontent.com/56889386/195936174-76b8e05b-6e0b-4f88-9607-e88f71baf142.svg)

And others display normally as expected
(Screenshot in React App)
![image](https://user-images.githubusercontent.com/56889386/195936393-9dce1fd8-51e2-4a4e-b83b-cdee7f4ef1fc.png)

(SVG)
![ShowsNormal](https://user-images.githubusercontent.com/56889386/195936463-c81caa7d-6ae2-4e58-8b69-f1da902ca745.svg)

This behaviour is the same in the iOS and Android emulators as well as physical android devices.

**Comment by gremlin529** [comment]
Forgot to note that we were seeing this on 12.3.0 so I updated to 13.4.0 and still seeing the same issues. (Also the Folder Icon above now I see it here also looks washed out)

**Comment by Aryk** [comment]
Im getting this error which I think is similar - 

```
Fetching file:///data/user/0/com.tribefy.tribefy.dev/cache/ExponentAsset-9b3d6b13a27b0c8c74eba357365f270c.svg failed with status 0
at node_modules/react-native-svg/src/xml.tsx:132:17 in fetchText
- ... 13 more stack frames from framework internals
```

**Comment by Svarto** [comment]
did you solve this? I have the same washed out problem with one of my svgs

**Comment by bohdanprog** [comment]
Hello,
If you still have that problem, please provide a simple example to reproduce that.
Thank you.
