### ISSUE TITLE
fix(types): add missing children for svg common props

### ISSUE THREAD

**Issue by theonetheycallneo** [software-mansion/react-native-svg#1898]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@12.3.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/index.d.ts b/node_modules/react-native-svg/src/index.d.ts
index 891a99d..18053c1 100644
--- a/node_modules/react-native-svg/src/index.d.ts
+++ b/node_modules/react-native-svg/src/index.d.ts
@@ -231,7 +231,9 @@ export interface CommonPathProps
     TouchableProps,
     DefinitionProps,
     CommonMarkerProps,
-    CommonMaskProps {}
+    CommonMaskProps {
+      children?: React.ReactNode;
+    }
 
 // Element props
 export interface CircleProps extends CommonPathProps {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nicolehackberry** [comment]
Hello! I am having the same issues with the RadialGradient component. This is the Type-Script issue that occurs: 


```
Type '{ children: Element[]; id: string; cx: number; cy: number; r: number; gradientUnits: "userSpaceOnUse"; gradientTransform: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RadialGradientProps, any, any>> & Readonly<RadialGradientProps>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RadialGradientProps, any, any>> & Readonly<RadialGradientProps>'
  ```

**Comment by WoLewicki** [comment]
I believe it is no longer an issue since in https://github.com/software-mansion/react-native-svg/pull/1806 all the components that accept children had them added to props. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
