### ISSUE TITLE
Typeerror: Network request failed. Svg not supporting some uri(s)

### ISSUE THREAD

**Issue by looju** [software-mansion/react-native-svg#1901]
# Bug

Please provide a clear and concise description of what the bug is.
I installed the latest version of react-native-svg. However, it doesn't seem to work with some svgs fetched from uri(s). Have tried about five different servers now and it still returns a network error

#### Unexpected behavior

This is the link to an expo snack showing the error 

https://snack.expo.dev/@loju/0e43c4

## Environment info

The development is occurring on the expo CLI. The package.JSON folder:
        `{
          "name": "mealstogo",
          "version": "1.0.0",
          "main": "node_modules/expo/AppEntry.js",
          "scripts": {
            "start": "expo start",
            "android": "expo start --android",
            "ios": "expo start --ios",
            "web": "expo start --web"
          },
          "dependencies": {
            "@callstack/react-theme-provider": "^3.0.8",
            "@expo-google-fonts/dev": "^0.2.2",
            "@react-navigation/bottom-tabs": "^6.4.0",
            "@react-navigation/native": "^6.0.13",
            "@rneui/themed": "^4.0.0-rc.6",
            "@types/styled-components": "^5.1.26",
            "camelcase": "^7.0.0",
            "expo": "~46.0.16",
            "expo-font": "~10.2.0",
            "expo-status-bar": "~1.4.0",
            "react": "18.0.0",
            "react-native": "0.69.6",
            "react-native-paper": "^5.0.0-rc.6",
            "react-native-safe-area-context": "^4.3.1",
            "react-native-screens": "~3.15.0",
            "react-native-svg": "^12.3.0",
            "react-native-vector-icons": "^9.2.0",
            "styled-components": "^5.3.6"
          },
          "devDependencies": {
            "@babel/core": "^7.12.9"
          },
          "private": true
        }

`

Library version: 12.3.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. Go to the expo snack at https://snack.expo.dev/@loju/0e43c4
2. Start the project on the android or ios emulator (might have to queue)
3. Alternatively, a physical device can be used by scanning the QR code at the expo snack

Describe what you expected to happen:

1. Svg to be displayed
2. Svg to work with uri(s) from various servers

**Comment by Aryk** [comment]
I'm getting errors like this as well but only on Android: 

<img width="1072" alt="Screen Shot 2022-11-10 at 10 59 58 PM" src="https://user-images.githubusercontent.com/525212/201281989-13c7ad59-c493-4a5f-b1f2-5fa5696f4c75.png">

**Comment by bohdanprog** [comment]
Hello @looju,
I tried to reproduce that issue but everything worked well.
If you still have that problem feel free to open a new issue.
