### ISSUE TITLE
TSpan the space between the letters does not look good

### ISSUE THREAD

**Issue by danielm2402** [software-mansion/react-native-svg#1902]
Hey guys. I have a problem when using TSpan with a fontSize 2, some of the letters look mounted on each other. It happens to me on the emulator and on some physical devices.

This is how it looks:

![image](https://user-images.githubusercontent.com/45048389/198151844-33e8bbca-34ec-4653-adc7-b4e9cae32e4c.png)

![image](https://user-images.githubusercontent.com/45048389/198151937-00ce8e30-d3ba-4748-a5a8-12c8acd21b7e.png)

My component looks like this:

```
<Svg
            width="100%"
            height="100%"
            viewBox="0 0 60 60">
            <G strokeWidth='6'>
                {data.map((item, index) => <Circle fill="transparent" key={index} cx="50%" cy="50%" r='16' strokeLinecap='round' strokeDasharray={`${item.percent} 100`} strokeDashoffset={`-${item.stroke}`} stroke={item.color} ></Circle>)}
            </G>
            <Text strokeWidth="0.5" fill="#fff" fontSize="7" x="50%" y="50%" textAnchor="middle">
                <TSpan x="50%" textAnchor='middle'>{title}</TSpan>
                <TSpan x="50%" dy="3" textAnchor='middle' fontSize={2} >{text}</TSpan>
                <Line strokeWidth="0.2" x1="40%" y1="58%" x2="60%" y2="58%" stroke="#fff" />
                <TSpan x="50%" dy="5" textAnchor='middle' fontSize="1.7" strokeWidth="0.5">{subtext}</TSpan>
            </Text>
        </Svg>
```
This is the line that does not show correctly:

`<TSpan x="50%" dy="3" textAnchor='middle' fontSize={2} >{text}</TSpan>`

I am using: 

"react-native": "^0.68.2",
"react-native-svg": "^12.3.0"

If some more info is needed I will add it. Thanks in advance

**Comment by bohdanprog** [comment]
Hello @danielm2402,
Can you provide a simple example to reproduce that issue?
Thank you
