### ISSUE TITLE
OnPressEvent on IOS not always working when pressing on stroke

### ISSUE THREAD

**Issue by masterRokshi** [software-mansion/react-native-svg#1908]
# Bug

When pressing on a stroke, sometimes click won't get detected

Ive made a snack here: https://snack.expo.dev/@rokus/native-svg-curve-press?platform=ios

How to replicate:
- try pressing more on the left side of the path

Works fine on android

**Comment by bohdanprog** [comment]
Hello @masterRokshi,
Are there any updates about it?
Thank you.
