### ISSUE TITLE
Add children to RadialGradientProps

### ISSUE THREAD

**Issue by fvn-manhtd** [software-mansion/react-native-svg#1917]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@12.3.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/index.d.ts b/node_modules/react-native-svg/src/index.d.ts
index 891a99d..112f6ba 100644
--- a/node_modules/react-native-svg/src/index.d.ts
+++ b/node_modules/react-native-svg/src/index.d.ts
@@ -365,6 +365,7 @@ export interface RadialGradientProps {
   gradientUnits?: Units;
   gradientTransform?: ColumnMajorTransformMatrix | string;
   id?: string;
+  children?: React.ReactNode;
 }
 export const RadialGradient: React.ComponentClass<RadialGradientProps>;
 export type RadialGradient = React.ComponentClass<RadialGradientProps>;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by WoLewicki** [comment]
Thanks for submitting an issue! I believe this has been already solved in the newer versions of the library, as you can see here: https://github.com/software-mansion/react-native-svg/blob/b3dc36ab01d5b6e6335e30f0f442099a3dedef16/src/elements/RadialGradient.tsx#L10. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.
