### ISSUE TITLE
typescript compile fails for web since 12.4.4

### ISSUE THREAD

**Issue by sbin1211** [software-mansion/react-native-svg#1920]
errors: 

> TS2322: Type '{ d: string; stroke: string; fillOpacity: number; fill: string; strokeWidth: number; strokeLinecap: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Path> & Readonly<BaseProps> & Readonly<{ children?: ReactNode; }>'.
>   Property 'd' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Path> & Readonly<BaseProps> & Readonly<{ children?: ReactNode; }>'.
>     384 |                       {visiable && (
>     385 |                               <Svg height={ConnectLineAreaHeight} width={width}>
>   > 386 |                                       <Path d={path} stroke="white" fillOpacity={0} fill="transparent" strokeWidth={2} strokeLinecap={'round'} />
>         |                                             ^
>     387 |                               </Svg>
>     388 |                       )}
>     389 |               </Box>

    

under tsconfig.json, if i specified the "moduleSuffixes" options to [".web",""] 
then import the "react-native-svg", 
the typescript engine will load the declaration file from "ReactNativeSVG.web.d.ts", but this declaration file have no properties definition for tags and report errors. 

react native:0.68,
 "react-native-web": "0.18.9",
 typescript: 4.7.2

**Comment by tenfef** [comment]
I'm having the same problem. Is there a workaround?
