### ISSUE TITLE
SvgXml inside <SVG> tag is showing blank in case of IOS, working fine in Android.

### ISSUE THREAD

**Issue by mohitarora777** [software-mansion/react-native-svg#1930]
# Bug

When wrapping SvgCss/ SvgXml inside SVG tag, it renders nothing in IOS, but works fine in android

## Environment info

```bash
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.99 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.17.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.2.0
        "react-native-svg": "12.2.0",

##Code

This is svg xml i am using:

const xml = `
<svg width="313" height="50" viewBox="0 0 313 50" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M243.313 47H68.6868L51 0H261L243.313 47Z" fill="url(#paint0_linear_32292_209567)"/>
<path d="M305.65 0.000234375H312.5C312.5 0.000234375 312.49 2.04023 309.17 1.81023C312.49 6.04023 310.18 10.6102 310.18 10.6102C307.27 3.79023 300.84 5.10023 298.23 4.71023C300 7.77023 298.75 10.8402 298.45 11.4402C298.45 11.4802 298.39 11.4802 298.37 11.4202C297.67 8.92023 295.36 8.02024 292.55 8.00023C289.46 8.00023 286.18 8.92023 282.99 8.42023C282.03 8.26023 281.06 7.98023 280.16 7.55023C280.04 7.50023 279.7 7.37023 279.46 7.23023C279.34 7.18023 279.2 7.25023 279.22 7.35023C280.1 11.2802 284.2 11.8502 284.2 11.8502C275.77 13.5902 266.39 9.11023 262.68 1.85023C262.34 1.19023 262.06 0.580234 261.8 -0.00976562H305.64L305.65 0.000234375Z" fill="url(#paint1_linear_32292_209567)"/>
<path d="M6.85 0.000234375H0C0 0.000234375 0.0100019 2.04023 3.33 1.81023C0.0100019 6.04023 2.32 10.6102 2.32 10.6102C5.23 3.79023 11.66 5.10023 14.27 4.71023C12.5 7.77023 13.75 10.8402 14.05 11.4402C14.05 11.4802 14.11 11.4802 14.13 11.4202C14.83 8.92023 17.14 8.02024 19.95 8.00023C23.04 8.00023 26.32 8.92023 29.51 8.42023C30.47 8.26023 31.44 7.98023 32.34 7.55023C32.46 7.50023 32.8 7.37023 33.04 7.23023C33.16 7.18023 33.3 7.25023 33.28 7.35023C32.4 11.2802 28.3 11.8502 28.3 11.8502C36.73 13.5902 46.11 9.11023 49.82 1.85023C50.16 1.19023 50.44 0.580234 50.7 -0.00976562H6.85V0.000234375Z" fill="url(#paint2_linear_32292_209567)"/>
<path d="M255.469 18.4395L251.449 24.4495L272.519 38.0695L276.539 32.0595L255.469 18.4395Z" fill="url(#paint3_linear_32292_209567)"/>
<path d="M276.709 32.1604L272.679 38.1704L275.799 42.6604C276.289 43.3704 277.349 43.3604 277.829 42.6404L282.929 35.0304C283.409 34.3204 282.999 33.3504 282.139 33.1904L276.709 32.1504V32.1604Z" fill="url(#paint4_linear_32292_209567)"/>
<path d="M34.7793 32.1604L38.8093 38.1704L35.6893 42.6604C35.1993 43.3704 34.1393 43.3604 33.6593 42.6404L28.5593 35.0304C28.0793 34.3204 28.4893 33.3504 29.3493 33.1904L34.7793 32.1504V32.1604Z" fill="url(#paint5_linear_32292_209567)"/>
<path d="M56.0192 18.4395L60.0392 24.4495L38.9692 38.0695L34.9492 32.0595L56.0192 18.4395Z" fill="url(#paint6_linear_32292_209567)"/>
<path d="M70.4645 49.54H59.7643L40 0H50.7121L70.4645 49.54Z" fill="url(#paint7_linear_32292_209567)"/>
<path d="M241.536 49.54H252.236L272 0H261.288L241.536 49.54Z" fill="url(#paint8_linear_32292_209567)"/>
<defs>
<linearGradient id="paint0_linear_32292_209567" x1="252.81" y1="64.5177" x2="42.7831" y2="-57.3951" gradientUnits="userSpaceOnUse">
<stop stop-color="#000C2C"/>
<stop offset="0.15" stop-color="#070838"/>
<stop offset="0.42" stop-color="#1A005A"/>
<stop offset="0.47" stop-color="#290369"/>
<stop offset="0.57" stop-color="#520D92"/>
<stop offset="0.65" stop-color="#7616B5"/>
<stop offset="0.7" stop-color="#6919B9"/>
<stop offset="0.79" stop-color="#4921C3"/>
<stop offset="0.87" stop-color="#252BD0"/>
</linearGradient>
<linearGradient id="paint1_linear_32292_209567" x1="323.31" y1="8.32023" x2="268.99" y2="3.93023" gradientUnits="userSpaceOnUse">
<stop stop-color="#FF00A4"/>
<stop offset="0.23" stop-color="#EF0025"/>
<stop offset="0.29" stop-color="#EA1424"/>
<stop offset="0.41" stop-color="#DE4823"/>
<stop offset="0.48" stop-color="#D76B23"/>
<stop offset="0.56" stop-color="#D97021"/>
<stop offset="0.65" stop-color="#E0801C"/>
<stop offset="0.75" stop-color="#EB9A13"/>
<stop offset="0.86" stop-color="#FABD08"/>
<stop offset="0.88" stop-color="#FFC905"/>
</linearGradient>
<linearGradient id="paint2_linear_32292_209567" x1="-10.82" y1="8.32023" x2="43.5" y2="3.93023" gradientUnits="userSpaceOnUse">
<stop stop-color="#FF00A4"/>
<stop offset="0.23" stop-color="#EF0025"/>
<stop offset="0.29" stop-color="#EA1424"/>
<stop offset="0.41" stop-color="#DE4823"/>
<stop offset="0.48" stop-color="#D76B23"/>
<stop offset="0.56" stop-color="#D97021"/>
<stop offset="0.65" stop-color="#E0801C"/>
<stop offset="0.75" stop-color="#EB9A13"/>
<stop offset="0.86" stop-color="#FABD08"/>
<stop offset="0.88" stop-color="#FFC905"/>
</linearGradient>
<linearGradient id="paint3_linear_32292_209567" x1="267.269" y1="23.6395" x2="262.389" y2="30.4995" gradientUnits="userSpaceOnUse">
<stop offset="0.22"/>
<stop offset="0.28" stop-color="#03000C"/>
<stop offset="0.37" stop-color="#0D002D"/>
<stop offset="0.48" stop-color="#1A005A"/>
<stop offset="0.52" stop-color="#290369"/>
<stop offset="0.59" stop-color="#520D92"/>
<stop offset="0.64" stop-color="#7616B5"/>
<stop offset="0.68" stop-color="#6D22B7"/>
<stop offset="0.75" stop-color="#5842BE"/>
<stop offset="0.84" stop-color="#3476CA"/>
<stop offset="0.87" stop-color="#258ED0"/>
</linearGradient>
<linearGradient id="paint4_linear_32292_209567" x1="283.129" y1="37.6804" x2="272.679" y2="37.6804" gradientUnits="userSpaceOnUse">
<stop stop-color="#FFC905"/>
<stop offset="0.07" stop-color="#F2A30E"/>
<stop offset="0.16" stop-color="#E68017"/>
<stop offset="0.24" stop-color="#DE661D"/>
<stop offset="0.32" stop-color="#D85621"/>
<stop offset="0.37" stop-color="#D75123"/>
<stop offset="0.41" stop-color="#D94823"/>
<stop offset="0.65" stop-color="#E81424"/>
<stop offset="0.77" stop-color="#EF0025"/>
<stop offset="1" stop-color="#FF00A4"/>
</linearGradient>
<linearGradient id="paint5_linear_32292_209567" x1="28.3593" y1="37.6804" x2="38.8093" y2="37.6804" gradientUnits="userSpaceOnUse">
<stop stop-color="#FFC905"/>
<stop offset="0.07" stop-color="#F2A30E"/>
<stop offset="0.16" stop-color="#E68017"/>
<stop offset="0.24" stop-color="#DE661D"/>
<stop offset="0.32" stop-color="#D85621"/>
<stop offset="0.37" stop-color="#D75123"/>
<stop offset="0.41" stop-color="#D94823"/>
<stop offset="0.65" stop-color="#E81424"/>
<stop offset="0.77" stop-color="#EF0025"/>
<stop offset="1" stop-color="#FF00A4"/>
</linearGradient>
<linearGradient id="paint6_linear_32292_209567" x1="42.2392" y1="21.0095" x2="50.5892" y2="32.5095" gradientUnits="userSpaceOnUse">
<stop offset="0.22"/>
<stop offset="0.28" stop-color="#03000C"/>
<stop offset="0.37" stop-color="#0D002D"/>
<stop offset="0.48" stop-color="#1A005A"/>
<stop offset="0.52" stop-color="#290369"/>
<stop offset="0.59" stop-color="#520D92"/>
<stop offset="0.64" stop-color="#7616B5"/>
<stop offset="0.68" stop-color="#6D22B7"/>
<stop offset="0.75" stop-color="#5842BE"/>
<stop offset="0.84" stop-color="#3476CA"/>
<stop offset="0.87" stop-color="#258ED0"/>
</linearGradient>
<linearGradient id="paint7_linear_32292_209567" x1="55.5845" y1="-6.95" x2="55.0402" y2="64.2618" gradientUnits="userSpaceOnUse">
<stop stop-color="#FF00A4"/>
<stop offset="0.23" stop-color="#EF0025"/>
<stop offset="0.35" stop-color="#E81424"/>
<stop offset="0.59" stop-color="#D94823"/>
<stop offset="0.63" stop-color="#D75123"/>
<stop offset="0.68" stop-color="#D85621"/>
<stop offset="0.76" stop-color="#DE661D"/>
<stop offset="0.84" stop-color="#E68017"/>
<stop offset="0.93" stop-color="#F2A30E"/>
<stop offset="1" stop-color="#FFC905"/>
</linearGradient>
<linearGradient id="paint8_linear_32292_209567" x1="257.096" y1="-5.42" x2="256.552" y2="65.7918" gradientUnits="userSpaceOnUse">
<stop stop-color="#FF00A4"/>
<stop offset="0.23" stop-color="#EF0025"/>
<stop offset="0.35" stop-color="#E81424"/>
<stop offset="0.59" stop-color="#D94823"/>
<stop offset="0.63" stop-color="#D75123"/>
<stop offset="0.68" stop-color="#D85621"/>
<stop offset="0.76" stop-color="#DE661D"/>
<stop offset="0.84" stop-color="#E68017"/>
<stop offset="0.93" stop-color="#F2A30E"/>
<stop offset="1" stop-color="#FFC905"/>
</linearGradient>
</defs>
</svg>
`

1) Without Wrapping inside Svg tag (renders correctly in both platforms)
      
               <SvgXml xml={xml}/>

![File](https://user-images.githubusercontent.com/107910744/205456446-23b705dd-1a34-4910-bd90-f8735d2031c7.jpg)

2) Wrapped inside Svg tag (renders nothing in IOS, works fine in Android)

            import { Svg, SvgXml } from 'react-native-svg';
            <Svg height={200} width={200}>
               <SvgXml xml={xml}/>
             </Svg>

![File (1)](https://user-images.githubusercontent.com/107910744/205456451-f4cec76a-9bec-48a3-b140-b75d294e984f.jpg)

**Comment by WoLewicki** [comment]
Could you explain what is the use-case for this? `SvgXml` already renders `Svg` under the hood.

**Comment by mohitarora777** [comment]
I am using https://github.com/software-mansion/react-native-svg/issues/1328#issuecomment-809649099 this for caching remote svg images which are rendering inside  svg of different paths.

**Comment by WoLewicki** [comment]
I tested the your code and it seems that the problem lays in the `fill` property not being applied correctly. You can change one of them from `url...` to e.g. "blue" and see that that element renders correctly. I will debug it further to see why the information is not passed correctly.

**Comment by mohitarora777** [comment]
@WoLewicki i also did check with solid colors, it seem to happen only for gradient filled

**Comment by WoLewicki** [comment]
@mohitarora777 can you check if applying https://github.com/software-mansion/react-native-svg/pull/1939 fixes your issues and does not introduce any new ones?

**Comment by mohitarora777** [comment]
@WoLewicki will update, as i am using an older version of this lib, there might be issue applying this.
