### ISSUE TITLE
Path's onLayout works fine?

### ISSUE THREAD

**Issue by kr-yeon** [software-mansion/react-native-svg#1942]
Currently working with svg. I needed the horizontal size, vertical size, and x and y values ​​of the path, so I tried to bring them into onLayout, but it seems to be getting the size of the SVG tag.

'''event.nativeEvent.layout'''

 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}
 LOG {"height": 0, "width": 370.28570556640625, "x": 0, "y": 0}

react-native-svg: 13.6.0
platform: android

**Comment by kr-yeon** [comment]
iPhone works fine. 

 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 0, "width": 372, "x": 0, "y": 0}
 LOG  {"height": 48.589210569726276, "width": 89.3074432095348, "x": 16.314041808009556, "y": 478.0800686064527}
 LOG  {"height": 134.1527106293181, "width": 163.68597053958993, "x": 144.25894879911888, "y": 282.94652876966563}
 LOG  {"height": 118.36246189731531, "width": 174.7988819966492, "x": -1.498401686228953, "y": 326.5069029162605}
 LOG  {"height": 105.32398931652486, "width": 161.4629475287487, "x": 23.83067619622702, "y": 252.83804465039745}
 LOG  {"height": 175.13454422648087, "width": 160.38712428557216, "x": 179.3716709246806, "y": 162.15293236914917}
 LOG  {"height": 19.995899977968236, "width": 26.396284867039412, "x": 328.1708214347527, "y": 247.8427847687716}
 LOG  {"height": 8.312698941506369, "width": 8.767504506334944, "x": 356.3492515027625, "y": 261.943868323854}
 LOG  {"height": 6.544261604904534, "width": 9.32420209891393, "x": 362.29864745004284, "y": 268.4592154489967}
 LOG  {"height": 144.00523593984147, "width": 125.10843234142027, "x": 132.64815051580416, "y": 140.72949079009177}
 LOG  {"height": 118.01065976744897, "width": 149.8167417063536, "x": 10.883689751750953, "y": 159.30725724567534}
 LOG  {"height": 28.311739928432218, "width": 17.969396395073982, "x": 23.779577067595785, "y": 224.04146370936593}
 LOG  {"height": 166.26988824359353, "width": 191.11240326494703, "x": 125.42781471305638, "y": -0.8688961091925242}
 LOG  {"height": 152.23452239753234, "width": 124.11097292512588, "x": 64.66732130528246, "y": 19.829766540688947}
 LOG  {"height": 34.9354432993041, "width": 23.75452759119122, "x": 39.075391449053875, "y": 81.39434788246132}

**Comment by kr-yeon** [comment]
IOS works fine. The problem with Path seems to only happen on Android.
For the G tag, each onLayout is returned for all paths inside. Any good solutions?

It seems that there is also a problem with onLayout, not just with getTotalLength.

**Comment by bohdanprog** [comment]
Hello @kr-yeon,
Do you still have that problem?
