### ISSUE TITLE
Emojis not working on MacOS

### ISSUE THREAD

**Issue by k1mmm** [software-mansion/react-native-svg#1950]
# Bug
When using Emojis in Text or TSpan nothing is rendered on MacOS

## Environment info
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 116.64 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: 0.68.57 => 0.68.57 
  npmGlobalPackages:

Library version: 13.6.0

## Steps To Reproduce
<Text>😀</Text>

**Comment by k1mmm** [comment]
Any updates to this? If you point me in the right direction I might be able to solve it myself =)

**Comment by bohdanprog** [comment]
Hello @k1mmm,
I tried to reproduce that issue but couldn't.

| IOS | ANDROID |
|--------|--------|
|<img width="300" height="700"  src="https://github.com/software-mansion/react-native-svg/assets/69891500/015e04ec-fc7e-41b7-a233-706a32cd7cac" /> | <img width="300" height="700"  src="https://github.com/software-mansion/react-native-svg/assets/69891500/214b3a79-a216-4acc-b531-02ff41cd7f17" /> | 

If you still have some problems feel free to open a new issue.
Thank you

**Comment by k1mmm** [comment]
Hello @bohdanprog!
Thank you for your reply, the issue is on MacOS and not iOS nor Android =)
