### ISSUE TITLE
native svg cannot change colors with fill

### ISSUE THREAD

**Issue by gcindy** [software-mansion/react-native-svg#1959]
` <SvgXml xml="search" width={40} height={40} fill="#ff4040" />`
 
<img width="381" alt="未命名" src="https://user-images.githubusercontent.com/37326714/211263692-f900dfbd-ae79-48c7-a2c6-e3436dff4a1c.png">

**Comment by WoLewicki** [comment]
Could you provide a simple repo with a reproduction of the issue? Also, did it stop working correctly in the newest version or was it not working correctly earlier?

**Comment by gcindy** [comment]
https://github.com/gcindy/neteaseCloudMusicApp.git.  

The path is Src/pages/mine

**Comment by WoLewicki** [comment]
Can you break it down to a simple repo? I tried providing the `fill` to `SvgXml` and it worked just fine:
```tsx
import * as React from 'react';
import {View} from 'react-native';
import {SvgXml} from 'react-native-svg';

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="100" height="300" viewBox="0 0 100 100">
<circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" />
</svg>`;

export default function App() {
  return (
    <View style={{flex: 1}}>
      <SvgXml xml={svg} fill="blue" />
    </View>
  );
}
```

**Comment by gcindy** [comment]
import { StyleSheet, Text, View, Image } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { SvgXml } from "react-native-svg";

export default function App() {
  const down = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>切片</title>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="公共组件" transform="translate(-104.000000, -248.000000)" fill="#BFBFBF">
            <g id="icon/prompt/error" transform="translate(104.000000, 248.000000)">
                <path d="M10,0 C15.5228475,0 20,4.4771525 20,10 C20,15.5228475 15.5228475,20 10,20 C4.4771525,20 0,15.5228475 0,10 C0,4.4771525 4.4771525,0 10,0 Z M7.17157288,5.75735931 C6.78104858,5.36683502 6.1478836,5.36683502 5.75735931,5.75735931 C5.39687535,6.11784327 5.36914582,6.68507433 5.67417071,7.07736554 L5.75735931,7.17157288 L8.58507933,9.99929289 L5.75735931,12.8284271 C5.36683502,13.2189514 5.36683502,13.8521164 5.75735931,14.2426407 C6.11784327,14.6031246 6.68507433,14.6308542 7.07736554,14.3258293 L7.17157288,14.2426407 L9.99929289,11.4135065 L12.8284271,14.2426407 C13.2189514,14.633165 13.8521164,14.633165 14.2426407,14.2426407 C14.6031246,13.8821567 14.6308542,13.3149257 14.3258293,12.9226345 L14.2426407,12.8284271 L11.4142136,10 L14.2426407,7.17157288 C14.633165,6.78104858 14.633165,6.1478836 14.2426407,5.75735931 C13.8821567,5.39687535 13.3149257,5.36914582 12.9226345,5.67417071 L12.8284271,5.75735931 L10,8.58578644 L7.17157288,5.75735931 Z" id="形状"></path>
            </g>
        </g>
    </g>
</svg>`;

  return (
    <SafeAreaView>
      <View>
        <SvgXml style={styles.icon} xml={down} width={30} height={30} fill="blue" />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  icon: {
    marginBottom: 20,
  },
});

**Comment by gcindy** [comment]
```
import { StyleSheet, Text, View, Image } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { SvgXml } from "react-native-svg";

export default function App() {
  const down = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>切片</title>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="公共组件" transform="translate(-104.000000, -248.000000)" fill="#BFBFBF">
            <g id="icon/prompt/error" transform="translate(104.000000, 248.000000)">
                <path d="M10,0 C15.5228475,0 20,4.4771525 20,10 C20,15.5228475 15.5228475,20 10,20 C4.4771525,20 0,15.5228475 0,10 C0,4.4771525 4.4771525,0 10,0 Z M7.17157288,5.75735931 C6.78104858,5.36683502 6.1478836,5.36683502 5.75735931,5.75735931 C5.39687535,6.11784327 5.36914582,6.68507433 5.67417071,7.07736554 L5.75735931,7.17157288 L8.58507933,9.99929289 L5.75735931,12.8284271 C5.36683502,13.2189514 5.36683502,13.8521164 5.75735931,14.2426407 C6.11784327,14.6031246 6.68507433,14.6308542 7.07736554,14.3258293 L7.17157288,14.2426407 L9.99929289,11.4135065 L12.8284271,14.2426407 C13.2189514,14.633165 13.8521164,14.633165 14.2426407,14.2426407 C14.6031246,13.8821567 14.6308542,13.3149257 14.3258293,12.9226345 L14.2426407,12.8284271 L11.4142136,10 L14.2426407,7.17157288 C14.633165,6.78104858 14.633165,6.1478836 14.2426407,5.75735931 C13.8821567,5.39687535 13.3149257,5.36914582 12.9226345,5.67417071 L12.8284271,5.75735931 L10,8.58578644 L7.17157288,5.75735931 Z" id="形状"></path>
            </g>
        </g>
    </g>
</svg>`;

  return (
    <SafeAreaView>
      <View>
        <SvgXml style={styles.icon} xml={down} width={30} height={30} fill="blue" />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  icon: {
    marginBottom: 20,
  },
});
```

I tried to set it this way, but it didn't work.

**Comment by WoLewicki** [comment]
It doesn't work since the inner element override their `fill` attribute, e.g. `fill="#BFBFBF"` in `g` element. If you remove this fill, it works correctly. Isn't the innermost element's `fill` attribute the one that decides the fill of the element? Or am I missing something?

**Comment by bohdanprog** [comment]
Hello @gcindy,
We closed that issue. 
But if you still have that problem feel free to open a new issue.
