### ISSUE TITLE
Unable to rotate text in pie charts with common center

### ISSUE THREAD

**Issue by saurabhsaneja** [software-mansion/react-native-svg#1960]
Description
I am working on a wheel made of pie charts. I am unable to rotate text.  

Snack or a link to a repository
https://snack.expo.dev/@saurabhsaneja/305e02
<img width="213" alt="rotate" src="https://user-images.githubusercontent.com/27431935/211468701-7ccfcaae-48f5-4ced-bfce-6fe7d3c243b7.PNG">

React Native version
0.66.4

**Comment by bohdanprog** [comment]
Hello @saurabhsaneja,

Are you still experiencing that issue? If the problem persists, please provide us with a simple example to replicate it.
Thank you.
