### ISSUE TITLE
Text SVG creation on Intel MacOS hogs the whole system for 10+ seconds

### ISSUE THREAD

**Issue by k1mmm** [software-mansion/react-native-svg#1961]
# Bug

Creating a text SVG on MacOS freezes the system on Intel processor for 10+ seconds.

**Comment by bohdanprog** [comment]
Hello @k1mmm,
Can you share a simple example to reproduce that issue?
Thank you

**Comment by k1mmm** [comment]
Hello @bohdanprog, as I no longer have an Intel Mac so I cannot demonstrate the issue, but I've forked the repo and solved the issue in this commit: https://github.com/k1mmm/react-native-svg/commit/6d0e7bab7c5a980a13f3a367c683e88d455aac18

I found the issue in "addUIBlock" that sometimes took over 10seconds to resolve, and I know my approach is not optimal since we need to wait for the UI block to get the bounds etc. This was back when I was using react-native-macos 0.71 or 0.70.0 I think, so it might been fixed since then =)

**Comment by bohdanprog** [comment]
@k1mmm  we have closed that issue. 
If you find any problems again, please don't hesitate to open a new issue.

Thank you.
