### ISSUE TITLE
Fill style is not longer set to "none" by defalt

### ISSUE THREAD

**Issue by Romick2005** [software-mansion/react-native-svg#1963]
Using newest 13.7.0 version it seems that we need to specify and check all svg fill property. 
It was working fine on 13.6.0, but luckily it can be easy fixed with explicit fill property declaration.
```
<Svg
  width="100"
  height="100"
  viewBox="0 0 512 512">
  <Path
    stroke="#FFFFFF"
    strokeLinecap="round"
    strokeLinejoin="round"
    strokeWidth="48"
    d="M328 112L184 256l144 144"
  />
</Svg>
```
```
<Svg
  width={size}
  height={size}
  viewBox="0 0 512 512">
  <Path
    d="M448 256c0-106-86-192-192-192S64 150 64 256s86 192 192 192 192-86 192-192z"
    stroke={color || colorMap.white}
    strokeWidth={32}
  />
  <Circle cx="256" cy="256" r="26"
    style={{
      fill: color || colorMap.white
    }}
  />
  <Circle cx="346" cy="256" r="26"
    style={{
      fill: color || colorMap.white
    }}
  />
  <Circle cx="166" cy="256" r="26"
    style={{
      fill: color || colorMap.white
    }}
  />
</Svg>
```

![image](https://user-images.githubusercontent.com/17779660/211592007-95953601-d019-4f87-b793-40bf748bfd07.png)
![image](https://user-images.githubusercontent.com/17779660/211593890-6baaf114-5d89-41f0-bdf1-79891124d79e.png)

**Comment by curthipster** [comment]
Looks like they changed this intentionally in https://github.com/software-mansion/react-native-svg/pull/1947

For us, this is a breaking change. I imagine it is for many others as well! It's described as fixing a regression, but the "regression" was introduced in Jan 2020, so I'd argue this is how people expect it to work now.

Before I goto the trouble of setting default fill styles, I'd love to know if this is indeed intentional and will stick.

**Comment by Romick2005** [comment]
Seems like black should be as default for svg according to [specification](https://www.w3.org/TR/SVG2/painting.html#SpecifyingFillPaint)
[This is default fill change](https://github.com/software-mansion/react-native-svg/commit/a9df6e0bbda4caf8c3b13213194a0c4aef8a7218)

**Comment by WoLewicki** [comment]
Can you check if using the same svg in web resolves in different output? If it renders as black on web, I believe it is the expected behavior. I know the behavior has been different for a long time in `react-native-svg`, but still it was a bug. Or am I missing something?

**Comment by Romick2005** [comment]
Yes I can confirm that on web it is rendered with default black fill property value.
![image](https://user-images.githubusercontent.com/17779660/212333046-30b9f788-65ae-4591-9767-77203cd4137d.png)

Case closed. Thank you!
