### ISSUE TITLE
RN 0.71.0 - installDebug error - build.gradle line:88 - implementation project(":ReactAndroid")

### ISSUE THREAD

**Issue by ugurdalkiran** [software-mansion/react-native-svg#1966]
I try to run it on the most current version of everything.

After installing the **react-native-svg** library, I say `npx react-native-run-android` but it throws an error in the build.gradle (88) file.

![image](https://user-images.githubusercontent.com/27302986/212714202-8f041484-a13e-4027-a8a7-31496396b5ca.png)

The relevant line contains the following code:

`implementation project(":ReactAndroid")`

```
A problem occurred evaluating project ':react-native-svg'.
> Project with path ':ReactAndroid' could not be found in project ':react-native-svg'.
```

How can I solve this problem?

**Comment by WoLewicki** [comment]
Could you try using the version of library from the newest main? Also, do you use new architecture in your app?

**Comment by WoLewicki** [comment]
Can you make a repo with a simple reproduction of the issue?

**Comment by ugurdalkiran** [comment]
Could the automatic linking process not be working properly?

```
dependencies {
    if (isNewArchitectureEnabled()) {
        implementation project(":ReactAndroid")
    } else {
        implementation 'com.facebook.react:react-native:+'
    }
}
```

I changed this code area like this and was able to move forward. ✔️

```
dependencies {
    implementation 'com.facebook.react:react-native:+'
}
```

But this time, the problem appears on this page.

https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1384142784

**Comment by WoLewicki** [comment]
So the newest main of `react-native-svg` contains the correct code? If so, can I close the issue?

**Comment by ugurdalkiran** [comment]
I don't know if what I'm doing is right. Maybe that's causing the issue on the other page I linked to. :/

**Comment by sudhanshusirohia** [comment]
@ugurdalkiran  is it the right solution, as I am also facing the same?

**Comment by ugurdalkiran** [comment]
@sudhanshusirohia Yes I think it is correct.

**Comment by ravithesun02** [comment]
Hi @WoLewicki @ugurdalkiran which version to use to fix this issue. 
After changing library as specified above its working , but i need to do it everytime. 
In production side , how to change this file ?

**Comment by UNIDY2002** [comment]
> In production side , how to change this file ?

You can use [patch-package](https://www.npmjs.com/package/patch-package). You may also find a patch file here: https://github.com/software-mansion/react-native-svg/issues/1970

BTW, I think this issue is solved in the latest commit on main. Hope that the author of this package can release a new version.
