### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by Pingou** [software-mansion/react-native-svg#1967]
App crashes with error Maximum call stack exceeded when using this svg: https://upload.wikimedia.org/wikipedia/commons/0/0a/Argentina_%28orthographic_projection%29.svg

## Environment info

System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M2
    Memory: 38.04 MB / 24.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.17 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.0, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 13.7.0

## Steps To Reproduce

Add
```
<SvgCssUri
                width="100%"
                height="100%"
                uri="https://upload.wikimedia.org/wikipedia/commons/0/0a/Argentina_%28orthographic_projection%29.svg"
              />
```

App crashes

Describe what you expected to happen:

Image load

**Comment by bohdanprog** [comment]
Hello @Pingou,
Do you still have that issue?
I tried to reproduce that, but everything worked well.

**Comment by Pingou** [comment]
@bohdanprog Sorry I do not remember anything about this issue.
