### ISSUE TITLE
Can't use on web with Reanimated

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/react-native-svg#1973]
# Bug

The following error gets posted on Web: `Invariant Violation: createAnimatedComponent does not support stateless functional components; use a class component instead.`

My guess is that the web elements don't fit the following criteria:

```tsx
export default function createAnimatedComponent(Component, options) {
    invariant(typeof Component !== 'function' ||
        (Component.prototype && Component.prototype.isReactComponent), '`createAnimatedComponent` does not support stateless functional components; ' +
        'use a class component instead.')
```

I confirmed this by doing this on web:

```tsx
import { Rect } from 'react-native-svg'

console.log(Rect.prototype) // logs undefined
```

#### Unexpected behavior

Since these are indeed class components, it should work fine.

## Environment info

Using Next.js
 
Library version: 13.7.0 with Reanimated 2.14

## Steps To Reproduce

I'll add a reproduction if necessary! However, it's a pretty straightforward cause I think.

```tsx
import Animated from 'react-native-reanimated'
import { Rect } from 'react-native-svg'

const AnimatedRect = Animated.createAnimatedComponent(Rect)
```

Please let me know if it's needed. In the meantime, I'll investigate a fix for a PR.

**Comment by nandorojo** [comment]
I think it's because the build step of `react-native-svg` from React Native Bob is turning the classes into functions to support older ES versions

<img width="942" alt="Screenshot 2023-01-25 at 3 43 22 PM" src="https://user-images.githubusercontent.com/13172299/214685963-bf9b36e6-788d-4e5b-abcb-03927a25e2c8.png">

**Comment by nandorojo** [comment]
In case anyone runs into this, I fixed it by doing this on Web:

1. Add `react-native-svg` to `next-transpile-modules`
2. Add this alias to your webpack config:

```ts
const nextConfig = {
 webpack(config, options) {
    config.resolve.alias['react-native-svg'] = 'react-native-svg/src'

    return config
  }
}
```

**Comment by javier545dev** [comment]
> In case anyone runs into this, I fixed it by doing this on Web:
> 
> 1. Add `react-native-svg` to `next-transpile-modules`
> 2. Add this alias to your webpack config:
> 
> ```ts
> const nextConfig = {
>  webpack(config, options) {
>     config.resolve.alias['react-native-svg'] = 'react-native-svg/src'
> 
>     return config
>   }
> }
> ```
> 
> By aliasing to the source code, we retain the classes themselves before they get turned into functions.

Hi, how to config react native svg for react webpack project?
