### ISSUE TITLE
npm was not the lastest code

### ISSUE THREAD

**Issue by MonsterDonkey** [software-mansion/react-native-svg#1977]
https://www.npmjs.com/package/react-native-svg?activeTab=explore

android/build.gradle code is not for rn-0.71.x

**Comment by WoLewicki** [comment]
Yes, since the release has been made before adding changes to `android/build.gradle`. It is available soon in v13.8.0 so I will close this issue. Feel free to comment here if something is wrong and we can always reopen it then.
