### ISSUE TITLE
Images are not loading on iOS using SvgFromUri or SvgUri

### ISSUE THREAD

**Issue by saulojoab** [software-mansion/react-native-svg#1978]
# Bug

Images are not loading using SvgFromUri or SvgUri on iOS. Android works fine.

<img width="867" alt="Captura de Tela 2023-01-30 às 02 34 29" src="https://user-images.githubusercontent.com/37988252/215395682-d717d324-a746-4d5a-8789-d5a6e59a2bcd.png">

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
 System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 86.50 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - /opt/homebrew/bin/npm
    Watchman: 2023.01.23.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 31, 33, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.1
      System Images: android-33 | Android TV ARM 64 v8a, android-33 | Google TV ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.70.1 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^13.1.0

## Steps To Reproduce

Simply import a SVG image from a URL.
This is the image: https://storagebekagm.blob.core.windows.net/app/avatars/Judge.svg

Describe what you expected to happen:

1. Image would show both in iOS and Android

## Short, Self Contained, Correct (Compilable), Example

```js
<SvgFromUri
            width={'30%'}
            height={'100%'}
            uri={urlToImage}
          />
```

**Comment by WoLewicki** [comment]
Can you provide a simple reproduction of the issue? It would be easier to work on it then.

**Comment by saulojoab** [comment]
@WoLewicki all I did was use the component with the URL I provided on the issue. That's all I'm doing.

**Comment by yasserkassem-aa** [comment]
It also happens to me, some of urls not loaded on iOS,
`        "react-native-svg": "^12.1.1",
        "react": "^17.0.2",
        "react-native": "^0.68.2"
`

example URL: https://cdn-staging.arabyads.com/boostiny-dev/categories/Food.svg

**Comment by tukaAlalami** [comment]
any solution ?

**Comment by WoLewicki** [comment]
Did you get an error? When I try those examples I get `[TypeError: Network request failed]`. Is it the same with you?

**Comment by saulojoab** [comment]
@WoLewicki i got no errors. 

sometimes the image would show up inverted and in a grid-like layout as well. for the moment we converted all remote svg images to png and used the default react-native Image component, which worked just fine.

**Comment by WoLewicki** [comment]
So should we close this issue then? I am not sure what should we do with it.

**Comment by ankitk-nimblechapps** [comment]
> I had the same problem yesterday. Update to version `react-native-svg@13.8.0` and it will work.

I am facing these issue in android getting [TypeError: Network request failed] as a result.

**Comment by bohdanprog** [comment]
Hello @ankitk-nimblechapps,
Can you provide a simple reproduction of the issue?

**Comment by Resource-4** [comment]
getting same issue [TypeError: Network request failed]
      <SvgUri
            style={styles.svgStyles}
            width="40"
            height="48"
            uri={
              Urls.CLOUDINARY_BASE_URL + "Vector_mbfzcr.svg"
            }
          />
