### ISSUE TITLE
toDataURL incorrectly contains line breaks

### ISSUE THREAD

**Issue by robrechtme** [software-mansion/react-native-svg#1986]
# Bug

The `toDataURL` method contains line breaks `\r\n`, which break the base64 string.

#### Unexpected behavior
This can lead to corrupted images when e.g. using it in [react-native-share](https://github.com/react-native-share/react-native-share).

## Environment info

Library version: 13.4.0

## Short, Self Contained, Correct (Compilable), Example

https://snack.expo.dev/@robrechtme/data-url-bug

**Comment by jakex7** [comment]
Hi! Could you check if #2272 resolves the issue?
