### ISSUE TITLE
Reanimated animated styles break rotations around a point

### ISSUE THREAD

**Issue by Zlass** [software-mansion/react-native-svg#1990]
# Bug

We've been using this to rotate an svg group around a center point.
```typescript
  const rotationDegree = useSharedValue(0);
  useEffect(() => {
    rotationDegree.value = withRepeat(
      withTiming(360, { duration: 72000, easing: Easing.linear }),
      -1
    );
  }, [rotationDegree]);

  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        { translateX: CENTER },
        { translateY: CENTER },
        { rotateZ: rotationDegree.value },
        { translateX: -CENTER },
        { translateY: -CENTER },
      ],
    };
  }, []);

return (
        <Svg fill="none" height="196" width="196" viewBox="0 0 196 196">
          <ReanimatedG style={animatedStyle}>
            <Rect fill="black" x="92" y="0" width="4" height="96" />
            <Circle
              cx="98"
              cy="98"
              originX="98"
              originY="98"
              r="96"
              stroke="black"
              strokeWidth="4"
            />
          </ReanimatedG>
        </Svg>
);
```
This was working perfectly fine in `12.4.3` but upgrading to `13.8.0` seems to have broken this animation code.

There is a similar bug #1968 which is just for a circle, but the bug I am seeing is on all animated components that use an `animatedStyle` from `reanimated`.

#### Unexpected behavior

Expected:
<img src="https://user-images.githubusercontent.com/2068677/220732261-f1a120c9-132c-4531-af74-621ec4eb097d.png" width=25% height=25%>

Current behaviour `v13.8.0`
<img src="https://user-images.githubusercontent.com/2068677/220732257-587e6618-bd6d-439a-80ce-3a15ea51240f.png" width=25% height=25%>

## Environment info

Library version: 13.8.0

## Steps To Reproduce

Reproducible example :
Use this animated style as a style prop on any reanimated SVG element and it does not behave correctly

```typescript
  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        { translateX: CENTER },
        { translateY: CENTER },
        { rotateZ: DEGREES },
        { translateX: -CENTER },
        { translateY: -CENTER },
      ],
    };
  }, []);
```

## Workaround
I have been able to solve this without downgrading by changing the transformation to

```typescript
  const animatedStyle = useAnimatedStyle(() => {
    return {
      transform: [
        { translateX: CENTER },
        { translateY: CENTER },
        { rotateZ: DEGREES },
        { translateX: -CENTER },
        { translateY: -CENTER },
        { translateX: 0 },
        { translateY: 0 },
      ],
    };
  }, []);
```

## Short, Self Contained, Correct (Compilable), Example
https://snack.expo.dev/u6vvVOHMG0

**Comment by bohdanprog** [comment]
Hello @Zlass,

https://github.com/software-mansion/react-native-svg/assets/69891500/c25101dc-04c1-425a-b60e-e235807c51f4

https://github.com/software-mansion/react-native-svg/assets/69891500/0bcc81b0-a6fc-4e8b-8210-9cda6b4171b2


I attempted to reproduce the issue, but I believe it has already been resolved. If you are still facing the problem, please feel free to open a new issue.

Thank you.
