### ISSUE TITLE
Animated image exception thrown while executing ui block 'childnode' is a required parameter. or connectanimatednodes animated node with tag (child) does not exist

### ISSUE THREAD

**Issue by manarfalah** [software-mansion/react-native-svg#1997]
using : 
  const AnimatedImage = Animated.createAnimatedComponent(Image);

              <AnimatedImage
                  height={zoomAnimatedValue.interpolate({
                    inputRange: [initialZoom, maxZoom],
                    outputRange: [80, 20],
                    extrapolate: 'clamp',
                  })}
                  width={zoomAnimatedValue.interpolate({
                    inputRange: [initialZoom, maxZoom],
                    outputRange: [80, 20],
                    extrapolate: 'clamp',
                  })}
                  x={zoomAnimatedValue.interpolate({
                    inputRange: [initialZoom, maxZoom],
                    outputRange: [Xrect - 80 / 2, Xrect - 20 / 2],
                    extrapolate: 'clamp',
                  })}
                  y={zoomAnimatedValue.interpolate({
                    inputRange: [initialZoom, maxZoom],
                    outputRange: [Yrect - 80 / 2, Yrect - 20 / 2],
                    extrapolate: 'clamp',
                  })}
                  href={borderImage}
                />

when I add the animated value to x,y I get error:
ios : exception thrown while executing ui block 'childnode' is a required parameter.
android : connectanimatednodes animated node with tag (child) does not exist

when I put fixed value like this: 

                x={Xrect}
                 y={Yrect}
it is wotking but I need to change the x and y of the image according to its width and height. 

hope some one can help me please ! 

thanks

**Comment by bohdanprog** [comment]
Hello @manarfalah 
Can you share a simple example to reproduce that issue? 
It will be easier to help you.
Thank you
