### ISSUE TITLE
No longer able to read svg file from android filesystem

### ISSUE THREAD

**Issue by Balintataw** [software-mansion/react-native-svg#2002]
# Bug

When updating react-native from 0.68.5 to 0.71.4, svg files no longer load when attempting to load from android filesystem. Works fine on iOS.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

USING: ```bash
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-fs": "^2.20.0",
    "react-native-svg": "^13.8.0"
```

React native info output:

```bash
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 84.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 9.1.3 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 13.8.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/Balintataw/android-filesystem-svg
2. yarn
3. npx react-native run-android
4. tap button
5. See error [Error: Fetching file:///data/user/0/com.androidfilesystemsvg/files/icon.svg failed with status 0]

Describe what you expected to happen:

Tapping the button should save an svg of a menu icon to a file 'icon.svg', then render that icon to the screen using SvgUri. This works on older versions however. I'm not sure exactly what combination of versions causes this issue. 
It was last known to work correctly using 
```
    "react": "17.0.2",
    "react-native": "0.68.5",
    "react-native-fs": "^2.16.6",
    "react-native-svg": "^12.3.0"
```

**Comment by WoLewicki** [comment]
It would be good to get to the exact versions of those libraries that made it broken. Are you sure it is an issue with how `react-native-svg` works?  @vicke4 could you also do some more testing when the response is still `ok` on `Android`?

**Comment by vicke4** [comment]
#1503 caused this issue. However, not sure how we can blame it as it's a simple `response.ok` check. 

I tested the API with a remote URI. Everything works fine on both Android and iOS. The issue occurs only on Android when you pass a local file as URI.
