### ISSUE TITLE
SVG blinking

### ISSUE THREAD

**Issue by Mistes974** [software-mansion/react-native-svg#2014]
I am encountering an issue with the react-native-svg library. When I use the `SvgXml `component or transform my SVG file with `react-svgr`, my SVG blinks repeatedly.

I have tried different methods to display my SVG in my React Native application, but the result is always the same. I'm wondering if anyone has encountered this issue before or has a solution to this problem?

Thank you in advance for your help!

https://user-images.githubusercontent.com/10241192/227541895-877cf2d2-3f25-479a-b2b5-2f67d9143562.mp4

The SvgComponent file (9k lines...) :
[Face2.js.zip](https://github.com/software-mansion/react-native-svg/files/11062905/Face2.js.zip)

EDIT 1: If i remove some `<Use />` tags (≈2000 lines) the blinking stops ... are there any limits ?
EDIT 2: The only solution i found is to use a webview to display it , and i inject some js to manipulate the svg like in a web app...

**Comment by bohdanprog** [comment]
Hello @Mistes974, 
I tried to show your SVG on that [page](https://www.svgviewer.dev/), but it didn't show anything,  I believe it's too big.
