### ISSUE TITLE
question: What is the minimum React-Native version supported by v13.x.x

### ISSUE THREAD

**Issue by mljlynch** [software-mansion/react-native-svg#2021]
# Question

In the release notes, it says you need to use react-native v0.69 to use fabric with V13.x.x. Can you clarify if that means v0.69 is the minimum capatible version with that package or if we can use earlier versions (currently, I'm on v0.68.)?

**Comment by ucheNkadiCode** [comment]
I have the same question @WoLewicki do you know the answer to this?

**Comment by WoLewicki** [comment]
As mentioned here: https://github.com/software-mansion/react-native-svg#support-for-fabric, we don't support RN v0.68 with Fabric, since there were so many changes between 0.68 and 0.69 that it did not make too much sense then. Does it answer your question?

**Comment by mljlynch** [comment]
No what I am asking is if we can use v13.x.x with RN v0.68 with the use of fabric.

**Comment by WoLewicki** [comment]
Yes, you can, as mentioned here: https://github.com/software-mansion/react-native-svg#supported-react-native-versions, you can use newest version with >=RN v0.64. Does it answer your question?
