### ISSUE TITLE
Please update examples to use proper Svg import

### ISSUE THREAD

**Issue by Romick2005** [software-mansion/react-native-svg#2023]
Please replace 
```
import Svg, {
  Path,
  Text,...
} from "react-native-svg";
```
with 
```
import {
  Path,
  Svg,
  Text,...
} from "react-native-svg";
```
in [usage examples](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md) to get rid off eslint no-named-as-default warnings/errors:
`Using exported name 'Svg' as identifier for default export  import/no-named-as-default`

![image](https://user-images.githubusercontent.com/17779660/229829779-f4031ca9-4c92-4614-858c-c57030d73520.png)

Also in [PointerEventsBoxNone.tsx](https://github.com/software-mansion/react-native-svg/blob/d31ffdb762d34171fd934ac97b031ccf5e0b645d/TestsExample/src/PointerEventsBoxNone.tsx#L4) and [Test1374.tsx](https://github.com/software-mansion/react-native-svg/blob/d31ffdb762d34171fd934ac97b031ccf5e0b645d/TestsExample/src/Test1374.tsx#L3)

**Comment by bohdanprog** [comment]
Hello @Romick2005,
I checked the PointerEventsBoxNone component but I didn't have any issues.
<image width="300" height="700" src="https://github.com/software-mansion/react-native-svg/assets/69891500/07d7c37d-65e6-4f4e-b398-57b30cc3172d" />

If you still have any problems feel free to open a new issue.
Thank you.

**Comment by Romick2005** [comment]
So what is the recommended way to import Svg component properly?
import Svg from "react-native-svg";
Or
import { Svg } from "react-native-svg"

What would you recommend @bohdanprog?

**Comment by Romick2005** [comment]
Please check this [line](https://github.com/software-mansion/react-native-svg/blob/0596fd9dc56057e5c74fef8865404aad8c26c35f/src/ReactNativeSVG.ts#L110) and [this](export default Svg;) to get more info for this case.

**Comment by bohdanprog** [comment]
@Romick2005 Thanks, I understand your point. I believe you can import the SVG in whichever way you prefer.

**Comment by Romick2005** [comment]
Agree. But we can update examples to demonstrate preferable usage which I believe is import { Svg } from "react-native-svg"
