### ISSUE TITLE
Shape.tsx: child.isClassAccessorProperty is not a function

### ISSUE THREAD

**Issue by kabeza** [software-mansion/react-native-svg#2029]
# Bug

I have a react-native project using latest version 0.71.2 and react-native-svg 13.9.0
The project compiles and runs fine on emulator, but fails when trying to generate a debug/release apk

PS: The react-native-svg library is required by native-base UI library, more specifically by Icon component, but I don't use it in all the code. But if I remove react-native-svg the app doesn't compile/run at all

command executed: 
`react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
`

Output:

`
error node_modules/react-native-svg/src/elements/Shape.tsx: /home/myuser/rnproject/node_modules/react-native-svg/src/elements/Shape.tsx: child.isClassAccessorProperty is not a function.
TypeError: /home/myuser/rnproject/node_modules/react-native-svg/src/elements/Shape.tsx: child.isClassAccessorProperty is not a function
    at /home/myuser/rnproject/node_modules/@babel/plugin-transform-typescript/lib/index.js:347:89
    at Array.forEach (<anonymous>)
    at PluginPass.Class (/home/myuser/rnproject/node_modules/@babel/plugin-transform-typescript/lib/index.js:340:31)
    at newFn (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/context.js:103:16)
    at TraversalContext.visitQueue (/usr/lib/node_modules/@react-native-community/cli/node_modules/@babel/traverse/lib/context.js:109:21)
info Run CLI with --verbose flag for more details.
`

## Tried

1. Removing node_modules and reinstall everything

2. downgrade packages
"@babel/core": "7.20.0" to "7.12.9"
"@babel/runtime": "7.20.0" to "7.12.5"

## Environment info

React native info output:

```
warn Package react-native-screens has been ignored because it contains invalid configuration. Reason: "dependency.platforms.android.componentDescriptors" is not allowed
info Fetching system and libraries information...
System:
    OS: Linux 5.4 elementary OS 5.1.7 Hera
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 4.05 GB / 15.50 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 32.1.0
      System Images: android-29 | Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: AI-203.7717.56.2031.7784292
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.2 => 0.71.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Thanks for any tip/workaround you may have

**Comment by emaan-riaz** [comment]
did you find a solution for this? I'm running into the same problem

**Comment by kabeza** [comment]
> did you find a solution for this? I'm running into the same problem

no luck yet 😭

**Comment by bohdanprog** [comment]
Hello @kabeza,
Can you share a simple example to reproduce that problem?

**Comment by kabeza** [comment]
> Hello @kabeza, Can you share a simple example to reproduce that problem?

Sorry, I've removed react-native-svg from the project and made it work with another library

**Comment by bohdanprog** [comment]
@kabeza We have closed that issue. If you encounter any other problems with react-native-svg, please feel free to open a new issue.

Thank you.
