### ISSUE TITLE
Some remote SVG url not load in library  

### ISSUE THREAD

**Issue by atologistdipak** [software-mansion/react-native-svg#2032]
# Bug

**SVG URL : - "https://storage.googleapis.com/sioinvest/Company%20Logos/Openai-1.svg"**

#### Unexpected behavior
```
 <SvgUri
          width={100}
          height={100}
          uri="https://storage.googleapis.com/sioinvest/Company%20Logos/Openai-1.svg"
 />

```
React native info output:

```bash
   "react": "17.0.2",
   "react-native": "0.68.2",
```

Library version: x.x.x
 "react-native-svg": "^12.3.0",
"react-native-svg-transformer": "^1.0.0",

**Comment by satyabhagavan** [comment]
Hi there are you able to find any solution for this.  I am trying to figure out the other alternatives but nothing seems working 

```
    "react-native": "0.71.8"
    "react-native-svg": "^13.9.0"
```

this is my versions. 

thanks in advance.

**Comment by bohdanprog** [comment]
Hello @satyabhagavan  @atologistdipak,
Unfortunately `react-native-svg` doesn't support style property in SVG.
Here is an example of how we can fix that:
It is the SVG XML:
```XML
<?xml version="1.0" encoding="UTF-8"?><svg fill="black" id="logosandtypes_com" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 150 150"><g id="Layer_3"><path id="Layer_3-2" d="M0,0H150V150H0V0Z"/></g><path  d="..."/></svg>
```

We have to remove that part: 
```
<path id="Layer_3-2" d="M0,0H150V150H0V0Z"/>
```
I have no idea why that SVG has some square over that image.

If you still have that problem after you've removed that part, feel free to reopen the issue.
