### ISSUE TITLE
OnPress for Path in SVG is not working and Mouse HoverIn and HoverOut is not present in Windows

### ISSUE THREAD

**Issue by NewChandan** [software-mansion/react-native-svg#2047]
# Bug

1. OnPress  for Path in SVG is not working 
2. OnMouseHoverIn and OnMosueHoverOut is not present 
3. onResponderMove should behave has OnMouseHoverIn and out

#### Unexpected behavior

(https://codesandbox.io/embed/react-native-svg-test-forked-8m58sg?fontsize=14&hidenavigation=1&theme=dark)

## Environment info
Windows platform

Library version: Latest

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.
OnPress for Path in SVG is not working and Mouse HoverIn and HoverOut is not present in Windows

Describe what you expected to happen:

1.OnPress for Path should work
2.Mouse HoverIn and HoverOut should be supported

**Comment by chzappsinc** [comment]
Any Updates?

**Comment by bohdanprog** [comment]
Hello @NewChandan @chrispader,

I attempted to reproduce the issue, and everything worked well for me. If you are still experiencing the problem, please provide a simple example to help us understand and address it.

Thank you.
