### ISSUE TITLE
Masked component is loosing precision, get pixelated

### ISSUE THREAD

**Issue by injecteer** [software-mansion/react-native-svg#2057]
In my app I have this code:

    <Svg width={W} height={H} viewBox="0 0 150 100" preserveAspectRatio="none">
      <Defs>
        <Mask id="mask" x={0} y={0} width={W} height={H} maskUnits="userSpaceOnUse">
          <Nested name="Path" d={path} animated stroke="white" fill="none" strokeLinejoin="round" strokeWidth={10} />
        </Mask>
      </Defs>
      
      
      <G mask="url(#mask)">
        <Path d={path} stroke="orange" strokeLinejoin="round" fill="none"/>
        {fields.map( f => <Nested key={f.id} {...f}/>)}
      </G>
      
      
      <G transform="translate(0 -20)">
        <Path d={path} stroke="orange" strokeLinejoin="round" fill="none"/>
        {fields.map( f => <Nested key={f.id} {...f}/>)}
      </G>
    </Svg>

where Nested is a delegation to Path, Circle and other RN-SVG elements.

# Bug

The G with mask (at the bottom) looks like so in the emulator or on real device:

![image](https://github.com/software-mansion/react-native-svg/assets/32952/3c3bf37b-5d7e-4408-92de-5a3a1da66aed)

in web-mode both Gs look crisp:

![image](https://github.com/software-mansion/react-native-svg/assets/32952/459f3602-4703-4f02-b647-857f025d638d)

Further info with screenshots see on Stackoverflow: https://stackoverflow.com/questions/76264610/react-native-svg-masked-elements-pixelated-in-android-emulator

# Library version: 13.4.0

## Steps To Reproduce

See the snack https://snack.expo.dev/@injecteer/react-native-svg-mask

**Comment by injecteer** [comment]
Any reaction to this?

Because of the bug the Mask is not usable at all!

**Comment by bohdanprog** [comment]
Hello @injecteer,
Could you please check on that issue? 
I am quite confident that it has already been resolved.

Thank you.

**Comment by injecteer** [comment]
Hi @bohdanprog,
I updated the above mentioned snack to use 15.2.0 and blur is still present on device or emulator

**Comment by jakex7** [comment]
Hey @injecteer, 
it has been fixed here: 7b5d4daaed9fd62d1b6a07ffb3742f56c49eda20 and released in `15.5.0`. However, it isn't available in the Expo SDK yet, so it won't work on Snack. To use the latest version of the library with Expo, you'll need to perform an Expo prebuild (see the [documentation](https://docs.expo.dev/workflow/prebuild/) for guidance).
