### ISSUE TITLE
Error setting property 'stroke' of RNSVGPath with tag #1: JSON value '{ payload = 4285358431; type = 0; }' of type NSMutableDictionary cannot be converted to NSArray

### ISSUE THREAD

**Issue by rschiffer** [software-mansion/react-native-svg#2068]
After updating `react-native-svg` from `12.5.1` to `13.4.0` the following Error pops up when building:

```
Error setting property 'stroke' of RNSVGPath with tag #1: JSON value '{ payload = 4285358431; type = 0; }' of type NSMutableDictionary cannot be converted to NSArray
```

The update of `react-native-svg` was done while upgrading the Expo SDK to 48. All works fine with `react-native-svg 12.5.1`.  

We couldn't figure out a working way to pass the `stroke` prop (components in use: `Path`, `Circle`, `Rect`).

**Comment by bohdanprog** [comment]
Hello @rschiffer,
Can you share a simple example to reproduce that issue?
Thank you.

**Comment by rschiffer** [comment]
Hi @bohdanprog! 
Thanks for reaching out! This issue did not pop up anymore for the more current Expo SDK versions. Hence, I think it could be closed.

**Comment by bohdanprog** [comment]
@rschiffer Feel free to open a new issue if you encounter any problems.
Thank you.
