### ISSUE TITLE
`prefetch` or `onLoad` for <Image />

### ISSUE THREAD

**Issue by scnroy** [software-mansion/react-native-svg#2073]
Hi all!

I'm using  [react-native-qrcode-svg](https://github.com/awesomejerry/react-native-qrcode-svg), which uses this package under the hood.

I'm [rendering a logo](https://github.com/awesomejerry/react-native-qrcode-svg#examples) in the middle of the QR Code via `require('./logo.png')`.  The QR code appears on a receipt layout, which is captured as an image via `react-native-view-shot` se we can either email it and/or send to a printer. This works great, however there is a race condition between capturing the screen shot and loading the logo image. I've been hunting for something like `<Image/>`'s [`onLoad`](https://reactnative.dev/docs/image#onload) event handler, and have also tried using `Image.prefetch()` without much success—perhaps because it's a local image?

Is there any way to know when the image is done loading or prefetch the image so that it renders on first pass when using your [image component](https://github.com/software-mansion/react-native-svg/blob/main/src/elements/Image.tsx)? I'd be happy to submit a PR to `react-native-qrcode-svg`, assuming we'd need to make the underlying API available.

Thanks!

**Comment by bohdanprog** [comment]
Hello @scnroy,
Currently, we are working on the implementation onLoad prop to the image component.
Here is [PR](https://github.com/software-mansion/react-native-svg/pull/2293)
