### ISSUE TITLE
This line still not fixed in 13.10.0

### ISSUE THREAD

**Issue by billnbell** [software-mansion/react-native-svg#2099]
https://github.com/software-mansion/react-native-svg/blob/0e931577ac9d9241be813bd9a7f03f71b7629ff0/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.h#L51

Please switch to 
```
return {imageSource, {imageSource, nullptr, SharedFunction<>(nullptr)}};
```

**Comment by bohdanprog** [comment]
Hello @billnbell,
Could you please explain why that approach is considered better?
Thank you.
```obj-c
return {imageSource, {imageSource, nullptr, SharedFunction<>(nullptr)}};
```

**Comment by billnbell3** [comment]
Yeah otherwise we get typescript errors, and it does not work.

**Comment by bohdanprog** [comment]
@billnbell Can you share an example of how we can reproduce that issue?
Because I've never had errors.

**Comment by billnbell3** [comment]
yes use new architecture.

```
cd ios && bundle install && NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 bundle exec pod install --repo-update && cd ..
```

**Comment by bohdanprog** [comment]
@billnbell What is the version of `react-native-svg` do you use?

**Comment by bohdanprog** [comment]
@billnbell  I ran the command that you sent. But I didn't get any errors.
<img width="1207" alt="Screenshot 2024-06-22 at 07 32 22" src="https://github.com/software-mansion/react-native-svg/assets/69891500/6c25293f-a404-4ade-9884-379e057f0150">
