### ISSUE TITLE
getting error while using getPointAtLength() function.

### ISSUE THREAD

**Issue by shellord** [software-mansion/react-native-svg#2105]
console.log(fullLineRef.current?.getPointAtLength(0));

`Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNSVGRenderableModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes`

**Comment by bohdanprog** [comment]
hello @shellord,
Can you share the example app to reproduce that issue?
Thank you
