### ISSUE TITLE
Some svg files are not load in react native

### ISSUE THREAD

**Issue by atologistdipak** [software-mansion/react-native-svg#2107]
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

import {SvgUri } from "react-native-svg";

`<SvgUri width={300} height={300} uri= {"https://storage.googleapis.com/sioinvest/Company%20Logos/Stripe-3.svg"} />`

# Bug

### SVG File url not load 

Please provide a clear and concise description of what the bug is.
Include screenshots if needed.
Please test using the latest release of the library, as maybe said bug has been already fixed.

#### Unexpected behavior

If you have unexpected behavior, please create a clean project with the latest versions of react-native and react-native-svg

```bash
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..
modify App.js -> run the app
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
"react-native": "0.68.2",
"react": "17.0.2",
 "react-native-svg": "^13.10.0",
 "react-native-svg-transformer": "^1.1.0",

```

Library version: x.x.x

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/user/rnsvg-bug-repro
2. cd rnsvg-bug-repro
3. yarn
4. yarn ios
5. yarn android
6. ...

![Screenshot_20230728-164356_SiO](https://github.com/software-mansion/react-native-svg/assets/71266588/0c758475-c6d2-47b5-ada9-be5a51a665ce)

**Comment by bohdanprog** [comment]
Hello @atologistdipak,
Do you still have that issue?
If you still have that issue, please share the example to reproduce that issue.
Thank you.
