### ISSUE TITLE
Pressable when wrapped over SVGUri, onPress is not working

### ISSUE THREAD

**Issue by Vikraantnegi** [software-mansion/react-native-svg#2108]
Pressable when wrapped over SVGUri, onPress is not working

```
<Pressable
          className="h-8 w-8 bg-primary items-center justify-center flex"
          onPress={onClick}
>
          <SvgUri uri={uri} height={24} width={24} />
</Pressable>
```

On clicking around the empty space of SVGUri, onPress is working, but when clicking on the svg its not working

**Comment by XantreGodlike** [comment]
We have the same issue

**Comment by bohdanprog** [comment]
Hello @Vikraantnegi @XantreDev,

Could you share an example app demonstrating how to reproduce the issue? I attempted to replicate it but was unsuccessful.

I believe this might not be the relevant issue. Please inform me if you are still experiencing this problem. Thank you.

**Comment by XantreDev** [comment]
@Vikraantnegi Do you have this bug now? 
I've used some workaround. I can try to replicate it if it still happens with @Vikraantnegi
