### ISSUE TITLE
SvgXml was not found in 'react-native-svg' (expo web)

### ISSUE THREAD

**Issue by Mhp23** [software-mansion/react-native-svg#2111]
# Bug

`SvgXml` not working in the web environment (it's ok for mobile) and  seems there isn't implementation or specific export for it in `ReactNativeSVG.web.ts` and cause to the following issue happening:

```bash
WARNING in '*/index.tsx'
export 'SvgXml' (imported as 'SvgXml') was not found in 'react-native-svg' (possible exports: Circle, ClipPath, Defs, Ellipse, ForeignObject, G, Image, Line, LinearGradient, Marker, Mask, Path, Pattern, Polygon, Polyline, RadialGradient, Rect, Stop, Svg, Symbol, TSpan, Text, TextPath, Use, WebShape, default)
```

## Environment info

**Expo web**

Expo SDK Version: `49.0.6` 

Library version: 13.9.0

**Comment by bohdanprog** [comment]
Hello @Mhp23,
Do you still have that issue?
Can you share the example to reproduce that?

**Comment by Mhp23** [comment]
Hi @bohdanprog,
After I faced the missing implementation for the web I used an alternative way (using [Svgr](https://github.com/gregberge/svgr) to transform svg code for RN) and I haven't tested it recently but based on the main branch it seems still not available for the web

**Comment by bohdanprog** [comment]
@Mhp23, I discovered that currently, we cannot utilize SvgXml in web applications. The reason behind this limitation is explained in detail [here.](https://github.com/software-mansion/react-native-svg/issues/1279#issuecomment-595269518) It's a bit tricky.

Rest assured, we have this on our roadmap, and we aim to implement it at the earliest opportunity. Stay in touch for further updates.

**Comment by bohdanprog** [comment]
Here is the main [thread](https://github.com/software-mansion/react-native-svg/issues/1279). 
We will inform everyone once any changes are made.
