### ISSUE TITLE
Color Prop Testing

### ISSUE THREAD

**Issue by cgibson-emesent** [software-mansion/react-native-svg#2113]
Hi, I've asked the following on StackOverflow. [https://stackoverflow.com/questions/76824476/react-native-svg-color-prop-testing](https://stackoverflow.com/questions/76824476/react-native-svg-color-prop-testing)

In summary, using the color prop and then testing in Jest is giving me a value that I wasn't expecting / know how to handle.

```
    Expected the element to have prop:
      color=14624048
    Received:
      color=4292814128
```
Any ideas on how this works? Thanks!

**Comment by jakex7** [comment]
Hi @cgibson-emesent, it looks like your StackOverflow question was removed, so I couldn't see the exact details. The colors you're referring to are processed by React Native's `processColor` function, which can yield different results for the same color depending on the platform it's executed on.

**Comment by jakex7** [comment]
As I mentioned earlier, the color is processed using the `processColor` function from `react-native`. You can utilize this function in your test to parse the color and compare the values. Here's an example:

```js
import { processColor } from 'react-native';

expect(iconSvg).toHaveProp("color", processColor("#DF2530"));
```
