### ISSUE TITLE
Scale/ ScaleX/ ScaleY does not work on iOS.

### ISSUE THREAD

**Issue by bagraercan** [software-mansion/react-native-svg#2116]
Hi everyone, is scale not available on ios? It works properly on android but the same code does not make any change on ios.

ImageBottomSheet  is an Svg file.

`  <View style={{ height: footerImageHeight }}>
                <ImageBottomSheet style={styles.footerImage} scaleX={footerScaleX} scaleY={footerScaleY}/>
    </View>
`

style class is below

`    footerImage: {
        height: "100%",
        width: "100%"
    }`

Does anyone have an idea?

**Comment by WoLewicki** [comment]
Can you give a simple repro for this? Parsing `scale` should be done on `JS` side so it seems weird for the behavior to differ between platforms.

**Comment by bagraercan** [comment]
@WoLewicki So, i hope that i understood you correct.
i have an svg file which name is **FooterImage** and  has **viewBox="0 0 360 40"**. The original size is **width:360, height:40**.
When i just call this file without any props. It looks like below.

`<FooterImage  />`
![image](https://github.com/software-mansion/react-native-svg/assets/50544758/c0cc8700-de8d-42b8-8d94-3cdcf1e469d5)
 As you see there is a space under the svg file. 
Then if i give the scaleY prop to this file It looks like below in android but has no effect on iOS.
in iOS it is still like above.

`<FooterImage scaleY={mediumScreen ? 2.15 : 1.93} />`

![image](https://github.com/software-mansion/react-native-svg/assets/50544758/51ec0c72-dd5e-4058-b4bf-375cdee24cd4)

Thanks

**Comment by bohdanprog** [comment]
Hello, @bagraercan.
Can you share a simple reproduction of that issue?
Thank you
