### ISSUE TITLE
Svg asset not loading properly for expo-web in nx-workspace without webpack

### ISSUE THREAD

**Issue by arishZype** [software-mansion/react-native-svg#2126]
# Bug

I am using react-native-svg for my expo-web project inside my nx-workspace.
In my workspace, I have mobile(react-native) and web(expo-web). 
Svg files work properly for my react-native app but they do not render properly for expo-web (react-native-web).

Earlier, I was using Webpack and inside webpack.config.js, I had the following configurations

```
  config.module.rules[1].oneOf.unshift({
    test: /\.svg$/,
    exclude: /node_modules/,
    use: [
      {
        loader: "@svgr/webpack",
        options: {
          svgoConfig: {
            plugins: [
              {
                name: "removeViewBox",
                active: false
              },
              {
                name: "removeUnknownsAndDefaults",
                active: false
              },
              {
                name: "convertColors",
                active: false
              },
              {
                name: "inlineStyles",
                params: {
                  onlyMatchedOnce: false
                }
              }
            ]
          }
        }
      }
    ]
  });
```

But now, due to some other incompatibilities with webpack, I have to use expo's default webpack and not customize it.
Hence, now I cannot add the above configurations in my webpack.config.js as it comes from @expo.

## Screenshots
Actual Svg looks like the following:
<img width="270" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/130343753/11ea53a6-db24-4b2d-b48e-e52fe9145211">

Incorrectly rendered svg in web looks like the following:
<img width="234" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/130343753/b31515c5-d44a-4b4e-893a-180c6f045b57">

## Environment Info
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.8.0 - /usr/local/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.19.1 - /usr/local/bin/npm
      Watchman: 2022.09.05.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.0 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    IDEs:
      Android Studio: 2022.1 AI-221.6008.13.2211.9619390
      Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
    npmPackages:
      @expo/metro-config: 0.10.7 => 0.10.7 
      babel-preset-expo: ~9.5.0 => 9.5.2 
      expo: 49.0.3 => 49.0.3 
      metro: 0.76.7 => 0.76.7 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.8 => 0.71.8 
      react-native-web: 0.18.12 => 0.18.12 
     nx => 16.4.0
     nx-cloud => 16.3.0
    Expo Workflow: managed

### react-native-svg => 13.13.0

Library version: 13.13.0

## Steps To Reproduce
1. create a new nx-workspace with the following command

> npx create-nx-workspace happynrwl --preset=react-native --appName=mobile

2. Create a new expo app in the workspace

> nx g @nx/expo:app my-app

3. Add the following svg to the assets folder of the lib

> https://shorturl.at/fPTV6

4. Use it in your code for mobile and web.

5. Run it in android and web and see the difference.

## Describe what you expected to happen:
1. Svgs to load in web as they do in mobile

**Comment by malikzype** [comment]
Facing the same issue, we are building an embedded react-native-web app using expo and facing the exact same issue. We have tried using SVGO as well but no luck. Can anyone please help?

**Comment by Pratish149** [comment]
I am also facing the same issue. Any solutions ?

**Comment by bohdanprog** [comment]
Hello @arishZype @malikzype  @Pratish149 ,
Can you share any examples of how we can reproduce that?

Thank you
