### ISSUE TITLE
Darkening of SVG fill colors when provided to 'currentColor'

### ISSUE THREAD

**Issue by ClayGriifith** [software-mansion/react-native-svg#2127]
# Bug

I have many SVGs in my application that are provided a color value with fill="currentColor" intended to color them. On simulator this seemingly works fine but in a physical device all SVGs colored this way are somewhat 'darker' than they should be. 

This is not the case for all colors in my app, only for the SVGs using currentColor.

I see that some fixes in 2022 solved for similar currentColor issues but I am using 13.13.0 and getting this effect. 

## Environment info

React native info output:

```bash
System:
  OS: macOS 13.0.1
  CPU: (8) arm64 Apple M1
  Memory: 72.94 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.12.1
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /opt/homebrew/bin/yarn
  npm:
    version: 8.19.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2022.11.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: false

```

Library version: x.x.x

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. add an .svg file to project with fill="currentColor" for fills
2. set color={"some hex code"} on the SVG called within some component (ex: <Images.BottomOut color={#FBFBFB} />)

Describe what you expected to happen:

1. I expect the color to match the hex value provided
2. It instead is darker in shade than it should be. This happens for any color applied.

## Screenshot

![Frame 35](https://github.com/software-mansion/react-native-svg/assets/46039053/315390b9-a98d-457d-9b0d-f4c2b67beda3)

**Comment by bohdanprog** [comment]
Hello @ClayGriifith,
Can you share the example app to reproduce that issue?
Thank you
