### ISSUE TITLE
Tranform function moves painted/UI-visible area to certian position but does not move clikable area (mouse click event).

### ISSUE THREAD

**Issue by AmolGuldagad** [software-mansion/react-native-svg#2134]
we are trying to create donut using SVG which will be user interactive like mouse click event & mouse hover event but we are facing issues below:

Transform function moves painted/UI-visible area to certain position but does not move clickable area (mouse click event).
Hover action is not available
Used packages as below:
"react-native-svg": "^13.13.0"
"react-native": "0.72.4"
 "@types/d3-shape": "3.1.2",
 "d3": "7.8.5",

PF code below:
[index.tsx.txt](https://github.com/software-mansion/react-native-svg/files/12608040/index.tsx.txt)
[package.json.txt](https://github.com/software-mansion/react-native-svg/files/12608041/package.json.txt)

Remove ".txt" from file extnesion 
# Bug

Tranform function moves painted/UI-visible area to certian position but does not move clikable area (mouse click event). 

#### Unexpected behavior

If you have unexpected behavior, please create a clean project with the latest versions of react-native and react-native-svg

```bash
react-native init CleanProject
cd CleanProject/
yarn add react-native-svg
cd ios && pod install && cd ..
modify App.js -> run the app
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/user/rnsvg-bug-repro
2. cd rnsvg-bug-repro
3. yarn
4. yarn ios
5. yarn android
6. ...

Describe what you expected to happen:

1.
2.

## Short, Self Contained, Correct (Compilable), Example

If you are having a problem with some code and seeking help, preparing a Short, Self Contained, Correct Example (SSCCE) is very useful. But what is an SSCCE?

It is all in the name, really. Take a look at each part. The version prepared for others to see should be:

Short (Small) - Minimise bandwidth for the example, do not bore the audience.
Self Contained - Ensure everything is included, ready to go.
Correct - Copy, paste, (compile,) see is the aim.
Example - Displays the problem we are trying to solve.

http://www.sscce.org/

**Comment by AmolGuldagad** [comment]
Hi Team - any updates on query above

**Comment by AmolGuldagad** [comment]
Hi Team - Please have a look on issue above.

**Comment by bohdanprog** [comment]
Hello @AmolGuldagad ,
Can you share the example app to reproduce that issue?
Thank you
