### ISSUE TITLE
Typescript 5.1.3 type issue 

### ISSUE THREAD

**Issue by mankybansal** [software-mansion/react-native-svg#2135]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@13.13.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/lib/extract/extractTransform.ts b/node_modules/react-native-svg/src/lib/extract/extractTransform.ts
index 3961868..1792413 100644
--- a/node_modules/react-native-svg/src/lib/extract/extractTransform.ts
+++ b/node_modules/react-native-svg/src/lib/extract/extractTransform.ts
@@ -68,17 +68,19 @@ export function transformsArrayToProps(
   transformObjectsArray: TransformsStyle['transform'],
 ) {
   const props: TransformProps = {};
-  transformObjectsArray?.forEach((transformObject) => {
-    const keys = Object.keys(transformObject);
-    if (keys.length !== 1) {
-      console.error(
-        'You must specify exactly one property per transform object.',
-      );
-    }
-    const key = keys[0] as keyof TransformProps;
-    const value = transformObject[key as keyof typeof transformObject];
-    props[key] = value;
-  });
+  if(Array.isArray(transformObjectsArray)) {
+    transformObjectsArray?.forEach((transformObject) => {
+      const keys = Object.keys(transformObject);
+      if (keys.length !== 1) {
+        console.error(
+          'You must specify exactly one property per transform object.',
+        );
+      }
+      const key = keys[0] as keyof TransformProps;
+      const value = transformObject[key as keyof typeof transformObject];
+      props[key] = value;
+    });
+  }
   return props;
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by crazyfraggle** [comment]
Just hit this exact issue as well. It seems from React Native 0.71.9, `string` is added to `TransformsStyle['transform']` which breaks the function above. 

However, it seems to me that the logic here is somewhat broken outside this function:

```ts
export function props2transform(
  props: TransformProps | undefined,
): TransformedProps | null {
  if (!props) {
    return null;
  }
  const extractedProps = Array.isArray(props)
    ? transformsArrayToProps(props)
    : props;
 ...
```

`TransformProps` is an object and will never be true for `Array.isArray(props)`.

It is used in `transformToMatrix` though, where the usage is properly type scoped.

**Comment by mankybansal** [comment]
Still seeing this issue on the latest.

**Comment by WoLewicki** [comment]
This hasn't been released yet so that might be the cause of it. Or are you using version from main @mankybansal ?

**Comment by mankybansal** [comment]
Oh whoops, didn't see there hasn't been a release yet. Is there an ETA for the next release?

**Comment by WoLewicki** [comment]
Not really, but I think I'll do it next week. Is it alright?

**Comment by mankybansal** [comment]
@WoLewicki, can you release this?
