### ISSUE TITLE
 Could not resolve all files for configuration ':react-native-svg:debugCompileClasspath'.

### ISSUE THREAD

**Issue by kundannetsetDemo** [software-mansion/react-native-svg#2137]
Could not resolve all files for configuration ':react-native-svg:debugCompileClasspath'.
![Screenshot 2023-09-19 at 3 12 18 PM](https://github.com/software-mansion/react-native-svg/assets/145329403/cebf82a3-87f4-40ef-b97a-85f91148c3da)

**Comment by last-hop** [comment]
hii @kundannetsetDemo I want to work on this issue please assign it to me

**Comment by kundannetsetDemo** [comment]
@last-hop

**Comment by last-hop** [comment]
hii @kundannetsetDemo  I was busy with some other stuff , I will surely look into it today .

**Comment by marvelous-ikechi** [comment]
Same error here

**Comment by marvelous-ikechi** [comment]
This is what my repositories looks like:

`repositories {
google ()
mavenCentral()
`

**Comment by last-hop** [comment]
@marvelous-ikechi what did you changed then , I tried by adding maven { url 'https://maven.google.com' } this , but app is just running normal  and  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.73.1",
    "react-native-reanimated": "3.6.1",
    "react-native-svg": "^14.1.0"
  },

**Comment by last-hop** [comment]
@marvelous-ikechi @kundannetsetDemo  i have added a maven { url 'https://maven.google.com' } and before that i cleand the project and re install node modules  and its running in my system i am not getting any build error here ,  also what version of SVG you guys used ..?

**Comment by marvelous-ikechi** [comment]
Adding that fixed it now. Just checked again and it works. I had abandoned it @last-hop

**Comment by last-hop** [comment]
alllRight  !! Hope that works  @kundannetsetDemo please Let me know
