### ISSUE TITLE
Wrong opacity behavior on android

### ISSUE THREAD

**Issue by burakgormek** [software-mansion/react-native-svg#2144]
# Bug

Android color blending is different from others if its parent view has an opacity style.

View -> background red, opacity 0.2
Svg -> fill red

**iOS:**
<img width="318" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/7578884/85fb6545-9e7e-4fc7-aefa-f07d715c598f">

**Android:**
<img width="326" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/7578884/6018d7a1-eead-4c92-81d9-1583d1ba4b16">

**Web:**
<img width="331" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/7578884/37770175-4088-409d-bed8-db784dd84841">

## Environment info

Library version: v13.14.0

## Steps To Reproduce

https://snack.expo.dev/LcGquw6tZ

**Comment by jakex7** [comment]
Hi @burakgormek,
It seems like it's not an issue of react-native-svg, but of react-native itself. Can be reproduced even with just a `View` component, so i suggest opening an issue there.
```tsx
<View style={{backgroundColor: 'red', opacity: 0.2, flex: 1}}>
  <View style={{backgroundColor: 'red', width: 100, height: 100}} />
</View>
```
<img width="809" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/39670088/3c328314-11f7-4471-9dcb-a9f4aa02c027">
