### ISSUE TITLE
Project with path ':ReactAndroid' could not be found in project ':react-native-svg'

### ISSUE THREAD

**Issue by dou-ni-wan-er** [software-mansion/react-native-svg#2150]
yarn start 

**:
* What went wrong:
A problem occurred evaluating project ':react-native-svg'.
> Project with path ':ReactAndroid' could not be found in project ':react-native-svg'.

http://www.sscce.org/

**Comment by FerHernandezT** [comment]
I have the same error when I put newArchEnabled = true in android/gradle.properties

**Comment by FerHernandezT** [comment]
Update to the latest version of react-native-svg and it's already working :smile:

**Comment by bohdanprog** [comment]
Hello @dou-ni-wan-er 
Do you still have that issue?
