### ISSUE TITLE
`onPress` firing even though parent's `display: 'none'`

### ISSUE THREAD

**Issue by szmarczak** [software-mansion/react-native-svg#2153]
```jsx
import { useEffect, useState } from 'react';
import { Pressable, Alert } from 'react-native';
import { Svg, Rect } from 'react-native-svg';

export default function App() {
	const [display, setDisplay] = useState('flex');

	useEffect(() => {
		setTimeout(() => setDisplay('none'), 1000);
	}, []);

	return (
		<Pressable onPress={() => Alert.alert('press')} style={{ display }}>
			<Svg width="100" height="100" viewBox="0 0 100 100">
				<Rect width="100" height="100" fill="black" />
			</Svg>
		</Pressable>
	);
}
```

<details>
<summary>Environment info</summary>

```
>npx react-native info
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: "(12) x64 AMD Ryzen 5 5600 6-Core Processor              "
  Memory: 17.01 GB / 31.91 GB
Binaries:
  Node:
    version: 20.2.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.7.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.5.33424.131 (Visual Studio Community 2022)
Languages:
  Java:
    version: 11.0.20.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

</details>

Library version: `13.13.0`

https://github.com/software-mansion/react-native-svg/assets/36894700/c8d40e7e-1743-43b3-bc99-b0ef5aecb8d8

<details>
<summary>screen1</summary>

![screen-20231015-190202 - frame at 0m3s](https://github.com/software-mansion/react-native-svg/assets/36894700/3198ef64-b011-4a2f-90d3-d19443c0d3b9)

</details>

<details>
<summary>screen2</summary>

![aaaa](https://github.com/software-mansion/react-native-svg/assets/36894700/97328014-672a-4472-b261-a8e49490a514)

</details>

<details>
<summary>screen3 (the alert should be not popping up)</summary>

![screen-20231015-190202 - frame at 0m5s2](https://github.com/software-mansion/react-native-svg/assets/36894700/82c3293f-6231-4d95-8f09-d72eb5ba874b)

</details>

Related with: https://github.com/software-mansion/react-native-svg/issues/794

**Comment by szmarczak** [comment]
Workaround: https://github.com/software-mansion/react-native-svg/issues/794#issuecomment-427225419

**Comment by jakex7** [comment]
Hi @szmarczak,
I think the issue is not valid anymore, however, if it is still not working for you, feel free to reopen the issue.

https://github.com/user-attachments/assets/df8d81ba-37ea-4841-972e-984e99cb2582
