### ISSUE TITLE
Failed builed on new arch Fabric on iOS (Did not find header RCTImagePrimitivesConversions.h)

### ISSUE THREAD

**Issue by vladimirevstratov** [software-mansion/react-native-svg#2154]
# Question

```
/node_modules/react-native-svg/apple/Elements/RNSVGImage.mm:36:9: 'react/renderer/imagemanager/RCTImagePrimitivesConversions.h' file not found

/node_modules/react-native-svg/apple/Elements/RNSVGImage.mm:36:9: Did not find header 'renderer/imagemanager/RCTImagePrimitivesConversions.h' in framework 'react' (loaded from '/Users/vladimir.evstratov/Library/Developer/Xcode/DerivedData/ShoppingList-cxwetcgtjsmprfcosczisbbsibkw/Build/Products/Debug-iphonesimulator/React-Core')

```
<img width="707" alt="Снимок экрана 2023-10-18 в 02 11 28" src="https://github.com/software-mansion/react-native-svg/assets/30527831/1eb839e5-127b-47b8-bc97-efa1cecb98e2">

I have a problem with building project on iOS with new arch enabled. 

System:
  OS: macOS 13.5.2
  CPU: (12) x64 Apple M2 Max
  Memory: 382.69 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.19.1
    path: ~/.nvm/versions/node/v16.19.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.19.1/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v16.19.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/vladimir.evstratov/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK:
    Android NDK: 21.4.7075529
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/vladimir.evstratov/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

**Comment by neosh11** [comment]
Any solution?

**Comment by WoLewicki** [comment]
Can you provide a small repo with reproduction so we can work on it?

**Comment by sohayb** [comment]
hello, I'm having the exact issue and it's currently a blocker for supporting the new architecture.
![Screenshot 2023-11-08 at 4 57 43 PM](https://github.com/software-mansion/react-native-svg/assets/2195533/c7c53d34-799c-4156-a23b-d02259a441ef)

Attached is a sample project, that has nothing in it, just the result of `npx react-native@0.72.6 init AwesomeProject` and then added `react-native-svg` to it. You just need to do a `yarn install` and `RCT_NEW_ARCH_ENABELD=1 bundle exec pod install` and then try to build for iOS and you can see the issue.

The main thing here is that in the `Podfile`, I'm using `use_frameworks! :linkage => :static` and the new architecture is enabled.

[AwesomeProject.zip](https://github.com/software-mansion/react-native-svg/files/13301660/AwesomeProject.zip)

**Comment by WoLewicki** [comment]
Can you check if #2175 solves the issue?
