### ISSUE TITLE
Cannot build tvOS app with the new architecture

### ISSUE THREAD

**Issue by sehyod** [software-mansion/react-native-svg#2172]
Hi! 👋 
      
Firstly, thanks for your work! 🙂

I am working on a project that uses a chart library, which relies on `react-native-svg`. The project should run on tvOS, and, while trying out the new architecture, with Fabric, I realised that the build was failing for the tvOS target.

<img width="240" alt="Screenshot 2023-11-09 at 15 46 21" src="https://github.com/software-mansion/react-native-svg/assets/58954208/469d7a80-59b2-4568-9717-34d628d77edb">

As you can see in the error message, it appears that there is some code needing a feature from tvos 12.0, while the version specified in the podspec file is only 11.0.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/RNSVG.podspec b/node_modules/react-native-svg/RNSVG.podspec
index 88afeb1..1084eae 100644
--- a/node_modules/react-native-svg/RNSVG.podspec
+++ b/node_modules/react-native-svg/RNSVG.podspec
@@ -19,7 +19,7 @@ Pod::Spec.new do |s|
   s.requires_arc    = true
 
   if fabric_enabled
-    s.platforms = { :osx => "10.14", ios: '12.4', tvos: '11.0' }
+    s.platforms = { :osx => "10.14", ios: '12.4', tvos: '12.0' }
     install_modules_dependencies(s)
 
     s.subspec "common" do |ss|
```

I am too new to the React Native world to know if this is a safe change or if there was a reason why the version was 11.0, so that's why I'm opening this issue to get your opinion.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by bohdanprog** [comment]
Hello, 
I was already implemented.
If you still have that issue, feel free to reopen the issue.
