### ISSUE TITLE
Inconsistent rendering of circle on Android and IOS

### ISSUE THREAD

**Issue by lit26** [software-mansion/react-native-svg#2174]
# Question

Hi, the rendering of nested svg is inconsistent between Android and ios.

To Reproduce
```tsx
import Svg, {Circle} from 'react-native-svg';

import React from 'react';
import {View} from 'react-native';

export default class SvgExample extends React.Component {
  render() {
    const size = 224.1;
    const strokeWidth = 22.41;
    const progressPercent = 40;
    const radius = (size - strokeWidth) / 2;
    const circum = radius * 2 * Math.PI;
    const svgProgress = 100 - progressPercent;
    const margin = 10;
    return (
      <View style={{position: 'absolute', height: 300, width: 300, top: 90}}>
        <Svg height="100%" width="100%" viewBox="0 0 100 100">
          <View style={{margin}}>
            <Svg width={size} height={size}>
              <Circle
                stroke={'blue'}
                fill="none"
                cx={size / 2}
                cy={size / 2}
                r={radius}
                strokeDasharray={`${circum} ${circum}`}
                strokeDashoffset={radius * Math.PI * 2 * (svgProgress / 100)}
                strokeLinecap="round"
                transform={`rotate(135, ${size / 2}, ${size / 2})`}
                strokeWidth={strokeWidth}
              />
            </Svg>
          </View>
        </Svg>
      </View>
    );
  }
}
```

Android pixel 2 screenshot
<img width="426" alt="Screen Shot 2023-11-10 at 3 40 17 PM" src="https://github.com/software-mansion/react-native-svg/assets/51225681/4421e71b-bb1d-44f2-ad10-19b659384fbf">
IOS 12 screenshot
![Simulator Screen Shot - iPhone 12 - 2023-11-10 at 15 40 11](https://github.com/software-mansion/react-native-svg/assets/51225681/db972d0f-59db-40f4-a6c2-786228f13b2b)

Thank you

**Comment by bohdanprog** [comment]
Hello @lit26, I tried to reproduce that issue but couldn't.
Let's know if you still have that issue, thank you.
| IOS | ANDROID |
|--------|--------|
|<img width='300' height='700' src="https://github.com/software-mansion/react-native-svg/assets/69891500/533eab2b-c34a-4e9d-85d0-0ad5100b9430"/> | <img width='300' height='700' src="https://github.com/software-mansion/react-native-svg/assets/69891500/54d17aed-8781-4542-92d9-db0a89beef4d"/> |
