### ISSUE TITLE
Cannot read property 'SvgWithCss' of undefined while using WithLocalSvg

### ISSUE THREAD

**Issue by manjuy124** [software-mansion/react-native-svg#2203]
# Bug

After updating the react native and react native svg packages to the latest version, we are not able to build the application.
We are getting build errors like in the screenshot
<img width="416" alt="Screenshot 2024-01-10 at 7 23 32 PM" src="https://github.com/software-mansion/react-native-svg/assets/29254928/d25f467a-54d4-4d80-a5df-79ebeef098d3">

<img width="411" alt="Screenshot 2024-01-10 at 7 40 04 PM" src="https://github.com/software-mansion/react-native-svg/assets/29254928/42c44c6d-1b38-4f8b-b3fd-53a9856e7fd3">

## Environment info

React native info output:
0.73.2

Library version: 14.1.0

## Steps To Reproduce

1. git clone https://github.com/manjuy124/RNLocalSvgIssue
2. cd RNLocalSvgIssue
3. yarn
4. yarn android

Describe what you expected to happen:

1. Expected local SVG to render

**Comment by LBMethodWorx** [comment]
I'm facing the same issue

**Comment by bohdanprog** [comment]
Hello @manjuy124  @LBMethodWorx,
Can you share the example to reproduce that issue?
I tried to reproduce that issue, but couldn't.
Thank you

**Comment by manjuge** [comment]
@bohdanprog  Have you tried this with the following repo (as mentioned in the Steps To Reproduce)?
https://github.com/manjuy124/RNLocalSvgIssue
