### ISSUE TITLE
react-native-svg not working with react native web

### ISSUE THREAD

**Issue by Prashant-Mobile-Server** [software-mansion/react-native-svg#2205]
Getting error when trying to load svg image from a local directory. It is working fine on mobile but has below issue when I try to run for **web**.

 **ERROR**
Uncaught runtime errors:
×
ERROR
The string contains invalid characters.
createElement@[native code]
createElement@
createInstance@
completeWork@
completeUnitOfWork@
performUnitOfWork@
workLoopSync@
renderRootSync@
recoverFromConcurrentError@
performConcurrentWorkOnRoot@
workLoop@
flushWork@
performWorkUntilDeadline@

### Made below changes to support on mobile:

**_custom.d.ts:_**
```
declare module '*.svg' {
  const content: React.FunctionComponent<React.SVGAttributes<SVGElement>>;
  export default content;
}

```

**_tsconfig.json:_**
```
{
  "compilerOptions": {
    "jsx": "react"
  },
  "extends": "@tsconfig/react-native/tsconfig.json",

  "include": ["**/*.ts", "**/*.tsx", "custom.d.ts"]
}

```

**Comment by bohdanprog** [comment]
Hello @Prashant-Mobile-Server ,
Can you share the example to reproduce that issue?
Thank you

**Comment by jkoutavas** [comment]
Here's an example of the failure: https://github.com/jkoutavas/react-native-web-sandbox/pull/1. Can we re-open this issue please?

**Comment by jkoutavas** [comment]
@bohdanprog

**Comment by bohdanprog** [comment]
Hello @jkoutavas,
I checked your example, but you didn't use react-native-svg in your repository. 
Also if you want to show SVG from file read [that](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#use-with-svg-files) please.

**Comment by jkoutavas** [comment]
@bohdanprog please see the PR branch :-)

**Comment by bohdanprog** [comment]
@jkoutavas Did you read [that](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#web-configuration) :) ?

**Comment by jkoutavas** [comment]
@bohdanprog okay. I carefully followed the documentation you pointed me at (I had some earlier documentation). And did [this commit](https://github.com/jkoutavas/react-native-web-sandbox/pull/1/commits/ac7456bd3f8778389ce9bceb36e861e4d23dd4ea) to the PR branch. I'm still having the same error.

Are you up for pulling my PR branch and debug things for me? I apologize if I am missing something super obvious, but, at least I provided an example to poke at. :-)

**Comment by jkoutavas** [comment]
@bohdanprog Am I hopeless? :-)

**Comment by jkoutavas** [comment]
@bohdanprog , can you expound on this from the web docs?

> Ensure that you have the proper configuration to parse flow files from @react-native/assets-registry/registry

**Comment by jkoutavas** [comment]
@bohdanprog I created the most simple example of the current failing state for integrating react-native-svg with react-native--web. See this PR's description as well as its diff, please.  https://github.com/jkoutavas/react-native-web-svg-sandbox/pull/1
