### ISSUE TITLE
Error using react-native-svg with Parcel

### ISSUE THREAD

**Issue by mikelgarciaurbina** [software-mansion/react-native-svg#2209]
# Bug

I am encountering an issue when trying to use the react-native-web library with Parcel. The specific error I am receiving is:

```bash
@parcel/core: Failed to resolve 'react-native/Libraries/Utilities/codegenNativeComponent' from
'./node_modules/react-native-svg/lib/module/fabric/RectNativeComponent.js'
```

<img width="851" alt="Screenshot 2024-01-17 at 21 45 42" src="https://github.com/software-mansion/react-native-svg/assets/17450954/d07fcc5e-b849-45ff-a419-d42283cfffa9">

This issue arises when attempting to integrate react-native-svg in a project that uses react-native-web with expo and Parcel as the bundler for a chrome extension. I have not found solutions in existing documentation or forums.

If anyone has experience or additional insights on setting up react-native-svg with Parcel, I would greatly appreciate your guidance or suggestions. Thank you!

**Comment by rafael-unloan** [comment]
Hey @mikelgarciaurbina, how did you manage to resolve this?
