### ISSUE TITLE
Build issue in React Native "new architecture" for iOS

### ISSUE THREAD

**Issue by tomrom-pomelo** [software-mansion/react-native-svg#2211]
I am getting a very similar issue to #2067 - the following error is produced when I try to build my app with the "new architecture". The build works without enabling new architecture.

CompileC /var/folders/bh/nz11vprd0rg3vbk_86cnsm300000gp/T/eas-build-local-nodejs/77121581-3a0f-4614-8f59-b9ddbfe8a9a7/build/clients/apps/mobile/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/x86_64/RNSVGImage.o /var/folders/bh/nz11vprd0rg3vbk_86cnsm300000gp/T/eas-build-local-nodejs/77121581-3a0f-4614-8f59-b9ddbfe8a9a7/build/clients/node_modules/react-native-svg/apple/Elements/RNSVGImage.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNSVG' from project 'Pods')

Exit status: 65

However, none of the recommendations in #2067 work. I am using react-native 0.72.6 and react-native-svg 14.1.0. I have tried removing/re-creating node_modules as mentioned in https://github.com/software-mansion/react-native-svg/issues/2067#issuecomment-1629104335

Any other recommendations?

**Comment by bohdanprog** [comment]
Hello @tomrom-pomelo,
Can you share the example to reproduce that issue?
Thank you.
