### ISSUE TITLE
snacks (from expo) with react-native-svg crash on native

### ISSUE THREAD

**Issue by chriscoomber** [software-mansion/react-native-svg#2214]
See e.g. the "open in snack" link in https://docs.expo.dev/versions/latest/sdk/svg/ which takes you to an example identical to this:

https://snack.expo.dev/@chris_whiterosemaths/svg-example

# Bug

Running the above snack will crash on iOS and Android, whether through the online simulator/emulator, or on a real device via expo go.

The crash is:

```
View config getter callback for component `RNSVGRect` must be a function (received `undefined`).
```

## Environment info

Whatever snack uses.

- expo: 49.0.0
- react-native-svg: 13.9.0

**Comment by khusharth** [comment]
Facing similar issue. 
Work fine with the following:
- `expo`: `48.0.0`
- `react-native-svg`: '`3.4.0`

**Comment by sospedra** [comment]
Same issue. Can be fixed using expo v48 but the latest Expo Go app doesn't support v48 anymore.

**Comment by bohdanprog** [comment]
Hello, @chriscoomber @khusharth @sospedra,
If you run that on expo go you have to use the last version of expo sdk.
