### ISSUE TITLE
Windows Release builds failing due to missing deps (Patch File Fix)

### ISSUE THREAD

**Issue by mat2718** [software-mansion/react-native-svg#2216]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@14.1.0` for the project I'm working on.

when building for release on react native windows this library fails due to missing dependencies that are listed for Debug but not in Release. this patch just adds the dependencies for release as well enabling a successful build. 😄 hope this helps!!

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/windows/RNSVG/RNSVG.vcxproj b/node_modules/react-native-svg/windows/RNSVG/RNSVG.vcxproj
index 11ad6f5..bd96537 100644
--- a/node_modules/react-native-svg/windows/RNSVG/RNSVG.vcxproj
+++ b/node_modules/react-native-svg/windows/RNSVG/RNSVG.vcxproj
@@ -120,6 +120,9 @@
     <ClCompile>
       <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
     </ClCompile>
+    <Link>
+      <AdditionalDependencies>dxguid.lib;WindowsApp.lib;%(AdditionalDependencies)</AdditionalDependencies>
+    </Link>
   </ItemDefinitionGroup>
   <ItemGroup>
     <ClInclude Include="BrushView.h" />
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by afonso-tsx** [comment]
bump, this works and is needed for windows support

**Comment by bohdanprog** [comment]
Hello @mat2718,
As I see the issue was resolved, can we close it?

**Comment by bohdanprog** [comment]
Hello @mat2718,
As I see it was already implemented.
Thank you.
