### ISSUE TITLE
React Native Svg Linear Gradient Not loading when redirecting to bottom navigation tab

### ISSUE THREAD

**Issue by oliviercperrier** [software-mansion/react-native-svg#2225]
# Bug
I have a SVG with a Linear Gradient Bg, when i use a flat color bg everything is fine.

I have this router (using expo-router):
- Tab Nav
     - Page One
     - Page Two 

Some Details:
- The SVG is on Page One.
- The root of my app is redirecting the user to page Two in the Tab Nav (First page that should be shown). 

If i open my app from the root (localhost:8081/), i get to Page Two and when i get to page one (by click in the tab nav), the SVG doesn't load, but the SVG element is in the DOM.

if i open my app from page two (localhost:8081/two) and then go to page one, the SVG load correctly.

I Added a video here: [Screen Recording 2024-02-19 at 2.01.11 PM.zip](https://github.com/expo/expo/files/14336057/Screen.Recording.2024-02-19.at.2.01.11.PM.zip)

In the video i first:

- Load the app from root and show the svg not loading,
- Then i load the app from page two and show that the svg is loading correctly

## Steps To Reproduce

```
1. git clone https://github.com/oliviercperrier/react-native-svg-linear-gradient-repro
2. npm install
3. npm run web
4. Load the app from the root `localhost:8081/`
5. Go to page one
6. SVG should be loading (but its not)
```

**Comment by oliviercperrier** [comment]
Up this is a big issue for my team

**Comment by anton-chikunov** [comment]
I had the same issue but on regular Stack navigation.
My app has root `Background` component with svg:
```
<View style={[styles.container, style]}>
        <Svg style={styles.svg}>
          <Defs>
            <SVGLinearGradient id="linear-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
              <Stop offset="0%" stopColor="#17171C" />
              <Stop offset="100%" stopColor="#17171C" />
            </SVGLinearGradient>
            <RadialGradient
              id="radial-gradient"
              cx="0%"
              cy="-7.81%"
              rx="125.18%"
              ry="61.5%"
              gradientUnits="userSpaceOnUse"
            >
              <Stop offset="0%" stopColor="#454554" />
              <Stop offset="100%" stopColor="rgba(23, 23, 28, 0)" />
            </RadialGradient>
          </Defs>
          <Rect x="0" y="0" width="100%" height="100%" fill="url(#linear-gradient" />
          <Rect x="0" y="0" width="100%" height="100%" fill="url(#radial-gradient" />
        </Svg>
        <View style={styles.innerContainer}>{children}</View>
      </View>
```

After navigating from first screen to second, background svg stops rendering. I guess it could be related to reconciliation process. I've managed to solve issue in next way:

```
 const [id, setId] = useState('');

  useEffect(() => {
    setId(uuid.v4().toString());
  }, []);

....

<View style={[styles.container, style]}>
        <Svg style={styles.svg}>
          <Defs>
            <SVGLinearGradient id={`linear-gradient-${id}`} x1="0%" y1="0%" x2="100%" y2="100%">
              <Stop offset="0%" stopColor="#17171C" />
              <Stop offset="100%" stopColor="#17171C" />
            </SVGLinearGradient>
            <RadialGradient
              id={`radial-gradient-${id}`}
              cx="0%"
              cy="-7.81%"
              rx="125.18%"
              ry="61.5%"
              gradientUnits="userSpaceOnUse"
            >
              <Stop offset="0%" stopColor="#454554" />
              <Stop offset="100%" stopColor="rgba(23, 23, 28, 0)" />
            </RadialGradient>
          </Defs>
          <Rect x="0" y="0" width="100%" height="100%" fill={`url(#linear-gradient-${id})`} />
          <Rect x="0" y="0" width="100%" height="100%" fill={`url(#radial-gradient-${id})`} />
        </Svg>
        <View style={styles.innerContainer}>{children}</View>
      </View>
```

I didn't try to use `key`, but I am sure that it may help too.

**Comment by bohdanprog** [comment]
Hello @oliviercperrier,

We have reviewed the issue. It appears that the problem is related to the Chrome engine blink. 
You can find more information about this issue at this link: https://issues.chromium.org/issues/40142085.

I believe the best solution would be to consider the workaround suggested by @anton-chikunov.
