### ISSUE TITLE
SvgUri can not load some of the svgs in both android and ios

### ISSUE THREAD

**Issue by UrvishaChandpara** [software-mansion/react-native-svg#2246]
**SvgUri can not fetch some of svgs.** 

for example:
https://cdn.coinranking.com/dSCnSLilQ/hedera.svg
https://cdn.coinranking.com/tU7Skyia9/ThorChain[1].svg

 npmPackages:
 react-native-svg:14.1.0
react:18.2.0
react-native:0.73.4

 <SvgUri
              width="32"
               height="32"
                uri={'https://cdn.coinranking.com/dSCnSLilQ/hedera.svg'}
/>

for some svg urls it gives exception error like this 
 ERROR  [SyntaxError: Expected ",", [ \t\r\n], or [eE] but "-" found.]
 ERROR  [SyntaxError: Expected ",", [ \t\r\n], or [eE] but "-" found.]
 ERROR  [SyntaxError: Expected ")", ",", [ \t\r\n], [0-9], or [eE] but "-" found.]
and svg not showing

**Comment by bohdanprog** [comment]
Hello @UrvishaChandpara,
Could you please share an example, because three of them work well.
Thank you
