### ISSUE TITLE
fetchText method error : TypeError: Cannot read property 'prototype' of undefined when trying to call svg from uri

### ISSUE THREAD

**Issue by YassineOujaa77** [software-mansion/react-native-svg#2256]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-svg@13.4.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-svg/src/xml.tsx b/node_modules/react-native-svg/src/xml.tsx
index c6f1799..cf09c94 100644
--- a/node_modules/react-native-svg/src/xml.tsx
+++ b/node_modules/react-native-svg/src/xml.tsx
@@ -28,6 +28,8 @@ import ClipPath from './elements/ClipPath';
 import Pattern from './elements/Pattern';
 import Mask from './elements/Mask';
 import Marker from './elements/Marker';
+import axios from 'axios';
+
 
 export const tags: { [tag: string]: ComponentType } = {
   svg: Svg,
@@ -125,11 +127,10 @@ export function SvgXml(props: XmlProps) {
 }
 
 export async function fetchText(uri: string) {
-  const response = await fetch(uri);
-  if (response.ok) {
-    return await response.text();
-  }
+ const response = await axios.get(uri)
+ if(response.status = 200) return await response.data;
   throw new Error(`Fetching ${uri} failed with status ${response.status}`);
+ 
 }
 
 export function SvgUri(props: UriProps) {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by bohdanprog** [comment]
Hello @YassineOujaa77 :)
Can you share the example of code how we can reproduce that error, thank you.

**Comment by YassineOujaa77** [comment]
Hello @bohdanprog , 
This is the code that reproduces the error : 

`const QRcode = ({ data, size }: IQRcodeFrameProps) => {
    return (
        <AppView position="relative">
            <SvgUri width={size} height={size} uri={data} /> // this return TypeError: Cannot read property 'prototype' of undefined
        </AppView>
    );
};`

**Comment by bohdanprog** [comment]
@YassineOujaa77 can you provide some `data`?
That  you put to:
```
<SvgUri uri={data}/>
```

Thank you

**Comment by YassineOujaa77** [comment]
Hey @bohdanprog , 
I put a simple svg url , like this one : https://svgsilh.com/svg/1295198.svg

**Comment by bohdanprog** [comment]
Hey @YassineOujaa77,
As I see we already fixed that in the next version of the library, could you update `react-native-svg` and check if you still have that error?

**Comment by bohdanprog** [comment]
@YassineOujaa77 We can close that issue, right?
