### ISSUE TITLE
HTML entities contained in an XML string are not decoded by the SvgXml component

### ISSUE THREAD

**Issue by hellonobug9** [software-mansion/react-native-svg#2257]
This is the XML string I have which consist of two HTML entities in the tspan tag

Everything functions perfectly when I use this string in react-svgr.com; the entities are immediately decoded.

![image](https://github.com/software-mansion/react-native-svg/assets/66345242/0e6a2fdd-e9ff-4641-89b1-11d4c64e62c9)

However, the text is presented in the encoded version when I use this string as an xml prop in the SvgXml component.

**Comment by bohdanprog** [comment]
Hello @hellonobug9,
Could you provide an example to reproduce that issue, thank you.
