### ISSUE TITLE
Path not rendering correctly

### ISSUE THREAD

**Issue by ashwin-jacob** [software-mansion/react-native-svg#2258]
# Bug

After upgrading from React Native SVG 13.4.0 to 14.1.0, we are running into rendering issues specifically using Path. One specific Path is causing a small black trace, while every other path I render doesn't.

**What Expo is showing**
![CleanShot 2024-04-16 at 13 41 02](https://github.com/software-mansion/react-native-svg/assets/1770694/06179d07-fdcb-4459-995e-0ff6a04cbcdb)

**What it should be**
![CleanShot 2024-04-16 at 13 54 38](https://github.com/software-mansion/react-native-svg/assets/1770694/e3d227f6-2cf5-4ec2-9bd0-c41bfdc58443)

## Code
```
      <Svg viewBox="0 0 310 248">
        <Path
          d={'M 22.5 154.99999999999997 A 150 132.5 0 0 1 89.47 39.83'}
          stroke={'#FF6E52'}
          strokeWidth="14"
          strokeLinecap="round"
        />
      </Svg>
```

## Environment info

Expo Version: 50.0.0
Library version: 14.1.0

## Short, Self Contained, Correct (Compilable), Example
https://snack.expo.dev/@ashwin-soundadvice/54245a?platform=web

**Comment by jakex7** [comment]
Hello @ashwin-jacob,
I've been looking into this and according to the MDN Docs, if you don't specify the `fill` prop (on the `path` element) should be set to `black` by default. This means the component works as expected (according to the specification). I checked the code you posted, and it works exactly the same in the browser. If you want to achieve the results you have posted, all you need to do is add `fill="transparent"` to the `path` element. 

<img width="1099" alt="image" src="https://github.com/software-mansion/react-native-svg/assets/39670088/cfa88381-d139-4700-93c3-bfdfa6eb9324">

If you've noticed any other problems, feel free to open an issue.
