### ISSUE TITLE
SVG image not import in React native

### ISSUE THREAD

**Issue by wolfxpertlab** [software-mansion/react-native-svg#2261]
![Screenshot 2024-04-20 at 10 16 14 AM](https://github.com/software-mansion/react-native-svg/assets/124674978/c73388ed-f1c9-43cf-bc73-d990ccd29786)

My All svg image not show path that show error is

Cannot find module '../assets/svg/dashboardcart.svg' or its corresponding type declarations.

how can I solved it please help when I think that show error after installing firebase app and firestore before work better without install firebase 

my declaration.d.ts file is:

declare module "\*.svg" {
  import React = require("react");
  const ReactComponent: React.FC<React.SVGProps<SVGSVGElement>>;
  export default ReactComponent;
}

my tsconfige file is:

{
  "compilerOptions": {
    "jsx": "react-jsx",
    "lib": ["DOM", "ES2022"],
    "moduleResolution": "node",
    "target": "ES2022"
  },
  "include": ["src/types/declarations.d.ts","declarations.d.ts"],
  "files": ["declarations.d.ts"],
  "extends": "@react-native/typescript-config/tsconfig.json"
}

**Comment by rodrigodiasf1984** [comment]
+1

**Comment by rodrigodiasf1984** [comment]
i've solve the problem with this: 
![image](https://github.com/software-mansion/react-native-svg/assets/30758309/afd88bc8-b3c4-4a9f-aeec-eefd03ecc156)

**Comment by bohdanprog** [comment]
Hello @wolfxpertlab,
Do you still have that issue?
As I see it can be the problem with typescript configuration.
If you still have that issue, Can you share a simple example to reproduce that issue?
Thank you.

**Comment by nzcodarnoc** [comment]
I'm having this problem on a fresh install of RN 0.76.5 with react-native-svg 15.10.1

**Comment by jakex7** [comment]
Hi @nzcodarnoc, could you please provide a minimal reproduction repository?
