### ISSUE TITLE
ForeignObject works with panResponder?

### ISSUE THREAD

**Issue by mbaviera** [software-mansion/react-native-svg#2264]
I'm trying to drag/drop a Text into a ForeignObject with panResponder, but it's not working. Is there any way to do this or is not supported?

![Captura de Tela 2024-04-22 às 17 53 07](https://github.com/software-mansion/react-native-svg/assets/26506097/520522a0-07fe-4a20-8359-c932faac7239)

**Comment by bohdanprog** [comment]
Hello @mbaviera,
Can you share with us the example to reproduce that issue, please?
Thank you.
