### ISSUE TITLE
Error "ViewPropTypes" undefined in svg.js file 

### ISSUE THREAD

**Issue by codetobuild** [software-mansion/react-native-svg#2267]
![WhatsApp Image 2024-04-30 at 9 07 14 PM](https://github.com/software-mansion/react-native-svg/assets/65239963/0e6f9e71-dc4c-4f6f-a156-946f1297bbc2)

Kindly look into this issue and is there any solution to get around this to overcome this error.
Thanks

**Comment by bohdanprog** [comment]
Hello @codetobuild,
Can you share with us the example to reproduce that issue, please?
Thank you.
