### ISSUE TITLE
Unspecified behaviour of the translate prop

### ISSUE THREAD

**Issue by MichalGniadek** [software-mansion/react-native-svg#2335]
# Question

Hi, I saw that there is a `translate` prop that is behaving rather strangely ([Snack](https://snack.expo.dev/SjBHTlEDKhPxuFE4CcvUt)):

```
<Svg height="100" width="100">
  {/* Translated */}
  <Circle r="50" fill="green" translate={[50, 50]} />
  {/* Not translated */}
  <Circle x="0" y="0" r="50" fill="red" translate={[50, 50]} />
  <Circle r="40" fill="yellow" />
</Svg>
<Svg height="100" width="100">
  {/* Not translated */}
  <Rect width={50} height={50} fill="red" />
  {/* Not translated */}
  <Rect width={40} height={40} fill="yellow" translate={[50, 50]} />
</Svg>
```

- I don't think this is specified in svg spec
- On Web this prop works as I would expect
- On iOS/Android this works _only_ on `Circle` when there aren't `x` and `y` specified

Should this be fixed/removed/mentioned in docs?

**Comment by bohdanprog** [comment]
Hello @MichalGniadek,
here is a [snack](https://snack.expo.dev/@bohdan.artiukhov/translate-prop) example of how it should work.
If you have any other questions, please don't hesitate to ask.
