### ISSUE TITLE
Symbol not found in new architecture

### ISSUE THREAD

**Issue by rovoskarl** [software-mansion/react-native-svg#2349]
### Description

I used RCT_NEW_ARCH_ENABLED=1 bundle exec pod install to develop a new architecture, and many components of react-native-svg reported errors that could not find symbols.
![image](https://github.com/software-mansion/react-native-svg/assets/26296949/0ebea01e-1dd6-4ff4-9791-0c37f617da3e)

### Steps to reproduce

1. RCT_NEW_ARCH_ENABLED=1 bundle exec pod install 
2. yarn ios

### Snack or a link to a repository

https://stackoverflow.com/help/minimal-reproducible-example

### SVG version

15.3.0

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by rovoskarl** [comment]
I tried but it didn't help

**Comment by bohdanprog** [comment]
Oki, could you provide an example app of how we can reproduce that?
Because I tried two different projects and it worked well.

**Comment by rovoskarl** [comment]
https://github.com/rovoskarl/demo Please see this repository Run yarn pod-install Then run yarn ios

**Comment by rovoskarl** [comment]
@bohdanprog

**Comment by bohdanprog** [comment]
@rovoskarl I couldn't setup your project for some reason.
Could you provide a simple example? 
You could check our fabric-example app in our repository, and everything worked well.

**Comment by rovoskarl** [comment]
all right

**Comment by bohdanprog** [comment]
@rovoskarl  However, if you are still encountering that error, please let us know. Since you provided an example from your private project, I was unfortunately unable to set it up.
