### ISSUE TITLE
CSS variables do not work

### ISSUE THREAD

**Issue by petterw03** [software-mansion/react-native-svg#2380]
### Description

SVG markup that make use of CSS variables does not work.

### Steps to reproduce

1. Render SVG markup that includes a CSS variable. The SVG example below is fully valid and should display a red rectangle.

```
import * as React from 'react';
import { SvgCss } from 'react-native-svg/css';

const xml = `
  <svg width="32" height="32" viewBox="0 0 32 32" id="mySVG">
    <style>
      #mySVG {
        --my-color: #ff0000;
      }
    </style>
    <rect fill="var(--my-color)" x="0" y="0" width="32" height="32" />
  </svg>
`;

export default function SvgComponent() {
  return (
    <SvgCss xml={xml} height="100%" width="100%" />
  );
}
```

2. The rectangle is not shown at all.

### Snack or a link to a repository

https://snack.expo.dev/kVoKWoPI8MAlGNaUXM2md

### SVG version

15.2.0

### React Native version

0.74.0

### Platforms

Android, iOS, Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by bohdanprog** [comment]
That PR was merged, that feature will be available in the next release ;)

**Comment by petterw03** [comment]
Awesome, thanks for addressing this!
