### ISSUE TITLE
RNSVGImageComponentDescriptor compile r

### ISSUE THREAD

**Issue by MmyzFlowerDog** [software-mansion/react-native-svg#2406]
### Description

![image](https://github.com/user-attachments/assets/1f1a9c01-ccc7-4a1c-8b90-829a6e693615)

### Steps to reproduce

install svg and then run

### Snack or a link to a repository

https://github.com/software-mansion/react-native-svg.git

### SVG version

15.0.0

### React Native version

0.72.0

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

ios 17.4 xcode 15.3 rn 0.72

### Acknowledgements

Yes

**Comment by MmyzFlowerDog** [comment]
> @MmyzFlowerDog Can you provide a simple example of the reproduction of that problem?

In my RN branch, I add "react-native-svg": "15.0.0". After install it, I Introduce this dependency into the iOS project. When I run my ios project, it show this error. Should I provide a Demo for it?

**Comment by bohdanprog** [comment]
> > @MmyzFlowerDog Can you provide a simple example of the reproduction of that problem?
> 
> In my RN branch, I add "react-native-svg": "15.0.0". After install it, I Introduce this dependency into the iOS project. When I run my ios project, it show this error. Should I provide a Demo for it?

If you could provide a repository with a simple example demonstrating how we can reproduce your problem, it would make it easier for us to assist you. I haven't encountered any issues myself.

<img width="1742" alt="Screenshot 2024-08-14 at 09 17 25" src="https://github.com/user-attachments/assets/8b5d49e3-ed29-46b5-88ef-4b3f68b13a3d">

**Comment by MmyzFlowerDog** [comment]
> > > @MmyzFlowerDog Can you provide a simple example of the reproduction of that problem?
> > 
> > 
> > In my RN branch, I add "react-native-svg": "15.0.0". After install it, I Introduce this dependency into the iOS project. When I run my ios project, it show this error. Should I provide a Demo for it?
> 
> If you could provide a repository with a simple example demonstrating how we can reproduce your problem, it would make it easier for us to assist you. I haven't encountered any issues myself.
> 
> <img alt="Screenshot 2024-08-14 at 09 17 25" width="1742" src="https://private-user-images.githubusercontent.com/69891500/357713345-8b5d49e3-ed29-46b5-88ef-4b3f68b13a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjAzMjAsIm5iZiI6MTcyMzYyMDAyMCwicGF0aCI6Ii82OTg5MTUwMC8zNTc3MTMzNDUtOGI1ZDQ5ZTMtZWQyOS00NmI1LTg4ZWYtNGIzZjY4YjEzYTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzUzMGZlY2NhNTUxZGU5NTFhOWVjODQwNjdjZWQxMWZhYzRlOTBmOGM3MGYxZWIyNGM3NTEyYjUxNDYxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fstnlP7SXaLRjNHP7pUYQyXWxN1UzoB2AgpFxBdUjcs">

could you please change your rn version from 0.74.2 to 0.72.13 and make RCT_NEW_ARCH_ENABLED=1 ? Our project is a tlilttle bit complex, which will take some time to create a simple project 。T_T

**Comment by bohdanprog** [comment]
> > > > @MmyzFlowerDog Can you provide a simple example of the reproduction of that problem?
> > > 
> > > 
> > > In my RN branch, I add "react-native-svg": "15.0.0". After install it, I Introduce this dependency into the iOS project. When I run my ios project, it show this error. Should I provide a Demo for it?
> > 
> > 
> > If you could provide a repository with a simple example demonstrating how we can reproduce your problem, it would make it easier for us to assist you. I haven't encountered any issues myself.
> > <img alt="Screenshot 2024-08-14 at 09 17 25" width="1742" src="https://private-user-images.githubusercontent.com/69891500/357713345-8b5d49e3-ed29-46b5-88ef-4b3f68b13a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjAzMjAsIm5iZiI6MTcyMzYyMDAyMCwicGF0aCI6Ii82OTg5MTUwMC8zNTc3MTMzNDUtOGI1ZDQ5ZTMtZWQyOS00NmI1LTg4ZWYtNGIzZjY4YjEzYTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzUzMGZlY2NhNTUxZGU5NTFhOWVjODQwNjdjZWQxMWZhYzRlOTBmOGM3MGYxZWIyNGM3NTEyYjUxNDYxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fstnlP7SXaLRjNHP7pUYQyXWxN1UzoB2AgpFxBdUjcs">
> 
> could you please change your rn version from 0.74.2 to 0.72.13 and make RCT_NEW_ARCH_ENABLED=1 ? Our project is a tlilttle bit complex, which will take some time to create a simple project 。T_T

I can't alter my React Native version because that project has other dependencies, and at the very least, the podfile appears different. When you create an issue, we usually request a repository with a straightforward example.

It appears that you might be utilizing a new architecture. That's why I recommend updating both libraries React Native and React Native SVG, as this is crucial.

**Comment by MmyzFlowerDog** [comment]
> > > > > @MmyzFlowerDog Can you provide a simple example of the reproduction of that problem?
> > > > 
> > > > 
> > > > In my RN branch, I add "react-native-svg": "15.0.0". After install it, I Introduce this dependency into the iOS project. When I run my ios project, it show this error. Should I provide a Demo for it?
> > > 
> > > 
> > > If you could provide a repository with a simple example demonstrating how we can reproduce your problem, it would make it easier for us to assist you. I haven't encountered any issues myself.
> > > <img alt="Screenshot 2024-08-14 at 09 17 25" width="1742" src="https://private-user-images.githubusercontent.com/69891500/357713345-8b5d49e3-ed29-46b5-88ef-4b3f68b13a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MjAzMjAsIm5iZiI6MTcyMzYyMDAyMCwicGF0aCI6Ii82OTg5MTUwMC8zNTc3MTMzNDUtOGI1ZDQ5ZTMtZWQyOS00NmI1LTg4ZWYtNGIzZjY4YjEzYTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA3MjAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzUzMGZlY2NhNTUxZGU5NTFhOWVjODQwNjdjZWQxMWZhYzRlOTBmOGM3MGYxZWIyNGM3NTEyYjUxNDYxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fstnlP7SXaLRjNHP7pUYQyXWxN1UzoB2AgpFxBdUjcs">
> > 
> > 
> > could you please change your rn version from 0.74.2 to 0.72.13 and make RCT_NEW_ARCH_ENABLED=1 ? Our project is a tlilttle bit complex, which will take some time to create a simple project 。T_T
> 
> I can't alter my React Native version because that project has other dependencies, and at the very least, the podfile appears different. When you create an issue, we usually request a repository with a straightforward example.
> 
> It appears that you might be utilizing a new architecture. That's why I recommend updating both libraries React Native and React Native SVG, as this is crucial.

thansk for your replay～～ Seems we cant not use svg in react native 0.72

**Comment by bohdanprog** [comment]
@MmyzFlowerDog  maybe you could try to update react-native-svg to the last version?

**Comment by MmyzFlowerDog** [comment]
> @MmyzFlowerDog maybe you could try to update react-native-svg to the last version?

15.

> @MmyzFlowerDog maybe you could try to update react-native-svg to the last version?

I have tried v15.5.0 but also get this error, the code of the file with compilation errors looks the same with 15.0.0

**Comment by bohdanprog** [comment]
@MmyzFlowerDog
I found an [issue](https://github.com/facebook/react-native/issues/41699) in react-native, and some [PRs](https://github.com/search?q=repo%3Afacebook%2Freact-native+ComponentDescriptor%3A%3Aadopt&type=pullrequests) which fixed your problem.

**Comment by MmyzFlowerDog** [comment]
thanks for you reply, the RP seems to solve the "adopt" in ComponentDescriptor 
![image](https://github.com/user-attachments/assets/36b46076-d964-4cdf-8de2-c4ac31fefba1)
but the file in react-native 0.72 even donot have this code 
![image](https://github.com/user-attachments/assets/32da5091-70c2-48cd-be9a-31954c139afc)
It looks like rn 0.73 makes a change here.

**Comment by MmyzFlowerDog** [comment]
> @MmyzFlowerDog I found an [issue](https://github.com/facebook/react-native/issues/41699) in react-native, and some [PRs](https://github.com/search?q=repo%3Afacebook%2Freact-native+ComponentDescriptor%3A%3Aadopt&type=pullrequests) which fixed your problem.

thanks for you reply, the RP seems to solve the "adopt" in ComponentDescriptor

**Comment by MmyzFlowerDog** [comment]
> @MmyzFlowerDog I found an [issue](https://github.com/facebook/react-native/issues/41699) in react-native, and some [PRs](https://github.com/search?q=repo%3Afacebook%2Freact-native+ComponentDescriptor%3A%3Aadopt&type=pullrequests) which fixed your problem.

Thanks for you reply, the RP seems to solve the "adopt" in ComponentDescriptor
![image](https://github.com/user-attachments/assets/3b24d7c5-a2b7-4207-81ce-e2dd9f104a56)

but the file in react-native 0.72 even does not have this code
![image](https://github.com/user-attachments/assets/f7b736c0-31a9-444f-8cee-0491d4b3226b)

It looks like rn 0.73 makes a big change here.

**Comment by bohdanprog** [comment]
@MmyzFlowerDog Can we close that issue?

**Comment by MmyzFlowerDog** [comment]
> @MmyzFlowerDog Can we close that issue?

sure, thanks for your time again

**Comment by xueqiulou** [comment]
> > @MmyzFlowerDog Can we close that issue?
> 
> sure, thanks for your time again

Hello, how did you ultimately resolve your issue?
