### ISSUE TITLE
react-native-svg crashing in release 

### ISSUE THREAD

**Issue by hosseinmd** [software-mansion/react-native-svg#2413]
### Description

The main issue is here:
https://github.com/callstack/repack/issues/115
We got this error on release mode
`TypeError: Cannot read property 'descriptors' of undefined`

that was because of ```import { SvgCssUri } from 'react-native-svg/css';```

### Steps to reproduce

Add this code to your react-native code 
```import { SvgCssUri } from 'react-native-svg/css';```
build release mode with repack

### Snack or a link to a repository

https://github.com/callstack/repack/issues/115

### SVG version

15.4.0

### React Native version

0.74.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by bohdanprog** [comment]
Hello @hosseinmd,
please provide a minimal reproduction repository if you are facing this issue.
