### ISSUE TITLE
Possible Breaking Change on Web in 15.5.0

### ISSUE THREAD

**Issue by jspizziri** [software-mansion/react-native-svg#2418]
### Description

[This commit](https://github.com/software-mansion/react-native-svg/commit/2da02cf2593feb8b03489aebfbf992be918d2197) which was released on `v15.5.0` [introduces a dependency on `@react-native/assets-registry`](https://github.com/software-mansion/react-native-svg/commit/2da02cf2593feb8b03489aebfbf992be918d2197#diff-03231aad50dc4f73ccebb4bdd9a851fd13c31530ae3216dcd3dcb1c1aa5757e7R7) which previously didn't exist.

`@react-native/assets-registry` is a transitive dependency of `react-native` but is _NOT_ a transitive dependency of `react-native-web`. Therefore, in web contexts, an error is thrown due to the missing dependency.

### Steps to reproduce

Setup a _bare_ `react-native-web` project that depends on `react-native-svg@15.5.0` and does _NOT_ install `react-native`. This seems to only happen in non-expo contexts.

### Snack or a link to a repository

working on it

### SVG version

15.5.0

### React Native version

0.74.5

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by FurySwordXD** [comment]
Can reproduce this issue on RNSVG 15.6.0

**Comment by jonstuebe** [comment]
I've gotta say, seems like we could have a test added to make sure web support isn't broken on release right?

**Comment by jspizziri** [comment]
@jonstuebe , I'm sure the maintainers would welcome a PR from you adding such a test 😄

**Comment by bohdanprog** [comment]
> I've gotta say, seems like we could have a test added to make sure web support isn't broken on release right?

It seems like the same problem as [here](https://github.com/expo/expo/issues/21469).
The best solution for that problem now is to:

Install [this dependency](https://github.com/expo/expo/issues/21469#issuecomment-1455354158).
If you are using Next.js, you need to [transpile](https://github.com/expo/expo/issues/21469#issuecomment-1789599778) @react-native/assets-registry/registry. I guess you can configure it [here](https://github.com/shawnmclean/sovoli/blob/main/apps/sovoli.com/next.config.js#L30).

**Comment by bohdanprog** [comment]
@shawnmclean If you have any questions let us know ;)

**Comment by johnf** [comment]
FYI: I tried transpiling via next.js, but that doesn't seem to work. I think it's because it's a flow file with a .js extension and not typescript.

I ended up patching registry.js instead.

**Comment by bohdanprog** [comment]
> FYI: I tried transpiling via next.js, but that doesn't seem to work. I think it's because it's a flow file with a .js extension and not typescript.
> 
> I ended up patching registry.js instead.

Can you share an example of how you tried transpiling via next.js?

**Comment by johnf** [comment]
I added the package to transpilePackages in next.config.mjs (I already have other entire in there so I know it's working). I tried a couple of options
* @react-native/assets-registry
* @react-native/assets-registry/registry
* @react-native/assets-registry/registry.js

None of these made any difference.

**Comment by bohdanprog** [comment]
Hello @johnf, sorry it took a while. I found the solution to your problem.
here is my configuration for the next.js project.

```ts
/** @type {import('next').NextConfig} */

const path = require("path");

const nextConfig = {
  experimental: {
    turbo: {
      resolveAlias: {
        "react-native": "react-native-web",
      },
      resolveExtensions: [
        ".web.js",
        ".web.jsx",
        ".web.ts",
        ".web.tsx",
        ".mdx",
        ".tsx",
        ".ts",
        ".jsx",
        ".js",
        ".mjs",
        ".json",
      ],
    },
  },
  webpack: (config) => {
    config.module.rules.push({
      test: /\.(js|jsx|ts|tsx)$/,
      include: [
        path.resolve(__dirname, "src"),
        path.resolve(
          __dirname,
          "node_modules/@react-native/assets-registry/registry"
        ),
      ],
      use: {
        loader: "babel-loader",
        options: {
          cacheDirectory: true,
          presets: ["module:metro-react-native-babel-preset"],
          plugins: ["react-native-web"],
        },
      },
    });
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      // Transform all direct `react-native` imports to `react-native-web`
      "react-native$": "react-native-web",
    };
    config.resolve.extensions = [
      ".web.js",
      ".web.jsx",
      ".web.ts",
      ".web.tsx",
      ...config.resolve.extensions,
    ];
    return config;
  },
};

module.exports = nextConfig;

```

**Comment by stevenwchien** [comment]
@bohdanprog Thank you for posting your fix. However, even with the next.config.js you recommended, I'm still running into this issue. I was wondering if you could share the versions of all of the relevant packages you are using, like react-native-web, react-native, nextjs, etc.

Thank you!
