### ISSUE TITLE
SvgViewManager.java:396: error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by zwang62** [software-mansion/react-native-svg#2428]
### Description

When I updated the svg to latest version, there is a build issue in the Android.

![WechatIMG291](https://github.com/user-attachments/assets/3c2690cc-16df-432a-b774-2f34e682b922)

Im not good at andorid,but, I think there might be an issue with this overridden method. The method in BaseViewManager only has two parameters?
![image](https://github.com/user-attachments/assets/43b63a29-5337-4c82-b379-6a453bc8ed3e)

![image](https://github.com/user-attachments/assets/9555b679-158d-465e-940c-597f5e3841a5)

### Steps to reproduce

1. Update react-native-svg to the latest version.
2. Sync and build on android platform.

### Snack or a link to a repository

None

### SVG version

15.6.0

### React Native version

0.72.9

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by dangthequan** [comment]
To fix this issue, downgrade version to 15.5.0. 
At version 15.6.0, there is an error which caused by overriding the setTransformProperty method in the SvgViewManager class but that method does not override or implement a method from a supertype.

**Comment by codexdevbrn** [comment]
Your version of react native is probably in conflict with react-native-svg, downgrade until you find one that is compatible.

**Comment by moonquddus** [comment]
For anyone else who has this issue, I'm on React Native 0.72.17 and I had to downgrade to 14.2.0

**Comment by frankie303** [comment]
for me `15.5.0` worked fine  with RN `0.72.15`

**Comment by compwron** [comment]
I am also having this issue at work (from a dependabot upgrade)
```
"node_modules/react-native-svg": {
      "version": "15.6.0",
```

`"react-native": "0.71.8",`
