### ISSUE TITLE
SVG Component Showing Blank After Updating to Version 15.4.0

### ISSUE THREAD

**Issue by aljadan** [software-mansion/react-native-svg#2449]
### Description

After updating to React Native SVG version 15.4.0, everything works as expected except for one specific SVG component, which appears blank

| 15.3.0 | 15.4.0 |
|--------|--------|
| ![Screenshot 2024-09-14 at 4 31 07 PM](https://github.com/user-attachments/assets/1aec4640-899e-4909-bd13-717c1cd354ea) | ![Screenshot 2024-09-14 at 4 25 31 PM](https://github.com/user-attachments/assets/065eb7ad-9bde-4dc6-8ef7-10afd28e210d) | 

### Steps to reproduce

1- Build the application for iOS/Android using version 15.4.0
2- Open the application on a simulator (both iOS and Android)
3- Observe that the SVG component appears blank

### Snack or a link to a repository

https://github.com/aljadan/react-native-svg-issue

### SVG version

15.4.0

### React Native version

0.74.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by TomCorvus** [comment]
Did you try to update to 15.5.0 version? I saw this in changelog https://github.com/software-mansion/react-native-svg/pull/2345

**Comment by jakex7** [comment]
Hi @aljadan,
I tested your icon on the latest version, v15.8.0, following the recent fixes, and everything is working as expected. Let me know if it’s working on your end or if there's anything that needs to be fixed.

**Comment by aljadan** [comment]
Hello @jakex7
Everything is working as expected, thank you so much for all your hard work
