### ISSUE TITLE
[15.7.0] missing types

### ISSUE THREAD

**Issue by efstathiosntonas** [software-mansion/react-native-svg#2453]
### Description

After upgrading to 15.7.0 the  types are missing because this line:

https://github.com/software-mansion/react-native-svg/blob/1ca8edd6d2ada9f1c1f92de77db2090c3d6317c7/package.json#L13

should be(?): ` "types": "lib/typescript/src/index.d.ts",`

![Screenshot 2024-09-17 at 12 50 25](https://github.com/user-attachments/assets/68d5326b-a4bf-4b9f-9caf-d4c8c6a2ceea)

### Steps to reproduce

1. upgrade to 15.7.0
2. boom, no types

### Snack or a link to a repository

none

### SVG version

15.7.0

### React Native version

0.75.3

### Platforms

Android, iOS, macOS, Web

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by vovkasm** [comment]
Actually issue does contain enough info. It's enough to compare value of "types" field in `package.json` and actual file locations in node_modules after installing.

**Comment by vovkasm** [comment]
This issue most probably related to https://github.com/software-mansion/react-native-svg/commit/a089cc2efcbea01de1a2b87c852b09d525a105ae#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R24 which include additional folders to `tsconfig.json`, now `bob` builds not only `src` content, but also `e2e` and do not do folder aggregation ;-)

**Comment by efstathiosntonas** [comment]
Thanks @jakex7 for the quick fix!

**Comment by jakex7** [comment]
Hello,  
thank you for reporting this issue so quickly. I was able to resolve it in #2454, and the fix has been included in the `v15.7.1` release.
