### ISSUE TITLE
Float to Double conversion bug for Radius values on Android

### ISSUE THREAD

**Issue by gorkemogut** [software-mansion/react-native-svg#2462]
### Description

Start getting error on radius styling for <Svg> objects on Android after updating package from 15.6.0 to 15.7.1.

When we set radius on a Svg object through styling like; 

```
<Svg style={{
        width: 80,
        height: 80,
        borderRadius: 40
    }}></Svg>
```
Android crashes;
<img width="328" alt="Screenshot 2024-09-20 at 09 16 25" src="https://github.com/user-attachments/assets/8ae8af67-0163-49e8-8ead-19399f8412ee">

### Steps to reproduce

1. Create <Svg> object 
2. Give radius from styles on it
3. Conversion warning and crashes

### Snack or a link to a repository

https://github.com/software-mansion/react-native-svg/blob/main/apps/examples/index.tsx

### SVG version

15.7.1

### React Native version

0.75.3

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Pixel 8 Pro API 34

### Acknowledgements

Yes

**Comment by gorkemogut** [comment]
Workaround: Using a View as wrapper and giving radius to the View

**Comment by bahadiraraz** [comment]
same issue

**Comment by mkondurPPGT** [comment]
same issue

**Comment by BertLammers** [comment]
Having the same issue after updating to react-native 0.75.3
