### ISSUE TITLE
[ANDROID] app crashes using SvgXml with borderRadius style RN@0.75.4

### ISSUE THREAD

**Issue by petros-g** [software-mansion/react-native-svg#2479]
### Description

Library update from 12.1.1 to latest, causing crash while using borderRadius to SvgXml component.

Error: java.lang.float cannot be cast to java.lang.double

![Screenshot_1728564730](https://github.com/user-attachments/assets/b51dfa27-9782-483e-a7c2-1fd292f265ff)

### Steps to reproduce

1. Adding borderRadius style to SvgXml component crashes each time

### Snack or a link to a repository

N/A

### SVG version

15.7.1

### React Native version

0.75.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Paper (Old Architecture)

### Build type

Debug app & dev bundle

### Device

Android emulator

### Device model

Pixel 2 XL

### Acknowledgements

Yes

**Comment by bohdanprog** [comment]
Hello @petros-g,
Thank you for letting us know about that problem.
That issue was solved in that [PR](https://github.com/software-mansion/react-native-svg/pull/2415).

**Comment by 1880akshay** [comment]
@bohdanprog @jakex7 is there any plan to release a stable version with this fix? I can see that a couple of pre release versions have been published with this issue fixed. I am currently blocked on upgrading React Native version to 75.

**Comment by jakex7** [comment]
Hey @1880akshay, a new version ([v15.8.0](https://github.com/software-mansion/react-native-svg/releases/tag/v15.8.0)) that includes this fix was released yesterday.
