### ISSUE TITLE
Update `warnUnimplementedFilter` to new version info. 

### ISSUE THREAD

**Issue by leo6104** [software-mansion/react-native-svg#2523]
### Description

Thanks for nice project. Recently new release supports FeBlend & FeFlood. 

Its `warnUnimplementedFilter` util still mentioin FeBlend & FeFlood. 

https://github.com/software-mansion/react-native-svg/blob/2a58016ec11bfbfe42b1581e789f266c7e81b2db/src/lib/util.ts#L24 

### Steps to reproduce

Just see `util.ts` 

https://github.com/software-mansion/react-native-svg/blob/2a58016ec11bfbfe42b1581e789f266c7e81b2db/src/lib/util.ts#L24 

### Snack or a link to a repository

https://snack.expo.io/

### SVG version

15.8.0

### React Native version

0.76.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

,

### Acknowledgements

Yes

**Comment by jakex7** [comment]
Thank you @leo6104,
The fix has been merged and will be included in the upcoming release.
