### ISSUE TITLE
Broken 'UIGraphicsBeginImageContextWithOptions' on macOS

### ISSUE THREAD

**Issue by gabrieldonadel** [software-mansion/react-native-svg#2528]
### Description

On react-native-macos 0.76, `UIGraphicsBeginImageContextWithOptions` and other `UIGraphics` directives were removed and we should now use `RCTUIGraphicsImageRenderer`

 more details in https://github.com/microsoft/react-native-macos/pull/2209/

Error:
```
/Users/gabriel/Workspace/expo/ExpoMenuBar/node_modules/react-native-svg/apple/Elements/RNSVGSvgView.mm:366:3: Use of undeclared identifier 'UIGraphicsBeginImageContextWithOptions'
```

### Steps to reproduce

1. create an new project using react-native-macos >= 0.76
2. Add react-native-svg
3. try to compile

### Snack or a link to a repository

https://github.com/expo/orbit

### SVG version

15.8.0

### React Native version

0.76.1

### Platforms

macOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by rwwaskk** [comment]
Bumping this issue. Still seeing it in react-native@latest
