### ISSUE TITLE
Installing react-native-svg with expo on development build results in RNSVGSvgView unimplemented component

### ISSUE THREAD

**Issue by daBack** [software-mansion/react-native-svg#2550]
### Description

Hey!
I saw a thread back 2.5 years ago with an issue "unimplemented component: <RNSVGSvgView>. Though it seemed to be resolved.

I am using expo and development build. If I use expo go, it works fine, however with development build I get the issue above.

I also tried setting the metro config js file to no avail:

```
const { getDefaultConfig } = require("expo/metro-config");

module.exports = (() => {
  const config = getDefaultConfig(__dirname);

  const { transformer, resolver } = config;

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve("react-native-svg-transformer/expo"),
  };
  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext) => ext !== "svg"),
    sourceExts: [...resolver.sourceExts, "svg"],
  };

  return config;
})();

```

### Steps to reproduce

1. Install with `npx expo install react-native-svg`
2. import `import Svg, { Circle, Rect } from "react-native-svg";`
3. Tried to use it.

Expected result: Display the svg
Actual outcome: Unimplemented component.

### Snack or a link to a repository

https://snack.expo.dev/@dabaack/react-native-svg

### SVG version

15.8.0

### React Native version

0.76.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

Expo Dev Client

### Architecture

None

### Build type

None

### Device

Real device

### Acknowledgements

Yes

**Comment by jakex7** [comment]
Hey @daBack,  
I tested your example on a fresh `create-expo-app` project, and everything appears to be working fine. Have you confirmed that you've installed the pods and created a new development build after adding the library?

**Comment by tyewang** [comment]
The exact same thing is happening to me as well on a relatively fresh Expo project. Confirmed I installed the pods with `npx pod-install` and created a new development build with `npx expo start`.

**Comment by daBack** [comment]
@jakex7 Hey! Thank you for trying it out. I did what you said as well, I installed a new build as @tyewang said, with npx expo run, and with expo run:ios.

I still get the same outcome when I scan the qr code and tries to open it up on my phone. Do I need to create a new build via EAS as well?

**Comment by daBack** [comment]
Yes, it was the EAS build that was required. I didn't fully understand what the difference was between npx expo run build and EAS. Hopefully this can be a good thread for another new lost react native expo developer in the future :D Thanks guys!

**Comment by muqige** [comment]
Hello! When I installed the react-native svg in the react-native project, the svg diagram could not be displayed properly. When I implemented various methods, the interface continued to display unimplemented component:<RNSVGSvgView>. How did you solve it

**Comment by jakex7** [comment]
Hey @muqige, since this is a native library, you'll need to create a new development/EAS build after installing it. If you're working with a bare React Native project, you'll need to reinstall pods and rebuild the project.

**Comment by muqige** [comment]
Hello, @jakex7, is this right, after creating a blank project, install react-native svg, cd ios, and execute pod install? I tried this, and still it said "unimplemented component: <RNSVGSvgView>"
![WechatIMG273307](https://github.com/user-attachments/assets/158c3d8b-138b-4211-8dba-d9cd52a8505f)

**Comment by jakex7** [comment]
@muqige could you set up and share a repository with this fresh project so I can verify if the issue persists on my end?

**Comment by muqige** [comment]
@jakex7  thank you very much for your help, I have uploaded my project to git, you can open my homepage, the project name is "testReactsvg"

**Comment by jakex7** [comment]
@muqige I reviewed your Git project and noticed that `react-native-svg` is missing from your `package.json`. Are you certain that all the necessary changes have been included in the reproduction repository?

**Comment by muqige** [comment]
@jakex7  Sorry, the code was not updated completely yesterday, I just mentioned the code again, now package.json contains svg package,

**Comment by jab-r** [comment]
Has anyone solved this? I have the same problem...

**Comment by daBack** [comment]
> Yes, it was the EAS build that was required. I didn't fully understand what the difference was between npx expo run build and EAS. Hopefully this can be a good thread for another new lost react native expo developer in the future :D Thanks guys!

@jab-r and @muqige: Are you, as me, running expo? In that case, I had to do the `EAS build`, wait for it to finish building, and then it worked! Then the pods are uploaded correctly, since its native. Want to explain the steps you've made?
