### ISSUE TITLE
[15.9.0] Crash on iOS with SVG containing feComposite called by SvgXml

### ISSUE THREAD

**Issue by TomCorvus** [software-mansion/react-native-svg#2552]
### Description

Hello,

Since 15.9.0, I have a crash on IOS with a SVG called with `SvgXml`.
I tried some manipulation like remove `feComposite` tags and the app doesn't crash.
No problem on Android (debug and release)

Thank you

### Steps to reproduce

1. Clone
2. expo run:ios

### Snack or a link to a repository

https://github.com/TomCorvus/RNSVG

### SVG version

15.9.0

### React Native version

0.76.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

None

### Build type

Debug app & production bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by jakex7** [comment]
Hey @TomCorvus,
Thank you for reporting this, can confirm that there is an issue with `FeComposite` when not all arguments (k1, k2, k3, k4) are provided. I will release the fix as soon as possible. In the meantime, as a workaround, you can add `k1="0" k4="0"` to each `FeComposite` to ensure all values are passed (0 is the default).

**Comment by TomCorvus** [comment]
Thank you @jakex7!

**Comment by fbp93** [comment]
@jakex7 LMK if you prefer that I open a new issue, but I thought it could be related to this

**Comment by jakex7** [comment]
Hey @fbp93, there's no need to create a new issue since it's related to the same crash and requires the same fix.
