### ISSUE TITLE
currentColor not using correct color sometimes

### ISSUE THREAD

**Issue by believer** [software-mansion/react-native-svg#2566]
### Description

We have SVG icons that use `currentColor` for strokes and fills. These are styled using [NativeWind](https://www.nativewind.dev) which sets the color on the SVG.

In the screenshots below, both SVGs display that the `color` property is defined as `rgba(171, 171, 171, 1)` in light mode and `rgba(94, 94, 94, 1)` in dark mode. But, the left icon is clearly using some other color. They should both look like the right icon.

Reloading the app solves the problem temporarily.

We don't remember that this was happening before we upgraded to the New Architecture, so there might be something related with that?

| Light | Dark |
| ------ | ----- |
| ![Screenshot 2024-12-05 at 14 25 49](https://github.com/user-attachments/assets/2a09776c-a9f3-43af-8649-e3d6a58e0ad7) | ![Screenshot 2024-12-05 at 14 24 51](https://github.com/user-attachments/assets/4f20d46d-8f22-41ee-9050-d00e985119fe) |

### Steps to reproduce

Unfortunately, we don't have a clear reproduction.

1. Use `react-native-svg-transformer` to convert imported SVGs
2. Set `color` property of imported SVGs
3. Navigate around and some icons might loose their connection to the defined color

### Snack or a link to a repository

-

### SVG version

15.10.0

### React Native version

0.76.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native

### Architecture

Fabric (New Architecture)

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by Dunedubby** [comment]
Not sure if this is the same issue, but we've also recently noticed that navigating around (particularly when doing a `navigation.reset`) causes `getCurrentColor` to completely crash out the app. When you say navigate, are you using `react-navigation`?

**Comment by Dunedubby** [comment]
As clarification: we are also occasionally seeing the same issue where SVGs revert back to some default color that isn't the one specified in the component tree. It also happens pretty randomly.

**Comment by believer** [comment]
Yes, we are using `react-navigation` and we've also seen crashes related to `getCurrentColor` so that could definitely be something.

**Comment by jakex7** [comment]
Hey, I've never come across that bug before, so please provide a minimal reproduction (can't be random), otherwise I won't be able to debug it

**Comment by believer** [comment]
Will try to create a reproduction of it next week!

**Comment by gituser8796** [comment]
@jakex7 we just experienced the exact same crash and also noticed the issue with incorrect colors, but only on iOS (Android works fine), react-native@0.76.2 with new architecture enabled.

No clear repro, it seems to be frequent though

**Comment by believer** [comment]
@jakex7 I've tried to create a minimal reproduction, but I can't get it to crash or show the wrong colors.

There seems to be something though, since more people are reporting similar issues, but I'm sorry that I can't provide a clear case where it fails.

**Comment by jakex7** [comment]
Hey @believer,  

Appreciate your efforts! I've implemented a blind fix in #2570 that *should* address the issue. Could you try applying it as a patch and test it over to confirm? Thanks!

**Comment by believer** [comment]
Ohh awesome, we've patched it in and initial results look very promising! We have a case where a logo consistently lost its color (couldn't repro it though 😅) and this now seems to work.

We'll continue testing it during the day to see if we get weird colors or crashes. Will report back later today!

**Comment by believer** [comment]
We haven't seen any crashes or color issues since we added the patch earlier today. I believe this was the fix 🎉 Thank you so much @jakex7!

**Comment by boazarad88** [comment]
Hi @believer @jakex7 

My team is also experiencing this issue (no crash though, just `currentColor` being stale).
Unfortunately we also don't have an easy reproduce, but it reproduced for us consistently using Metro hot reloading (not sure how to demonstrate this, but I hope this helps in investigation).

After seeing https://github.com/software-mansion/react-native-svg/pull/2570 I tried applying a similar fix for `color_`  here https://github.com/software-mansion/react-native-svg/pull/2573 and can verify that it works (using the hot reloading hack).

This might not be the actual fix but I hope this helps in finding the actual cause 🙏

**Comment by gituser8796** [comment]
@jakex7 do we have expected release date for this one?

**Comment by augusthjerrild** [comment]
We are experiencing the same thing in our app. Only happens when using navigation.reset. First reset, a lot of svg's changes color and some disappears, and after second reset the app crashes completely :-)

Sounds very promising with the fix :-)!

**Comment by Dunedubby** [comment]
I can also confirm that the patch works! Thanks @jakex7!

**Comment by jakex7** [comment]
> @jakex7 do we have expected release date for this one?

I'm planning to release a new version early next week. Thanks everyone for testing it!

**Comment by Unuuuuu** [comment]
Hi @jakex7 Thank you for your work.
Could you let me know if there’s an update on the release schedule?
