### ISSUE TITLE
Path not working on Android

### ISSUE THREAD

**Issue by zaguiini** [software-mansion/react-native-svg#648]
It just shows blank.

Snippet:

```js
<Svg
  width={size}
  height={size}
  viewBox={`0 0 ${size} ${size}`}
>
  <Path
    fill={color}
    d="M65.92 66.34h2.16c14.802.42 30.928 6.062 29.283 20.35l-1.618 13.32c-.844 6.815-5.208 7.828-13.972 7.866H52.23c-8.764-.038-13.13-1.05-13.973-7.865l-1.62-13.32C34.994 72.4 51.12 66.76 65.92 66.34zM49.432 43.934c0-9.82 7.99-17.81 17.807-17.81 9.82 0 17.81 7.99 17.81 17.81 0 9.82-7.99 17.807-17.81 17.807-9.82 0-17.808-7.987-17.808-17.806z"
  />
</Svg>
```

Not tested on iOS. The README example is working. Weird...

**Comment by zaguini** [comment]
What's the difference?

**Comment by msand** [comment]
Mainly the viewBox attribute I guess. It defines the coordinate system used in the svg together with the preserveAspectRatio attribute and meet/slice. The width and height attributes decide how many pixels the actual canvas/bitmap it gets rendered into has, you're setting both, while the viewBox attribute should only depend on the vector data, not the render target.
