### ISSUE TITLE
[ts] Type error when assigning ref to <Rect />

### ISSUE THREAD

**Issue by xzilja** [software-mansion/react-native-svg#802]
I'm using `React.createRef()` method to set ref on rectangle i.e.

```
class MyClass extends React.Component<{}> {
  rectangleRef = React.createRef()

  render() {
    return ( <Svg> <Rect ref={this.rectangleRef} /> </Svg> )
  } 
}
```

This yields following typescript error:

> [ts]
> Type 'RefObject<{}>' is not assignable to type 'string | ((instance: Component<RectProps, any, any> | null) => any) | RefObject<Component<RectProps, any, any>> | undefined'.
>   Type 'RefObject<{}>' is not assignable to type 'RefObject<Component<RectProps, any, any>>'.
>     Type '{}' is not assignable to type 'Component<RectProps, any, any>'.
>       Property 'setState' is missing in type '{}'.
> index.d.ts(69, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RectProps, any, any>> & Readonly<{ children?: ReactNode; }> & Readonly<RectProps>'
> (JSX attribute) ref: React.RefObject<{}>

I'm not sure what else  I can do here to fix it to be honest. Is new `createRef()` supported in latest available react-native-svg@7.0.3?

**Comment by msand** [comment]
Seems to work fine, I guess it's just the typescript definitions. A pr to fix that would be very welcome.

**Comment by IljaDaderko** [comment]
I'll jump on this as I get some time 👍

**Comment by IljaDaderko** [comment]
Closing this as issue comes from `@types/react` package
