### ISSUE TITLE
SVG not being rendered correctly

### ISSUE THREAD

**Issue by rarenatoe** [software-mansion/react-native-svg#850]
This is the svg file in question. I have removed whitespaces and compressed it as suggested in other threads/forums:
`<?xml version="1.0" encoding="UTF-8"?><svg width="20px" height="27px" viewBox="0 0 20 27" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><polygon id="path-1" points="0 0 16 0 16 23 7.82151442 14.698999 0 23"></polygon><filter x="-21.9%" y="-10.9%" width="143.8%" height="130.4%" filterUnits="objectBoundingBox" id="filter-2"><feOffset dx="0" dy="1" in="SourceAlpha" result="shadowOffsetOuter1"></feOffset><feGaussianBlur stdDeviation="1" in="shadowOffsetOuter1" result="shadowBlurOuter1"></feGaussianBlur><feColorMatrix values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.2 0" type="matrix" in="shadowBlurOuter1"></feColorMatrix></filter></defs><g id="PP" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="Projects-List" transform="translate(-285.000000, -208.000000)" fill-rule="nonzero"><g id="Content" transform="translate(16.000000, 157.000000)"><g id="Open-Issues"><g id="Project_symbol" transform="translate(0.000000, 52.000000)"><g id="Group-2" transform="translate(271.000000, 0.000000)"><g id="Rectangle-Copy"><use fill="black" fill-opacity="1" filter="url(#filter-2)" xlink:href="#path-1"></use><use fill="#FFC944" xlink:href="#path-1"></use></g><path d="M8.11682533,12.123423 L5.5067159,13.4956387 C4.5301607,14.0090442 3.889933,13.5423561 4.07620428,12.4563112 L4.57469082,9.54991163 L2.46306793,7.49158803 C1.67301818,6.72147985 1.91902371,5.96837257 3.00947475,5.80992076 L5.92766581,5.38588278 L7.23272053,2.7415531 C7.72099813,1.75219462 8.51326561,1.75343683 9.00093014,2.7415531 L10.3059848,5.38588278 L13.2241759,5.80992076 C14.3159978,5.96857177 14.5596405,6.72244678 13.7705827,7.49158803 L11.6589598,9.54991163 L12.1574464,12.4563112 C12.3439518,13.5437214 11.7022638,14.0083996 10.7269347,13.4956387 L8.11682533,12.123423 Z" id="svg-icon-star" stroke="#FFC944" fill="#FFFFFF"></path></g></g></g></g></g></g></svg>`

However whereas every other SVG renderer/editor displays it correctly (a yellow bookmark with a white star in it), react-native-svg/react-native-svg-uri only displays the white star.
Can someone illuminate me over what is happening?

**Comment by renato-bvdash** [comment]
While investigating, it seems like the property xlink not being supported might be what's causing the issue.
Does anyone know how I could transform this?

**Comment by kristerkari** [comment]
I tried the image with the [React Native SVG transformer](https://github.com/kristerkari/react-native-svg-transformer) that I have created, and the image renders correctly for me. I don't think that the bug is is in this library, so probably `react-native-svg-uri` has a bug.

**Comment by msageryd** [comment]
For what it's worth, I ran your SVG through svgo and got an equal image, half the file size and with simpler SVG code. All the SVGs I import into my app goes through svgo. I've found that I get smaller SVG files with less problems. I actually run them twice through svgo. It seems that some optimization possibilities are not identified at the first run.

Your SVG after svgo
```xml
<svg xmlns="http://www.w3.org/2000/svg" 
  xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="27">
  <defs>
    <polygon id="b" points="0 0 16 0 16 23 7.82151442 14.698999 0 23"/>
    <filter id="a" width="143.8%" height="130.4%" x="-21.9%" y="-10.9%" filterUnits="objectBoundingBox">
      <feOffset dy="1" in="SourceAlpha" result="shadowOffsetOuter1"/>
      <feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="1"/>
      <feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.2 0"/>
    </filter>
  </defs>
  <g transform="translate(2 1)">
    <use filter="url(#a)" xlink:href="#b"/>
    <use xlink:href="#b"/>
  </g>
  <path d="M10.117 13.123l-2.61 1.373c-.977.513-1.617.046-1.43-1.04l.498-2.906-2.112-2.058c-.79-.77-.544-1.524.546-1.682l2.919-.424 1.305-2.644c.488-.99 1.28-.989 1.768 0l1.305 2.644 2.918.424c1.092.159 1.336.912.547 1.682l-2.112 2.058.498 2.906c.187 1.088-.455 1.552-1.43 1.04l-2.61-1.373z"/>
</svg>
```

Here are the params I use for svgo:

```javascript
const SVGO = require('svgo');
let fs = require('fs');
const fileName = process.argv[2];

svgo = new SVGO({
  plugins: [
    {
      cleanupAttrs: true,
    },
    {
      removeDoctype: true,
    },
    {
      removeXMLProcInst: true,
    },
    {
      removeComments: true,
    },
    {
      removeMetadata: true,
    },
    {
      removeTitle: true,
    },
    {
      removeDesc: true,
    },
    {
      removeUselessDefs: true,
    },
    {
      removeEditorsNSData: true,
    },
    {
      removeEmptyAttrs: true,
    },
    {
      removeHiddenElems: true,
    },
    {
      removeEmptyText: true,
    },
    {
      removeEmptyContainers: true,
    },
    {
      removeViewBox: true,
    },
    {
      cleanUpEnableBackground: true,
    },
    {
      convertStyleToAttrs: false, //do not activate!
    },
    {
      convertColors: true,
    },
    {
      convertPathData: true,
    },
    {
      convertTransform: true,
    },
    {
      removeUnknownsAndDefaults: true,
    },
    {
      removeNonInheritableGroupAttrs: true,
    },
    {
      removeUselessStrokeAndFill: true,
    },
    {
      removeUnusedNS: true,
    },
    {
      cleanupIDs: true,
    },
    {
      cleanupNumericValues: true,
    },
    {
      moveElemsAttrsToGroup: true,
    },
    {
      moveGroupAttrsToElems: true,
    },
    {
      collapseGroups: true,
    },
    {
      removeRasterImages: true,
    },
    {
      mergePaths: true,
    },
    {
      convertShapeToPath: false,
    },
    {
      sortAttrs: true,
    },
    {
      transformsWithOnePath: true,
    },
    {
      removeDimensions: true,
    },
    {
      removeAttrs: { attrs: '(stroke|fill)' },
    },
  ],
});

fs.readFile(fileName, (err, file) => {
  if (err) return console.log(err);

  const svg = file.toString();
  const opt = svgo.optimize(svg).then((result1) => {
    const opt2 = svgo.optimize(result1.data).then((result2) => {
      fs.writeFileSync('./out.svg', result2.data);
    });
  });
});
```

**Comment by renato-bvdash** [comment]
thank you for your help. that narrows it to react-native-svg-uri.
